### ISSUE TITLE
Error: Cannot find module '@expo/server/build/vendor/http' after upgrading from v49.0.3 to v51.0.0

### ISSUE THREAD

**Issue by izner32** [expo/expo#28703]
### Minimal reproducible example

https://github.com/expo/expo

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

My iOS device automatically updated Expo Go. Now, I can't run my app on Expo Go without upgrading to the latest version, v51. However, after upgrading to v51, I'm unable to launch the app using 'npm run start.' I'm encountering the following error: Error: Cannot find module '@expo/server/build/vendor/http'.

### Environment

N/A

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✖ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Dependency tree validation for expo-cli failed. This validation is only available on Node 16+ / npm 8.
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that native modules use compatible support package versions for installed Expo SDK
Unexpected error while running 'Check that native modules use compatible support package versions for installed Expo SDK' check:
Error: Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Check that packages match versions required by installed Expo SDK

**Comment by j0nah** [comment]
@izner32 did you solve this? I'm having the same issue

**Comment by aotakeda** [comment]
for me what fixed was running `npm i @expo/server`

**Comment by gauravRz** [comment]
hey, i am having this  issue with my "expo": "~52.0.11", and nide version => v18.20.5. I am not quite sure about the latest expo version it was built with, but have a gut feeling that expo 51 was used. Anyways, when i am trying to start the metro server "npx expo start" , i am getting this issue Error: Cannot find module '@expo/server/build/vendor/http'. how can i solve this, tried removing node-modules, and also tried installing @expo/server explicitly.  What is the issue, and how can i fix this?

**Comment by Antyos** [comment]
I am having the same issue. I created a minimal test application using `pnpx create-expo-app@latest` (where `latest` seems to be 3.1.1 as of writing) and `pnpx run reset-project`. I get the error `Error: Cannot find module '@expo/server/build/vendor/http'` when running with `pnpx expo start`, but if I run with `npx expo start`, it works fine (even though it's technically installed through pnpm).

Running `pnpx expo install -- --fix` does not seem to resolve the issue.

**Comment by benyamynbrkyc** [comment]
> I am having the same issue. I created a minimal test application using `pnpx create-expo-app@latest` (where `latest` seems to be 3.1.1 as of writing) and `pnpx run reset-project`. I get the error `Error: Cannot find module '@expo/server/build/vendor/http'` when running with `pnpx expo start`, but if I run with `npx expo start`, it works fine (even though it's technically installed through pnpm).
> 
> Running `pnpx expo install -- --fix` does not seem to resolve the issue.

Can confirm, having the same experience as well, started a fresh project, expo version: `"expo": "~52.0.23"`

**Comment by ffrz** [comment]
I also had the same issue on ~52.0.24 after installing some packages with `npx expo install`. 
I don't understand the actual problem, but I checked in the node_modules directory and @expo/server and some other required modules are not there. Finally I try to run the command `npx expo install --fix` and it worked for me.
Here are the command results, hopefully someone can analyze the problem.
```
npx expo install --fix`
Skipped checking expo-router dependencies: expo-router/doctor.js not found.
The following packages should be updated for best compatibility with the installed expo version:
  expo@52.0.23 - expected version: ~52.0.24
  expo-router@3.1.0 - expected version: ~4.0.16
  expo-splash-screen@0.29.18 - expected version: ~0.29.19
Your project may not work correctly until you install the expected versions of the packages.
› Installing 3 SDK 52.0.0 compatible native modules using npm
> npm install
```

**Comment by Arttii** [comment]
This worked for me `pnpm --package=@expo/server dlx  expo start `

**Comment by jfvillablanca** [comment]
there must be something wrong with the `pnpx` alias. `pnpx expo start` doesn't work but `pnpx exec expo start` does work

**Comment by madhavarora03** [comment]
Well, I tried for hours, reinitialized my project twice, updated my dependencies and reconfigured my project. However, `pnpx expo run:android` doesn't work. Must use `npx expo run:android` after prebuild with `npx`. I don't know why `pnpm` doesn't work... Anybody has any idea?

**Comment by rrooddooxx** [comment]
same here, everything fine with `pnpm exec expo start`or `npx expo start`, but always failing on `pnpx expo start`

**Comment by cyanface** [comment]
> Well, I tried for hours, reinitialized my project twice, updated my dependencies and reconfigured my project. However, `pnpx expo run:android` doesn't work. Must use `npx expo run:android` after prebuild with `npx`. I don't know why `pnpm` doesn't work... Anybody has any idea?

totally the same..

**Comment by jdbohrman** [comment]
Same here using Bun

**Comment by FleetAdmiralJakob** [comment]
Hi guys, I used pnpm and got this error using `pnpm dlx expo run:android` the error was gone using `pnpm exec expo run:android`

**Comment by zeynepyldzz** [comment]
Hello, I tried typing npx expo start and it worked.

**Comment by jesse-ppd** [comment]
`pnpm ios`  works on my end

**Comment by archcorsair** [comment]
If you're like me and following the [Expo getting started guide](https://docs.expo.dev/get-started/set-up-your-environment/?platform=ios&device=physical&mode=development-build&buildEnv=local#run-the-project-on-your-device) in 2025 and are on the step where you should run:
```
npx expo run:ios --device
```
🛑  **Don't** make the same mistake I did and use:
```
pnpm dlx expo run:ios
```
✅ Instead use run this and it will work:
```
pnpm exec expo run:ios
```

**Comment by FleetAdmiralJakob** [comment]
Now the only question remains: Why does `pnpm exec` work and `pnpm dlx` doesn't?
