### ISSUE TITLE
expo 57 fails to compile on Xcode 26.3 when building from source with error sending 'emitter' risks causing data races

### ISSUE THREAD

**Issue by shamilovtim** [expo/expo#47539]
### Minimal reproducible example

https://github.com/shamilovtim/expo-emitter-error-repro

### Steps to reproduce

Platform: iOS.
Environment: local native iOS build / bare Expo project.
Package manager: pnpm 11.7.0.

The repro intentionally includes the generated `ios/` project and sets `EXPO_USE_PRECOMPILED_MODULES` to `false` in `ios/Podfile.properties.json`, because the failure only appears when `expo-modules-core` is compiled from Swift source.

1. Clone the minimal reproduction repository.
2. Install dependencies:

```sh
pnpm install
```

3. Install pods:

```sh
pnpm pod-install
```

4. Build the failing ExpoModulesCore target:

```sh
pnpm build:expo-modules-core
```

You can also reproduce through the app scheme:

```sh
pnpm build:ios
```

Expected result: `ExpoModulesCore` compiles successfully.

Actual result: the build fails in `expo-modules-core@57.0.2/ios/Core/Events/EventEmitter.swift`:

```text
EventEmitter.swift:52:17: error: sending 'emitter' risks causing data races
      guard let emitter else {
                ^~~~~~~

EventEmitter.swift:79:17: error: sending 'emitter' risks causing data races
      guard let emitter, let appContext else {
                ^~~~~~~
```

The Swift frontend is invoked with `-swift-version 6` by the `ExpoModulesCore` pod. The local toolchain is Xcode 26.3 / Apple Swift 6.2.4.

### Environment

```text
expo-env-info 2.1.0 environment info:
    System:
      OS: macOS 26.5.2
      Shell: 3.5.1 - /usr/local/bin/fish
    Binaries:
      Node: 24.13.0 - /Users/admin/.local/share/mise/installs/node/24.13.0/bin/node
      npm: 11.6.2 - /Users/admin/.local/share/mise/installs/node/24.13.0/bin/npm
      Watchman: 2026.01.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/admin/.local/share/mise/installs/ruby/3.4.8/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.2, iOS 26.2, macOS 26.2, tvOS 26.2, visionOS 26.2, watchOS 26.2
      Android SDK:
        API Levels: 34, 35, 36
        Build Tools: 34.0.0, 35.0.0, 36.0.0
        System Images: android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2026.1 AI-261.23567.138.2611.15503007
      Xcode: 26.3/17C529 - /usr/bin/xcodebuild
    npmPackages:
      expo: 57.0.2 => 57.0.2 
      react: 19.2.3 => 19.2.3 
      react-native: 0.86.0 => 0.86.0 
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```text
Running 20 checks on your project...
20/20 checks passed. No issues detected!
```

**Comment by grace4succession** [comment]
I have the same issue.  Just started today

**Comment by theeket** [comment]
Expo bumped minimum Xcode requirements to Xcode 26.4 / Swift 6.3 since **Expo 56** ([Changelog](https://expo.dev/changelog/sdk-56#tool-version-bumps)).

Update Xcode to 26.4 – 26.6 should fix this issue.

**Comment by tsapeta** [comment]
This 👆 is correct, SDK 56 and 57 require Xcode 26.4

**Comment by kuldeep-kth** [comment]
Hey guys, any other fixes?

Currently i am not able to upgrade to macos tahoe and the highest xcode support is 26.3

**Comment by VictorRiz-del** [comment]
who has found the resolution

**Comment by VictorRiz-del** [comment]
https://www.native-templates.com/blog/expo-sdk-57-ios-build-fails-xcode-26

use this
