### PR TITLE
the import of Clipboard was not done properly

### PR DESCRIPTION
**Pull request by hassanAwanAlvi**
The Clipboard Object was not imported properly, that is why it was not working with expo ~41.0.0
Just updated it.

# Why

I tried to import it, however, it was causing crash.  

# How

It is just an update in documentation. 

# Test Plan

1- Create a simple expo project.
2- install expo-clipboard 
             #expo install expo-clipboard

3- Try importing 
           #import * as Clipboard from 'expo-clipboard';  
           # Clipboard.setString('mail.google.com'); // this will give error TS2339: Property 'setString' does not exist on type 'typeof import

4- Change it to
         #import Clipboard from 'expo-clipboard';  
         # Clipboard.setString('mail.google.com'); //works fine

# Checklist

- [ ] Documentation is up to date to reflect these changes (eg: https://docs.expo.io and README.md).
- [ ] This diff will work correctly for `expo build` (eg: updated `@expo/xdl`).
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

**Comment by EvanBacon** [comment]
Cannot repro https://snack.expo.dev/@bacon/clipboard-import-works-as-expected

**Comment by hassanAwanAlvi** [comment]
> Cannot repro https://snack.expo.dev/@bacon/clipboard-import-works-as-expected

dev Dependencies

```
"devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "jest-expo": "~41.0.0",
    "typescript": "~4.0.0"
  },

```
Try it with Typescript ... 
Screenshot attached ... 

[https://paste.pics/DVL89](url)

**Comment by Simek** [comment]
Hmm, refs https://github.com/expo/expo/pull/14199?

**Comment by EvanBacon** [comment]
Closing because there is definitely no default export in expo-clipboard [ref](https://github.com/expo/expo/blob/b0f66be95b0889e7e986c0401b3adb4823e8d0aa/packages/expo-clipboard/src/Clipboard.ts#L39).
