### ISSUE TITLE
TypeError · undefined is not a function (evaluating 'c.askAsync(e)')

### ISSUE THREAD

**Issue by manelpb** [expo/expo#2087]
After upgrading to 29.0.0, I'm getting a bunch of those errors reported by Bugsnag :/

Any idea on how to fix?

```
TypeError · undefined is not a function (evaluating 'c.askAsync(e)')
```

```TypeError · undefined is not a function (evaluating 'o.getInfoAsync(e,t)')```
```/data/user/0/MY_APP_NAME/files/29.0.0/cached-bundle-experience-%40username%2FMY_APP_NAME-1805053905-29.0.0:339:284getInfoAsync```

Android
apiLevel 24

**Comment by manelpb** [comment]
The error is related to this thread: https://forums.expo.io/t/cant-use-permissions-api-in-sdk-29/12109/7

By following the steps there, i was able to get this working again. 

Still a bug tho.

**Comment by sjchmiela** [comment]
Hi @manelpb, thanks for submitting the issue! This is a bug indeed, caused by Proguard overstripping methods from our modules. We'll fix it as soon as possible. 🙂

**Comment by manelpb** [comment]
Thank you!

**Comment by mjgallag** [comment]
Unfortunately disabling minification/proguard doesn't work for us as our detached app is too big so it leads to `Too many classes in --main-dex-list, main dex capacity exceeded`. @sjchmiela Any other workarounds we can try or ETA on fix? Thanks!

**Comment by sjchmiela** [comment]
Hi @mjgallag!

Could you please try appending the following snippet to the `proguard-rules.pro` file and then enabling the minification and stripping back?

```pro
-keepclassmembers class * {
  @expo.core.interfaces.ExpoProp *;
}
-keepclassmembers class * {
  @expo.core.interfaces.ExpoMethod *;
}

-keepclassmembers class * {
  @**.expo.core.interfaces.ExpoProp *;
}
-keepclassmembers class * {
  @**.expo.core.interfaces.ExpoMethod *;
}
```

```gradle
// app/build.gradle

// ...

buildTypes {
  // ...

  release {
    minifyEnabled true
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    // ...
  }
}
```

**Comment by mjgallag** [comment]
@sjchmiela these proguard rules seem to work, thanks for the quick turnaround, saved me from having to figure out them out!
