### ISSUE TITLE
ExpoKit: `java.lang.NoClassDefFoundError: Failed resolution of: BouncyCastleProvider`

### ISSUE THREAD

**Issue by tamayok** [expo/expo#1091]
Not sure why I keep crashing. Tried removing proguard files or changing minifyEnable: false. Below is my crash log

`Process: com.example.reactnative, PID: 6925
                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lorg/spongycastle/jce/provider/BouncyCastleProvider;
                                                                           at host.exp.expoview.Exponent.getBouncyCastleProvider(Exponent.java:366)
                                                                           at host.exp.expoview.Exponent.<init>(Exponent.java:131)
                                                                           at host.exp.expoview.Exponent.initialize(Exponent.java:115)
                                                                           at host.exp.exponent.experience.ReactNativeActivity.onCreate(ReactNativeActivity.java:143)
                                                                           at host.exp.expoview.ExponentActivity.onCreate(ExponentActivity.java:69)
                                                                           at android.app.Activity.performCreate(Activity.java:6010)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "org.spongycastle.jce.provider.BouncyCastleProvider" on path: DexPathList[[zip file "/data/app/com.example.reactnative-1/base.apk", zip file "/data/app/com.example.reactnative-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.reactnative-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.reactnative-1/lib/arm, /vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at host.exp.expoview.Exponent.getBouncyCastleProvider(Exponent.java:366) 
                                                                           at host.exp.expoview.Exponent.<init>(Exponent.java:131) 
                                                                           at host.exp.expoview.Exponent.initialize(Exponent.java:115) 
                                                                           at host.exp.exponent.experience.ReactNativeActivity.onCreate(ReactNativeActivity.java:143) 
                                                                           at host.exp.expoview.ExponentActivity.onCreate(ExponentActivity.java:69) 
                                                                           at android.app.Activity.performCreate(Activity.java:6010) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: org.spongycastle.jce.provider.BouncyCastleProvider
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 19 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Comment by r1nkel** [comment]
I have same error. My expo detach dependencies.
>dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:26.0.1'
  compile 'com.android.support:multidex:1.0.1'
  compile('host.exp.exponent:expoview:23.0.0@aar') {
    exclude group: 'com.facebook.android', module: 'facebook-android-sdk'
    exclude group: 'com.facebook.android', module: 'audience-network-sdk'
    exclude group: 'io.nlopez.smartlocation', module: 'library'
    transitive = true;
  }
  compile 'com.facebook.android:facebook-android-sdk:4.+'
  compile('com.facebook.android:audience-network-sdk:4.+') {
    exclude module: 'play-services-ads'
  }
  compile('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }
}

Removing `compile 'com.facebook.android:facebook-android-sdk:4.+'` solves the issue.

**Comment by r1nkel** [comment]
I have same error in my Samsung note 4 (other device doesn't have the error). I solve the issue by changing the dependency version from
`compile 'com.facebook.android:facebook-android-sdk:4.+'` to
`compile 'com.facebook.android:facebook-android-sdk:4.26.0'` (v4.27.0 - v4.29.0 causing the error)

**Comment by Bharat23** [comment]
@r1nkel Thanks it totally worked. I was facing this issue when running on an emulator having an older version of Android OS like Lollipop.

**Comment by helielson** [comment]
I'm facing the same problem running on a Moto G 1 with Android Lollipop.
Change the version of facebook sdk didn't work for me.

@r1nkel how did you find this solution? Maybe it could help me to find what is going on here.

**Comment by r1nkel** [comment]
I am just guessing the solution based on the error when detaching app. AFAIK when I re-detach using expo v25, I am not encounter this problem anymore.

**Comment by helielson** [comment]
I'm also using the v25 version of expo. I'll try to detach again.

**Comment by YKSing** [comment]
I am facing this problem by using v25 too. After adding `preDexLibraries = false`, it seems work.
```
dexOptions {
    javaMaxHeapSize System.getenv("DISABLE_DEX_MAX_HEAP") ? null : "8g"
    preDexLibraries = false
}
```

**Comment by wnadurski** [comment]
I have the same problem with expo v25. None of solutions mentioned above worked for me

**Comment by slvtrs** [comment]
@xiamike thanks for the great tips. Were you ever able to get it running through Android Studio though to build a signed APK?

**Comment by AlexCatch** [comment]
I'm also facing this issue & none of the above solutions work, it works on my S9 Plus (7.0) but doesn't work on a Lenovo tablet running 5.1

I get the same runtime error:

`
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/spongycastle/jce/provider/BouncyCastleProvider;
`

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. Recent posts indicate this remains an issue, could one of you please open a new issue with a repro case? We'll get it appropriately assigned and we'll be happy to investigate.

Cheers,  
Adam
