### ISSUE TITLE
[RN 0.66][SDK 44][iOS] expo-av no longer compatible with RN 0.66 (compile error)

### ISSUE THREAD

**Issue by Yonom** [expo/expo#15627]
### Summary

`expo-av` fails to compile on iOS in a react-native 0.66.4 project (it was working fine on SDK 43 + RN 0.66.4)

```
› Compiling expo-av Pods/EXAV » EXAV.m

❌  (node_modules/expo-av/ios/EXAV/EXAV.m:66:1)

  64 | @property (nonatomic, assign) int audioRecorderDurationMillis;
  65 | 
> 66 | @property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
     | ^ type of property 'EXModuleRegistry *' in class extension does not match property type in primary class
  67 | @property (nonatomic, weak) id<EXPermissionsInterface> permissionsManager;
  68 | 
  69 | @end
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

SDK 44

### Environment

```
  Expo CLI 5.0.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /opt/homebrew/Cellar/node@16/16.13.1/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.1.2 - /opt/homebrew/Cellar/node@16/16.13.1/bin/npm
      Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0, 32.0.0
        System Images: android-31 | Google Play ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.66.4 => 0.66.4 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Expo Workflow: bare
```

### Reproducible demo

- `expo init yonom --yes && cd yonom`
- `expo install expo-av`
- `yarn add react-native@0.66.4`
- `expo prebuild --skip-dependency-update=react-native`
- `expo run:ios`

❌ Build fails

**Comment by schiller-manuel** [comment]
This is a name clash of property `moduleRegistry` that is already declared in RCTModuleRegistry:
https://github.com/facebook/react-native/blob/3bd11599c9d6aca5fa29ad291e9ad8b4a353bef4/React/Base/RCTBridgeModule.h#L118

longer error message:

````
node_modules/expo-av/ios/EXAV/EXAV.m:66:1: error: type of property 'EXModuleRegistry *' in class extension does not match property type in primary class
@property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
^
In module 'React' imported from node_modules/expo-av/ios/EXAV/EXAV.h:5:
ios/Pods/Headers/Public/React-Core/React/RCTBridgeModule.h:127:58: note: property declared here
@property (nonatomic, weak, readonly) RCTModuleRegistry *moduleRegistry;
````

This name clash is introduced in #14904, more specifically:

https://github.com/expo/expo/pull/14904/files#diff-9b366bdef454bb571ed72979846a05a69d750213a4acfc5c3c721616a19cd9c8R58

So I guess the property in `EXAV.m` needs to be renamed (and of course all uses of that property), e.g.

````diff
- @property (nonatomic, weak) EXModuleRegistry *moduleRegistry;
+ @property (nonatomic, weak) EXModuleRegistry *expoModuleRegistry;
````

**Comment by Yonom** [comment]
I'm not 100 % sure if the name `moduleRegistry` can be safely changed or if its part of the expo modules interface... If someone lets me know that it can be safely changed, I'll create a PR with a fix

**Comment by jonotrybe** [comment]
I just tried locally and 
renaming moduleRegistry to expoModuleRegistry
plus _moduleRegistry to _expoModuleRegistry

is working so far. Im not up to speed on ios dev so this was a guess.

**Comment by nomi9995** [comment]
for now, you can install this as a temp solution
**package.json**
```
"expo-av": "https://gitpkg.now.sh/expo/expo/packages/expo-av?master"
```

**Comment by nero2009** [comment]
Thank you

**Comment by wbroek** [comment]
The temp solution (using master of expo-av) is working but when is the update due?

**Comment by radko93** [comment]
@Kudo would you be able to trigger an update?
