### PR TITLE
fix(babel-preset-expo): avoid Hermes V1 native async regressions

### LINKED ISSUE #45592: 🐛 [SDK 56 preview.7] await of an async function's Promise resolves to undefined while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS
# 🐛 [SDK 56 preview.7] `await` of an async function's Promise resolves to `undefined` while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS

## Summary

On `expo@56.0.0-preview.7` (`react-native@0.85.3`, Hermes default, iOS simulator), `await aPromise` resolves with `undefined` *before* the underlying `async function` reaches its `return` statement. The function continues executing in the background, its `return` does eventually fire with the correct value, but the awaiting caller has already moved on with `undefined`.

The same userland code works correctly on `expo@55.0.23` / `react-native@0.83.6`.

The most visible symptom: **every RTK Query `queryFn`-based endpoint fails** because the dispatcher's internal `await executeRequest(arg)` resolves to `undefined`, then `finalQueryReturnValue.data` access throws `TypeError: Cannot read property 'data' of undefined`. Identical `@reduxjs/toolkit@2.11.2` works on SDK 55 with the same userland code.

## Minimal reproducible example

**Repro:** https://github.com/azaars/expo-56-rtk-await-bug

```bash
git clone https://github.com/azaars/expo-56-rtk-await-bug.git
cd expo-56-rtk-await-bug
npm install
npx expo prebuild --clean --platform ios
npx expo run:ios
```

The repro is `npx create-expo-app@latest --template blank-typescript` scaffolded, then bumped to `expo@next`, with `@reduxjs/toolkit` + `react-redux` added and a single `queryFn` endpoint that returns `{ data: { message: 'hello from queryFn' } }`. Three small files: `src/api.ts` (createApi), `src/store.ts` (configureStore), `App.tsx` (Provider + a child that subscribes via `useGetThingQuery()`).

## Steps to reproduce

1. Clone and install per above.
2. `npx expo prebuild --clean --platform ios && npx expo run:ios`.
3. App boots in iOS simulator. The single screen renders.

## Expected behavior

```
isLoading: false
isError:   false
data:      {"message":"hello from queryFn"}
error:     (none)
```

## Actual behavior

```
isLoading: false
isError:   true
data:      undefined
error:     {"status":"CUSTOM_ERROR","error":"Cannot read property 'data' of undefined"}
```

Metro logs:

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning: {"data":{"message":"hello from queryFn"}}
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       In the case of an unhandled error, no tags will be "provided" or "invalidated".
       [TypeError: Cannot read property 'data' of undefined]
```

## Diagnostic evidence

In a parallel investigation I patched `node_modules/@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` at the dispatcher's await call site:

```js
// Patched at line 1091 of executeEndpoint:
const __exr_promise = executeRequest(arg.originalArgs);
console.log('[RTK PATCH] BEFORE-AWAIT typeof:', typeof __exr_promise,
            'isPromise:', __exr_promise instanceof Promise,
            'isUndefined:', __exr_promise === undefined);
finalQueryReturnValue = await __exr_promise;
console.log('[RTK PATCH] AFTER-AWAIT finalQueryReturnValue =',
            JSON.stringify(finalQueryReturnValue),
            'type:', typeof finalQueryReturnValue);

// And patched executeRequest's return statement (~line 1041):
const __ret = __spreadProps(__spreadValues({}, result), { data: transformedResponse });
console.log('[RTK PATCH] executeRequest about to return:',
            JSON.stringify(__ret), 'type:', typeof __ret);
return __ret;
```

Time-ordered output from the iOS simulator (with the queryFn reduced to a synchronous return of a hoisted constant `{ data: [] }` to eliminate userland variables):

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning hoisted: {"data":[]}
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       [TypeError: Cannot read property 'data' of undefined]
LOG    [RTK PATCH] executeRequest about to return: {"data":[]} type: object
```

Note the **time ordering**:

1. `BEFORE-AWAIT` confirms `executeRequest()` returns a real `Promise` synchronously (`isPromise: true`, `isUndefined: false`).
2. `AFTER-AWAIT` resumes immediately with `undefined`.
3. The dispatcher's catch block logs the unhandled error.
4. **Only afterwards** does `executeRequest`'s body reach its return statement and log the correct value.

A nested-`await` test inside the queryFn itself behaves consistently — the inner await resolves with the right value, but only after RTK's outer await has already moved on:

```
LOG    [REPRO] outer enter
LOG    [REPRO] inner enter
LOG    [REPRO] before await, p instanceof Promise: true typeof p: object
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  [TypeError: Cannot read property 'data' of undefined]
LOG    [REPRO] after await, r: {"data":[]} typeof: object
```

## Same pattern in non-RTK code

In a private brownfield app on the same SDK 56 preview.7 stack, the same pattern surfaces in code that has nothing to do with RTK Query:

```ts
const localPlants = await soloTaskService.getLocalPlants('solo-user', 'active');
// → throws TypeError: Cannot read property 'map' of undefined on the next line
const mappedPlants = localPlants.map((lp) => ({...}));
```

`SoloTaskService.getLocalPlants` is a class `async` method that ends with `return rows.map(...)`. The await receives `undefined`. Same root cause, completely separate call path. Not included in the public minimal repro because reproducing it cleanly requires recreating that class context, but happy to share if useful.

## What was ruled out

- **`@reduxjs/toolkit` version**: identical `2.11.2` works on SDK 55 / RN 0.83.6 with the same userland code.
- **`react-redux` version**: `9.2.0`, unchanged across SDKs.
- **`react-native-reanimated`/`worklets` babel plugin**: bug reproduces with `react-native-reanimated/plugin` removed from `babel.config.js` and Metro restarted with `--clear`.
- **Userland code**: queryFn reduced to a hoisted-constant synchronous return. Bug persists.
- **`baseQuery: fakeBaseQuery()` vs `baseQuery: async () => ({ data: null })`**: bug fires with both.
- **`providesTags`** as static array vs callback: no difference.
- **Node test suite**: `npm test` (Node + ts-jest + better-sqlite3, no Hermes) passes 3028/3030 in the brownfield app on SDK 56. Bug is iOS-Hermes-runtime-only.

## Suspected scope

The dispatcher in `@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` declares `executeRequest` as a hoisted nested `async function` inside another `async function`:

```js
async function executeEndpoint(arg, ...) {
  // ...
  async function executeRequest(finalQueryArg) {
    // ...
    return __spreadProps(...);
  }
  // ...
  finalQueryReturnValue = await executeRequest(arg.originalArgs);
  // → undefined here despite executeRequest returning a Promise that
  //   eventually resolves to the correct value
}
```

The same nested-async-function-declaration pattern is what surfaces the bug in the non-RTK case as well. This points to Hermes RN 0.85.3's async-function / Promise resolution machinery rather than RTK or app code.

## Environment

```
expo-env-info 2.0.12 environment info:
  System:
    OS: macOS 26.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 25.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 11.12.1 - /opt/homebrew/bin/npm
    Watchman: 2025.11.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
  IDEs:
    Android Studio: 2025.1 AI-251.26094.121.2513.14007798
    Xcode: 26.4.1/17E202 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^56.0.0-preview.7 => 56.0.0-preview.7
    react: 19.2.3 => 19.2.3
    react-dom: 19.2.3 => 19.2.3
    react-native: 0.85.3 => 0.85.3
  npmGlobalPackages:
    eas-cli: 16.19.3
  Expo Workflow: bare (custom dev client via expo-dev-client)
```

Additional minimal-repro deps:

- `@reduxjs/toolkit@2.11.2`
- `react-redux@9.2.0`
- `babel-preset-expo@56.0.5`

## Asks

1. Is this a known issue in the SDK 56 preview Hermes / RN 0.85.3?
2. Workaround guidance for the next 1–2 weeks until SDK 56 GA?
3. Happy to attach the patched `rtk-query.legacy-esm.js`, run further traces, or drop into Discord for live debugging if useful.

### PR DESCRIPTION
**Pull request by gronxb**
# Why

Fixes #45592.

Expo SDK 56 selects the Hermes V1 Babel profile when the Metro caller engine is Hermes. That profile preserves native async/await, while the older Hermes V0/default profile includes `@babel/plugin-transform-async-to-generator`.

On RN 0.85 / Hermes V1, an iOS Release minimal repro showed RTK Query receiving `undefined` from an awaited query result. The underlying async query function returned a valid `{ data }` object, but the outer awaited request chain resumed with `undefined`, producing `Cannot read property 'data' of undefined`.

# How

Force Hermes V1 async functions through Babel's `@babel/plugin-transform-async-to-generator` transform.

This keeps the change narrow to the Hermes V1 Babel profile and avoids the Hermes native async/await path that can resume selected await chains with `undefined`. The built preset output, plugin-list snapshots, and package changelog were updated with the source change.

Rejected alternative: keep native async/await in Hermes V1. The iOS Release repro showed RTK Query receiving `undefined` from an awaited query result, so preserving that path leaves the regression in place.

Directive: Revisit this once the underlying Hermes native async/await bug is fixed and covered by runtime tests.

# Test Plan

Automated test:

```sh
pnpm --filter babel-preset-expo test -- preset-config.test.ts --runInBand
```

Result:

```text
Test Suites: 1 passed, 1 total
Tests:       42 passed, 42 total
Snapshots:   8 passed, 8 total
```

Manual iOS Release repro:

1. Ran https://github.com/azaars/expo-56-rtk-await-bug before applying this transform.
2. Confirmed the failing state: `isError: true`, `data: undefined`, and `Cannot read property 'data' of undefined`.
3. Patched the repro's local `babel-preset-expo` Hermes V1 profile with this change.
4. Rebuilt and reran the same iOS Release repro.
5. Confirmed the fixed state: `isError: false`, `data: {"message":"hello from queryFn"}`, and `error: (none)`.

Before applying the Hermes V1 async-to-generator transform:

Before fix: iOS Release repro shows data undefined and TypeError

After applying the Hermes V1 async-to-generator transform:

After fix: iOS Release repro shows returned data and no error

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

**Comment by kitten** [comment]
While I'll look into this, this won't necessarily mean we'll merge this PR, just to give an early heads up. This isn't a regression that the test suite we created caught, however, if we are forced to re-enable this transform, this one in particular may have a knock-on effect of needing 3-4 more transforms (which can be seen in the upstream source)

Will have to have a look but just noting this early, so mostly will check on the original issue instead first

**Comment by gronxb** [comment]
@kitten 
Yes, I understand. With the introduction of Hermes v1, many Babel plugins were removed to improve bundler performance. However, if this PR is introduced, Babel would be added again, which goes against the original goal.

That said, while Hermes v1 now supports native async/await and Babel was removed for that reason, there appears to be a bug in the native async/await implementation. My intention is to let you know that we may need to consider temporarily adding the plugin as a workaround.

Thank you.

**Comment by kitten** [comment]
Superseded by #45601

We've narrowed this down to minimal test cases. Afterwards we were also able to identify the specific fixes that already existed in Hermes after the branch cut and version that React Native currently uses. That allows the fix PR to have a few targeted fixes instead.
