### ISSUE TITLE
expo-location: startGeofencingAsync is not a function

### ISSUE THREAD

**Issue by mRcSchwering** [expo/expo#15043]
### Summary

I am not getting geofencing to work in _expo-location_ (13.0.4). I stared of from the [TaskManager Example (docs)](https://docs.expo.dev/versions/latest/sdk/task-manager/#example) and changed it to use `Location.startGeofencingAsync`.
When I trigger this button in the app I get:
```
TypeError: _ExpoLocation__WEBPACK_IMPORTED_MODULE_2__.default.startGeofencingAsync is not a function
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

43.0.1

### Environment

Expo CLI 4.12.11 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.9.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/bin/yarn
      npm: 7.21.1 - /usr/local/bin/npm
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. `expo init` (blank, typescript)
2. `yarn add expo-location expo-task-manager`
3. paste below code into `button.tsx`
5. import it in _App.tsx_ and make `App` return `<View style={styles.container}><Button /></View>`
6. `yarn start`
7. click on _Run in web browser_
8. open inspector > console
9. click on _Enable background location_

```
import React from "react";
import { Text, TouchableOpacity } from "react-native";
import * as TaskManager from "expo-task-manager";
import * as Location from "expo-location";

const LOCATION_TASK_NAME = "geofencing-location-task";

const region: Location.LocationRegion = {
  identifier: "1",
  latitude: 52.4,
  longitude: 13.4,
  radius: 30,
};

const requestPermissions = async () => {
  const { status } = await Location.requestBackgroundPermissionsAsync();
  if (status === "granted") {
    await Location.startGeofencingAsync(LOCATION_TASK_NAME, [region]);
  }
};

const PermissionsButton = () => (
  <TouchableOpacity onPress={requestPermissions}>
    <Text>Enable background location</Text>
  </TouchableOpacity>
);

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }: any) => {
  const eventType: Location.LocationGeofencingEventType = data.eventType;
  const region: Location.LocationRegion = data.region;

  if (error) {
    console.log(error.message);
    return;
  }

  if (eventType === Location.LocationGeofencingEventType.Enter) {
    console.log("You've entered region:", region);
  } else if (eventType === Location.LocationGeofencingEventType.Exit) {
    console.log("You've left region:", region);
  }
});

export default PermissionsButton;
```
