### ISSUE TITLE
Upgrade expo from 49 -> 50 ["_interopRequireDefault is not a function js.hermes.engine"]

### ISSUE THREAD

**Issue by KacpiDrewniak** [expo/expo#27742]
### Minimal reproducible example

-

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Hi, I'm getting a TypeError: _interopRequireDefault error when upgrading my Expo SDK from 49 to 50. From what I know, this is related to the Babel compiler. I need some pointers on where to look for a solution. Has anyone had a similar error?

Here are some additional details that might be helpful:

I'm using the latest version of Expo CLI.
I've tried clearing the cache and restarting my computer.
I've searched for this error on Google and Stack Overflow, but I haven't found any solutions that work for me.
Any help would be greatly appreciated!

Here are some additional resources that you might find helpful:

Expo SDK 50 documentation: https://expo.dev/changelog/2024/01-18-sdk-50
Babel documentation on TypeError: _interopRequireDefault: [usunięto nieprawidłowy URL]
Stack Overflow thread on TypeError: _interopRequireDefault with Expo SDK 43: https://stackoverflow.com/questions/66327197/how-to-fix-typeerror-interoprequiredefault-is-not-a-function-in-create-react-ap
I hope this helps!

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.0 => 50.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

### Expo Doctor Diagnostics

The package  "@types/react-native" should not be installed directly in your project, as types are included with the "react-native" package.

One or more checks failed, indicating possible issues with the project.

**Comment by watadarkstar** [comment]
@KacpiDrewniak Did you figure this out?

**Comment by watadarkstar** [comment]
@KacpiDrewniak Can you post your `package.json`? I'm having the same issue and this is my package.json dependencies:

```
"dependencies": {
    "@config-plugins/react-native-google-cast": "7.0.0",
    "@expo/react-native-action-sheet": "4.0.1",
    "@expo/vector-icons": "14.0.0",
    "@launchdarkly/react-native-client-sdk": "10.0.3",
    "@miblanchard/react-native-slider": "2.3.1",
    "@native-html/iframe-plugin": "2.6.1",
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/hooks": "3.0.0",
    "@react-native-community/netinfo": "11.1.0",
    "@react-navigation/bottom-tabs": "6.5.2",
    "@react-navigation/drawer": "6.5.0",
    "@react-navigation/native": "6.1.1",
    "@react-navigation/native-stack": "6.9.7",
    "@react-navigation/stack": "6.3.10",
    "@segment/analytics-react-native": "2.10.0",
    "@segment/sovran-react-native": "1.0.4",
    "@sentry/react-native": "5.19.1",
    "@tanstack/react-query": "4.29.12",
    "@valasolutions/react-native-markdown": "1.0.3",
    "@xstate/react": "3.0.1",
    "algoliasearch": "4.14.2",
    "axios": "1.5.0",
    "date-fns": "2.29.3",
    "expo": "50.0.14",
    "expo-analytics-segment": "11.2.1",
    "expo-application": "5.8.3",
    "expo-auth-session": "5.4.0",
    "expo-av": "~13.10.5",
    "expo-build-properties": "0.11.1",
    "expo-constants": "15.4.5",
    "expo-dev-client": "3.3.11",
    "expo-device": "5.9.3",
    "expo-file-system": "16.0.8",
    "expo-font": "11.10.3",
    "expo-haptics": "12.8.1",
    "expo-image": "1.10.6",
    "expo-keep-awake": "12.8.2",
    "expo-linear-gradient": "12.7.2",
    "expo-linking": "6.2.2",
    "expo-mail-composer": "12.7.1",
    "expo-navigation-bar": "2.8.1",
    "expo-screen-orientation": "6.2.0",
    "expo-secure-store": "12.8.1",
    "expo-splash-screen": "0.26.4",
    "expo-sqlite": "~13.4.0",
    "expo-status-bar": "1.11.1",
    "expo-system-ui": "2.9.3",
    "expo-updates": "0.24.12",
    "expo-web-browser": "12.8.2",
    "get-youtube-id": "1.0.1",
    "graphql": "16.6.0",
    "graphql-request": "5.1.0",
    "he": "1.2.0",
    "immer": "9.0.16",
    "jwt-decode": "3.1.2",
    "lodash": "4.17.21",
    "markdown-it": "13.0.1",
    "markdown-it-footnote": "3.0.3",
    "markdown-it-style": "1.0.0",
    "node-forge": "1.3.1",
    "onesignal-expo-plugin": "1.3.0",
    "react": "18.2.0",
    "react-airplay": "1.2.0",
    "react-devtools-core": "4.27.8",
    "react-dom": "18.2.0",
    "react-error-boundary": "3.1.4",
    "react-native": "0.73.6",
    "react-native-circular-progress": "1.3.7",
    "react-native-draggable-flatlist": "4.0.0",
    "react-native-flipper": "0.212.0",
    "react-native-gesture-handler": "2.14.1",
    "react-native-google-cast": "4.8.0",
    "react-native-image-colors": "2.4.0",
    "react-native-iphone-x-helper": "1.3.1",
    "react-native-onesignal": "4.5.0",
    "react-native-reanimated": "3.6.1",
    "react-native-reanimated-carousel": "3.5.1",
    "react-native-render-html": "6.3.4",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "3.29.0",
    "react-native-svg": "14.1.0",
    "react-native-swipeable-item": "2.0.9",
    "react-native-system-setting": "1.7.6",
    "react-native-track-player": "4.0.1",
    "react-native-url-polyfill": "1.3.0",
    "react-native-webview": "13.6.4",
    "react-native-youtube-iframe": "2.2.2",
    "rehype-raw": "6.1.1",
    "rehype-stringify": "9.0.3",
    "remark-parse": "10.0.1",
    "remark-rehype": "10.1.0",
    "remove-markdown": "0.5.0",
    "search-insights": "2.11.0",
    "sentry-expo": "7.2.0",
    "tinycolor2": "1.6.0",
    "unified": "10.1.2",
    "xstate": "4.33.6",
    "zod": "3.21.4"
  },
  "devDependencies": {
    "@babel/core": "7.20.12",
    "@babel/preset-env": "7.22.7",
    "@babel/runtime": "7.22.6",
    "@graphql-codegen/add": "4.0.0",
    "@graphql-codegen/cli": "4.0.0",
    "@graphql-codegen/introspection": "4.0.3",
    "@graphql-codegen/typescript": "4.0.6",
    "@graphql-codegen/typescript-operations": "4.2.0",
    "@types/node": "20.4.1",
    "@types/react": "18.2.67",
    "@types/react-instantsearch-core": "6.26.3",
    "@types/remove-markdown": "0.3.1",
    "@types/tinycolor2": "1.4.3",
    "@typescript-eslint/eslint-plugin": "5.59.11",
    "@typescript-eslint/parser": "5.59.11",
    "@xstate/cli": "0.4.1",
    "babel-plugin-module-resolver": "5.0.0",
    "commitizen": "4.2.5",
    "cz-conventional-changelog": "3.3.0",
    "dotenv": "16.3.1",
    "eslint": "8.42.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-react": "7.31.0",
    "eslint-plugin-react-hooks": "4.6.0",
    "eslint-plugin-react-native": "4.0.0",
    "husky": "8.0.1",
    "jest": "29.7.0",
    "jest-expo": "50.0.4",
    "lint-staged": "13.0.3",
    "prettier": "2.7.1",
    "react-native-bundle-visualizer": "3.1.0",
    "react-native-flipper-performance-plugin": "0.4.0",
    "react-native-performance": "5.1.0",
    "react-native-performance-flipper-reporter": "5.0.0",
    "react-test-renderer": "18.2.0",
    "rn-flipper-async-storage-advanced": "1.0.5",
    "ts-node": "10.9.1",
    "ts-node-dev": "2.0.0",
    "typescript": "5.4.3"
  },
  ```

**Comment by michael-lmk** [comment]
Hi, i have same issue and for me this come from react-native-draggable-flatlist, when i remove this package the projet start succefully.
