### ISSUE TITLE
ExpoKit ios Use of undeclared identifier 'RCTPackagerConnection'

### ISSUE THREAD

**Issue by rxhivzero** [expo/expo#6487]
### Environment

 Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @ant-design/react-native: ^3.2.0 => 3.2.0 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

ExpoKit
### Steps to Reproduce
xcode archive ExpoKit Project

### Expected Behavior
build success

### Actual Behavior
Use of undeclared identifier 'RCTPackagerConnection'

--
If my comment out will work.
Maybe there is a problem with my _isDevModeEnabledForBridge?

/*
  if ([self _isDevModeEnabledForBridge:bridge]) {
    // Set the bundle url for the packager connection manually
    [[RCTPackagerConnection sharedPackagerConnection] setBundleURL:[bridge bundleURL]];
  }
*/

**Comment by makirby** [comment]
Having the same issue myself. Ejecting to an Expokit project on 36.0.0

**Comment by GuillaumeSarfati** [comment]
Exactly the same too

**Comment by allhaze** [comment]
Same issue :(
(after upgrade from v35 to v36)

**Comment by GuillaumeSarfati** [comment]
Tips if you just remove the 3 lines it's working

**Comment by tsapeta** [comment]
Hi everyone! Thanks for reporting this issue to us 😉 
I've fixed it in #6507 and tagged this new version of ExpoKit as `ios/2.14.2` so you can just update the tag from which Cocoapods downloads ExpoKit dependency in your `Podfile` 🙂

**Comment by makirby** [comment]
Great stuff. Thanks
