### PR TITLE
[android] Fully initialize Facebook SDK on older Expo SDKs

### LINKED ISSUE #6500: Facebook login not working with SDK35 after SDK36 release
## Description

expo-cli 3.11.1 nerfed facebook login.
A hour ago, before upgrading expo-cli this code used to  work perfectly.

			
## Expected Behavior

An hour ago before updating expo-cli this code worked perfectly

`const { type, token } = await Facebook.logInWithReadPermissionsAsync('< my actual facebook project id >', { permissions: ['public_profile', 'email'] }).catch(function(error) {
				// Handle Errors here.
				
        let errorCode = error.code;
        let errorMessage = error.message;
        // The email of the user's account used.
       let email = error.email;
       // The firebase.auth.AuthCredential type that was used.
       let credential = error.credential;
      console.log(errorCode, ' ', errorMessage, ' ', email, ' ', credential, ' ',);

});`	

I also tried Facebook.initializeAsync  but that did not work either

## Observed Behavior
Error from facebook is 
`E_FBLOGIN_APP_ID   Tried to perform Facebook login, but no Facebook app id was provided. Specify Facebook app id in Info.plist. `

error from expo is 
```
undefined is not an object (evaluating '_ref.type')
* src/actions/user.js:82:11 in _callee3$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- ... 13 more stack frames from framework internals
```

If I run Facebook.initializeAsync . I get 

`Facebook.initializeAsync is not a function`

## Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

 "expo-facebook": "~7.0.1",  does not work on ^8.0.0 either

Emulator is iPhone 11 Pro Max 13.3
Phone 1  is Pixel 3 Android version 10
Phone 2 is Samsung S8 Android version 9

## Reproducible Demo

I am not sure how to do this...

### PR DESCRIPTION
**Pull request by sjchmiela**
# Why

Should fix https://github.com/expo/expo/issues/6500, even though I wasn't able to reproduce the problem not by building Expo client from `master`, or from `sdk-36`, in debug or release mode.

# How

The error being logged is

```
GraphRequest can't be used when Facebook SDK isn't fully initialized
```

which [is only thrown](https://github.com/facebook/facebook-android-sdk/blob/3a1b00e84aa26df97c1f80e659c2b034309d381d/facebook-core/src/main/java/com/facebook/GraphResponse.java#L258-L262) if `Facebook.isFullyInitialized()` is `false`.

This is probably because we don't **fully initialize** Facebook SDK — only **initialize**.

This PR fixes this by fully initializing the SDK.

This has stopped working when we added Facebook autoinitialization customization feature, since now Expo client doesn't autoinitialize Facebook SDK.

# Test Plan

Couldn't reproduce the error, but the thought process for the fix seems reasonable.

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
looks fine to me, I'm okay with shipping as long as you've tested this and it at least doesn't make anything worse 🤷‍♂ thanks for looking into it!
