### ISSUE TITLE
[expo-in-app-purchases] [android] App crashes on launch with java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/vending/billing/IInAppBillingService$Stub;

### ISSUE THREAD

**Issue by acb** [expo/expo#15063]
### Summary

After updating `expo-in-app-purchases` from 9.1.0 -> 11.0.1 (also had to update `react-native-unimodules` from 0.11.0 -> 0.14.10) I can no longer boot my app on android.  Shortly after starting the app it crashes, and the message `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/vending/billing/IInAppBillingService$Stub;` is found via `logcat`.

I aware that `expo-in-app-purchases` 12 exists, but that suffers from the same Android build problems as [here](https://github.com/expo/expo/issues/7900).  11.0.1 seems like the only current way to upgrade to Android billing library 3 as required by Google.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.18.2 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      react: 17.0.2 => 17.0.2
      react-native: 0.66.2 => 0.66.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

* Create a new bare project (e.g. from `react-native init`)
* Install latest `react-native-unimodules` (0.14.10) (and all the post install linking according to [the docs](https://docs.expo.dev/bare/installing-unimodules/)
* Install `expo-in-app-purchases` at version 11.0.1
* Run `npx run-android`
* Watch app crash at startup

**Comment by cruzach** [comment]
You may need to [install expo modules](https://docs.expo.dev/bare/installing-expo-modules/) instead of unimodules, depending on your versions.

**Comment by acb** [comment]
@cruzach yeah I'm aware, that's why I was on 11.0.1, it doesn't need expo modules.

That said, I did try to update to `expo-in-app-purchases` 12.0.0 and remove unimodules and replace them with `expo` 43.0.2 and I get the same `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/vending/billing/IInAppBillingService$Stub;` error there.

I've also tried to add `implementation "com.android.billingclient:billing:4.0.0"` into my `app/build.gradle` and that doesn't help anything.  I'm at a loss, I just can't get this library to exist.

**Comment by acb** [comment]
This appears to have been a conflict with the `react-native-billing` library.  I guess they could coexist on `expo-in-app-purchases` 9 but not later than that.  Thankfully removing that library (which I thought I already did 🙄 ) seems to have fixed my problems!

**Comment by pckz** [comment]
@acb so you previously did had installed 'react-native-billing' and also expo-in-app-purchases? Because now Playstore doesn't accept under billing v3, I have the following:

    "expo": "^40.0.0",
    "expo-in-app-purchases": "~9.1.0",

but I don't have react-native-billing version, when I create an APK, in the merge of Manifest is automatically added android billing. version 2..

I forced to use the version 3, without update my package.json, but doesn't work in the APK.

So now I upgraded to SDK 41, but I don't find information on which version of expo-in-app.purchases use to pass the billing v3 version of android. Do you have any advice to my situation? thanks @acb !!
