### ISSUE TITLE
expo-av error: no known instance method for selector 'hasGrantedPermission:'

### ISSUE THREAD

**Issue by StevenHarlow** [expo/expo#6604]
I'm not sure if this is what caused it but I noticed this bug after upgrading my `react-native-unimodules` to 0.7.0:

```
node_modules/expo-av/ios/EXAV/EXAV.m:754:91: error: no known instance method for selector 'hasGrantedPermission:'
  if (![[_moduleRegistry getModuleImplementingProtocol:@protocol(UMPermissionsInterface)] hasGrantedPermission:@"audioRecording"]) {

```
I'm on a bare workflow using React Native 0.61.5, and expo-av 7.0.1

### Environment

```
  Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.9.0 => 16.9.0
      react-native: 0.61.5 => 0.61.5
      react-navigation: ^4.0.9 => 4.0.9
    npmGlobalPackages:
      expo-cli: 3.2.3
```

Target: ios

### Steps to Reproduce

- cleaned directory with react-native-clean-project
- pod install in ios directory
- ran `xcodebuild -workspace ios/project_name.xcworkspace -scheme project_name -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build`

### Expected Behavior

App builds

### Actual Behavior

```
node_modules/expo-av/ios/EXAV/EXAV.m:754:91: error: no known instance method for selector 'hasGrantedPermission:'
  if (![[_moduleRegistry getModuleImplementingProtocol:@protocol(UMPermissionsInterface)] hasGrantedPermission:@"audioRecording"]) {

```

**Comment by StevenHarlow** [comment]
I do notice that `react-native-unimodules` now uses `"expo-permissions": "~8.0.0",`, which seems relevant

**Comment by StevenHarlow** [comment]
I'm going to close this. I bumped all my expo packages up to their most current versions in and it solved the issue.
