### ISSUE TITLE
Use of undeclared identifier 'Promise' with RCT_NEW_ARCH_ENABLED

### ISSUE THREAD

**Issue by fbotalla** [expo/expo#18063]
### Summary

When I spin up a new react-native 0.69.1 project, I add Expo and the iOS build breaks with error
`Use of undeclared identifier 'Promise'` in the EXJSIUtils.h file

<img width="717" alt="Screen Shot 2022-06-30 at 2 14 20 PM" src="https://user-images.githubusercontent.com/56210704/176799514-c9128f63-5f9e-4a9e-97bc-48961c778817.png">

I haven't had the time to investigate the cause of the error, but I will asap. Just wanted to make the expo team aware of this in case it's happening to more people.

 

### What platform(s) does this occur on?

iOS

### SDK Version

45

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.8.0 - /usr/local/bin/npm
      Watchman: 20220331.150235.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.6 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.1 => 0.69.1 
    npmGlobalPackages:
      expo-cli: 5.4.12
    Expo Workflow: bare

### Reproducible demo

Steps I took that resulted in compiling error on the iOS end.

1- Spin up a new bare react native project
https://reactnative.dev/docs/environment-setup
`npx react-native init test --template react-native-template-typescript`

2- Upgrade the version of react-native. (in the boilerplate it's 0.69.0, but we want 0.69.1)
https://reactnative.dev/docs/upgrading
`npx react-native upgrade`

3- Install expo using the command line (I also tried to do a manual installation) 
https://docs.expo.dev/bare/installing-expo-modules/
`npx install-expo-modules@latest`

4 - The above command installs the pods already on iOS, but if you want to enable new arch use (you don't have to do this step in order to get that error, I tested with both new arch enabled and not) within the iOS folder:
`RCT_NEW_ARCH_ENABLED=1 pod install`

5 - run the iOS project 
`yarn run ios` or via Xcode

End result is the above pic.

**Comment by brentvatne** [comment]
we don't officially support the new architecture yet, but we plan to soon.

**Comment by fbotalla** [comment]
Thank you @brentvatne. Just to better understand, expo 45 and react native 0.69 ( with new arch NOT enabled) are still not compatible for the time being? I am getting the same result with the new arch enable and with new arch NOT enabled.

**Comment by brentvatne** [comment]
@fbotalla - it's not currently compatible, but I believe any incompatibility should be fixed in react-native@0.69.1, @Kudo has been working on this and you can see the commits in react-native that he cherry-picked in https://github.com/expo/expo/pull/18006 in order to get 0.69 landed on our main branch in this repo

**Comment by bfischer1121** [comment]
@brentvatne I'm in the process of upgrading to 0.69.1 and ran into this error. Is the recommended approach to upgrade to 0.69.0? Is that compatible?

**Comment by bfischer1121** [comment]
FWIW tried resolving expo-modules-core to 0.10.0 to get the above changes, and RN 0.69.1 ran into nearly the same error (Promise class not present, but under a new namespace). Also downgraded to RN 0.69.0 and applied the RN patch file in @Kudo 's PR, and ran into a different error. Just going to avoid upgrading to 0.69.x for now, expo doesn't seem ready yet.

**Comment by Kudo** [comment]
hi there! we are working on react-native 0.69 support in expo sdk 46 which would likely for beta before the end of this month.

there're a couple prs to address 0.69 support and i would recommend to wait for sdk 46. if you want to deal with the `Use of undeclared identifier 'Promise'` error, as far as i can tell, please add [`#import <ReactCommon/TurboModuleUtils.h>;` to EXJSIUtils.h](https://github.com/expo/expo/blob/9ea99d9acdb89ea3a1cef10f6600d2774940f4cf/packages/expo-modules-core/ios/JSI/EXJSIUtils.h#L9)

**Comment by rafaelmaeuer** [comment]
> FWIW tried resolving expo-modules-core to 0.10.0 to get the above changes, and RN 0.69.1 ran into nearly the same error (Promise class not present, but under a new namespace). Also downgraded to RN 0.69.0 and applied the RN patch file in @Kudo 's PR, and ran into a different error. Just going to avoid upgrading to 0.69.x for now, expo doesn't seem ready yet.

I tried some similar steps and also reverted back to RN 0.68.2, I agree expo is not ready for 0.69.x yet...

**Comment by MainAdc95** [comment]
I still have a problem

![Screen Shot 2022-07-17 at 5 06 07 PM](https://user-images.githubusercontent.com/72463475/179399786-3f4771b8-ee57-4218-bd67-548701c7117b.png)

@Kudo didn't work for me

**Comment by atabariscanalp** [comment]
I'm also getting the same error still

**Comment by Kudo** [comment]
sdk 46 is available, please try to upgrade and it should work: https://blog.expo.dev/expo-sdk-46-beta-is-now-available-9dfee4040aa7

**Comment by oliviercperrier** [comment]
@Kudo still getting this issue even with the sdk 46
