### ISSUE TITLE
[jest-expo] TypeError: (0 , _jestUtil(...).tryRealpath) is not a function after upgrade to 38.0.2 

### ISSUE THREAD

**Issue by ghasemikasra39** [expo/expo#10049]
### Summary of Issue 
I should mention that our project is an expo ejected project. 
After upgrading `jest-expo` to version `38.0.2` I get this error when running my test:
```
yarn run v1.22.4
$ jest __tests__/App1.test.tsx
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
 FAIL  __tests__/App1.test.tsx
  ● Test suite failed to run

    TypeError: (0 , _jestUtil(...).tryRealpath) is not a function

      at ScriptTransformer.transformSource (node_modules/jest-runtime/node_modules/@jest/transform/build/ScriptTransformer.js:424:50)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.181s
Ran all test suites matching /__tests__\/App1.test.tsx/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.19.2
```

### Reproducible Demo
```javascript
// jest.config.js
const { defaults } = require('jest-config');

const expoPreset = require('jest-expo/jest-preset');
const jestPreset = require('@testing-library/react-native/jest-preset');

module.exports = Object.assign(expoPreset, jestPreset, {
  preset: 'jest-expo',
  testRegex: '(/__tests__/.*(\\.|/)(test|spec))\\.[jt]sx?$',
  setupFiles: [
    ...expoPreset.setupFiles,
    ...jestPreset.setupFiles,
    '<rootDir>setup-tests.js',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base|unimodules-permissions-interface|@mollie/.*)',
  ],
  collectCoverage: false,
  collectCoverageFrom: ['App.tsx', 'src/**/*.{tsx}', '!node_modules/**/*'],
  moduleFileExtensions: ['ts', 'tsx', ...defaults.moduleFileExtensions],
  modulePathIgnorePatterns: ['.yarn_cache'],
  setupFilesAfterEnv: ['./__tests__/bootstrapTests.ts'],
});

```

```javascript
// setup-tests.js
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

```

```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "jest": "^26.4.2",
    "jest-enzyme": "^7.1.2",
    "jest-expo": "^38.0.2",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.4",
```

### Expected Behavior vs Actual Behavior
The test should run without error, like in version `36.0.0`

**Comment by byCedric** [comment]
Hi @ghasemikasra39, thanks for the report. Unfortunately, this looks like a Jest specific and not necessarily an Expo issue. If you can create a [small repro](https://stackoverflow.com/help/minimal-reproducible-example) where this happens, we can investigate this. But without, we can't do much about it (similar to https://github.com/facebook/jest/issues/10475)

If you want to use enzyme, I would also recommend taking a look at [`jest-expo-enzyme`](https://github.com/expo/expo/tree/master/packages/jest-expo-enzyme). I doubt it will solve the issue because it looks like it's Jest-specific. But without the repro, I can't be sure of that.

Hope this helps!

**Comment by SimenB** [comment]
Happy to fix if a reproduction is provided 🙂

**Comment by ghasemikasra39** [comment]
Dear @byCedric 
Issue fixed by doing the following, it's very strange, but it worked:
Just delete the node_modules and run yarn install/npm install and the error is gone

**Comment by byCedric** [comment]
Thanks @SimenB! ❤️ I'm also happy to take a look at it, to confirm if it's an expo or jest issue (and where it originates from). But it looks like @ghasemikasra39 might have fixed this by reinstalling `node_modules`, am I correct with that? If so, happy you solved it and I'll close this issue.

**Comment by GhadaAJIMI** [comment]
btw when I installed an old version '22.2.2' it worked just fine
