### PR TITLE
[dev-launcher] Add support for RN 66

### LINKED ISSUE #14854: [RN0.66] [android] build fails due to missing handleReloadJS() implementation
### Summary

Android debug builds on React Native 0.66 fail with the following error:

> /build/node_modules/expo-dev-launcher/android/src/react-native-65/expo/modules/devlauncher/rncompatibility/DevLauncherDevSupportManager.kt: (17, 1): Class 'DevLauncherDevSupportManager' is not abstract and does not implement abstract base class member public abstract fun handleReloadJS(): Unit defined in com.facebook.react.devsupport.DevSupportManagerBase

### Why?

The following method implementations are missing from `expo-dev-launcher`'s `DevLauncherDevSupportManager`:

- handleReloadJS https://github.com/facebook/react-native/commit/7c6eb1fecb1e3a74e382aba5dd2aba38b4cf3ec4
- loadSplitBundleFromServer https://github.com/facebook/react-native/commit/30340890dc339d67e0f72c7fd15c9f575329ba7e
- getUniqueTag https://github.com/facebook/react-native/commit/6676d01033ee0a75e1be49068c4d31aa31b28953

Until RN 0.66, `DevSupportManagerBase` provided an implementation for `handleReloadJS` and `loadSplitBundleFromServer`. These were moved to `BridgeDevSupportManager`.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Package versions

react-native: 0.66.1
expo: 43.0.0
expo-dev-client: 0.6.3

### Environment

```
Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.12.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.1 - /usr/local/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 24, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 31.0.0, 31.0.0, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.66.1 => 0.66.1 
      react-native-web: ^0.17.5 => 0.17.5 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

- expo init (select bare workflow)
- expo add expo-dev-client
- yarn add react-native^0.66.1
- expo prebuild
- expo run:android

### Stacktrace (if a crash is involved)

_No response_

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Closes ENG-2297.
Fixes https://github.com/expo/expo/issues/14854.
Adds support for RN 66.

# Test Plan

- project with RN 66 without unimodules 
- project with RN 66 with unimodules 
- bare-expo

### CODE REVIEW

**Review by esamelson — APPROVED** [review]
This looks fine to me, but is there a reason why DevLauncherDevSupportManager can't just subclass BridgeDevSupportManager directly instead of copying all its functionality? 🤔 (I know it's only defined in RN 66+ but this file should only be compiled in that same case, right?) Asking because this just looks like even more maintenance work down the line when something inevitably changes in BridgeDevSupportManager.

**Comment by lukmccall** [comment]
@esamelson `BridgeDevSupportManager` is marked as a final class, so we can't subclass it, unfortunately.

**Review by esamelson — APPROVED** [review]
Ah ☹️ that's unfortunate. OK, this looks good then

**Comment by Yonom** [comment]
Awesome!
