### ISSUE TITLE
[expo-image-manipulator] doesn't build on Xcode 13.3.1

### ISSUE THREAD

**Issue by ahdam** [expo/expo#17888]
### Summary

Build fails because of this library Xcode 13.3.1

I get a lot of errors like this:
```
ImageManipulations.swift:51:11: 'NoImageInContextException' is not convertible to 'Error'
ImageManipulations.swift:63:11: 'ImageNotFoundException' is not convertible to 'Error'
ImageManipulations.swift:111:11: 'ImageInvalidCropException' is not convertible to 'Error'
....
ImageManipulatorExceptions.swift:25:16: Property does not override any property from its superclass
...
ImageManipulatorExceptions.swift:24:50: Cannot find type 'Exception' in scope
...
ImageManipulatorModule.swift:48:34: 'CorruptedImageDataException' is not convertible to 'Error'
...
ImageManipulatorModule.swift:69:68: Argument passed to call that takes no arguments
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
      Yarn: 1.22.18 - ~/apps/tp/mobile-app/node_modules/.bin/yarn
      npm: 6.14.8 - ~/apps/tp/mobile-app/node_modules/.bin/npm
      Watchman: 2022.01.10.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 26, 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 30.0.2, 30.0.3, 32.0.0
        System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
    npmGlobalPackages:
      expo-cli: 5.4.9
    Expo Workflow: bare

### Reproducible demo

```
> react-native init expoTest --version 0.67.4
> npx install-expo-modules@44.0.6
> expo install expo-constants
> expo install expo-camera
> expo install expo-image-manipulator
```

Try to run build on iOS device.

**Comment by brentvatne** [comment]
> npx install-expo-modules@44.0.6

the latest version of `install-expo-modules` is 0.3.4, so i'm not sure what npx will do in this case. https://www.npmjs.com/package/install-expo-modules

if you want to install a specific version of expo modules, use `-s` to specify the sdk version `npx install-expo-modules@latest -s 44.0.0` 

using your "reproducible demo"

```
╰─$ npx install-expo-modules@44.0.6
npm ERR! code ETARGET
npm ERR! notarget No matching version found for install-expo-modules@44.0.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brentvatne/.npm/_logs/2022-06-16T17_26_54_389Z-debug.log
╭─[10:26:54] ~/code
```

after removing the `@44.0.6` from the command, i followed the steps you provided and the project built as expected on xcode 13.3.1. please in the future follow the issue template and actually provide a clonable example - i expect you did not actually run the instructions you provided and it is not a good use of our time to do that for you.

**Comment by ahdam** [comment]
I'm sorry I didn't provide a "reproducible demo", but the issue still stands.

The repo you provided does not solve the issue.
You are using a different version of expo.

```
"dependencies": {
    "expo": "^45.0.0",
    "expo-camera": "~12.2.0",
    "expo-constants": "~13.1.1",
    "expo-image-manipulator": "~10.3.1",
    "react": "17.0.2",
    "react-native": "0.67.4"
  }
```

This combination of expo (^45.0.0) + RN (0.67.4) does NOT build on Android, as explained in [this issue](https://github.com/expo/expo/issues/17862).

So, I switched to expo (^44.0.0) + RN (0.67.4). This builds on Android and iOS.
But with this version combination of expo and RN, if I add "expo-image-manipulator", the build fails on iOS with the errors mentioned above.

I'm sorry for not reading the documentation and wasting your time with an unreproducible demo.
I've been trying to install these modules for a week now, and I'm not able to find a combination of versions that work.

Any help on this matter is highly appreciated.
Thanks!

**Comment by brentvatne** [comment]
our support policy for expo sdk modules is outlined here: https://docs.expo.dev/versions/latest/#support-for-other-react-native-versions

> Packages in the Expo SDK are intended to support the target React Native version for that SDK. Typically, they will not support older versions of React Native, but they may. When a new version of React Native is released, the latest versions of the Expo SDK packages are typically updated to support it; however, this may take weeks or more, depending on the extent of the changes in the release.

we never targeted react-native 0.67.4 and can't guarantee support for it. if you were to update to 0.68.2 you would be able to use expo@45. it is likely going to be much faster for you to update your app to 0.68.2 than it would be for us to find the source of this and publish an update.
