### ISSUE TITLE
dynamic import() returns a bare thenable without .catch/.finally on native — breaks libraries chaining .catch() on import()

### ISSUE THREAD

**Issue by 1kuko3** [expo/expo#47591]
### Minimal reproducible example

https://github.com/1kuko3/expo57-import-thenable-repro

### Steps to reproduce

Created with `npx create-expo-app@latest --template blank` (SDK 57); the only change is in `App.js`.

1. `npm install`
2. `npx expo start --ios` (also reproduces on Android; occurs in Expo Go and in development builds, and in **production** bundles as well)
3. `App.js` runs:

```js
const p = import('expo-status-bar');
console.log(`then: ${typeof p.then}, catch: ${typeof p.catch}, finally: ${typeof p.finally}`);
console.log('is real Promise:', p instanceof Promise);
p.catch(() => {}); // <-- throws
```

**Expected** (spec behavior — `import()` evaluates to a Promise — and actual SDK 56 behavior):

```
then: function, catch: function, finally: function
is real Promise: true
```

**Actual on SDK 57:**

```
LOG    import() returned — then: function, catch: undefined, finally: undefined
LOG    is real Promise: false
ERROR  import().catch() threw: [TypeError: undefined is not a function]
```

### Cause

Since SDK 57, `import()` on native resolves through `expo/src/async-require/asyncRequireModule.ts` (set as `asyncRequireModulePath` by `@expo/metro-config`). Its `asyncRequire()` returns a bare thenable in **all** cases:

```js
return {
  _result: ret,
  then(resolve, reject) {
    return Promise.resolve(ret).then(resolve, reject);
  },
};
```

— no `.catch()`, no `.finally()`. This was introduced in #46539 (the `_result` rehydration thenable). On SDK 56, Metro's stock `asyncRequire` is an `async function`, i.e. a real Promise.

`await import(...)` still works (await accepts thenables), so only code chaining `.catch()`/`.finally()` directly on `import()` breaks — which makes the failures silent and hard to trace.

### Real-world impact

msw's ESM build (`msw/lib/core/utils/internal/parseGraphQLRequest.mjs`) does:

```js
const { parse } = await import("graphql").catch((error) => { ... });
```

On SDK 57 this throws `TypeError: undefined is not a function` inside msw's request matching, so the `graphql.operation()` handler never matches and all GraphQL requests silently pass through to the real backend — our e2e suite's mocking broke with no visible error after upgrading from SDK 56. Any other library chaining `.catch()`/`.finally()` on `import()` will break the same way.

### Suggested fix

Give the returned thenable the full Promise surface, e.g.:

```js
return {
  _result: ret,
  then(resolve, reject) {
    return Promise.resolve(ret).then(resolve, reject);
  },
  catch(reject) {
    return this.then(undefined, reject);
  },
  finally(onFinally) {
    return Promise.resolve(ret).finally(onFinally);
  },
};
```

(or keep `_result` on a real `Promise.resolve(ret)` object).

### Environment

```
expo-env-info 2.1.0 environment info:
  System:
    OS: macOS 26.5.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.22.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /Users/jakubhanko/.local/share/mise/installs/yarn/1.22.22/bin/yarn
    npm: 10.9.4 - /opt/homebrew/bin/npm
  Managers:
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 25.5, iOS 26.5, macOS 26.5, tvOS 26.5, visionOS 26.5, watchOS 26.5
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 26.6/17F113 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~57.0.4 => 57.0.4
    react: 19.2.3 => 19.2.3
    react-native: 0.86.0 => 0.86.0
  Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
Running 20 checks on your project...
20/20 checks passed. No issues detected!
```

**Comment by 1kuko3** [comment]
Some follow-up analysis on why this was introduced and why fixing it shouldn't conflict with the goals of #46539:

#46539 fixes a web FOUC by letting `React.lazy` bail out of Suspense when a preloaded route chunk is available synchronously. That required two things:

1. `asyncRequire` can no longer be an `async function` (that always wraps the return value in a new Promise), and
2. the returned value must expose the synchronous result (`_result`) so callers can detect "module already loaded".

Neither of those requires dropping `.catch`/`.finally`. As far as I can tell, the synchronous bailout doesn't even depend on the `then` implementation of *this* object — `expo/src/async-require/asyncRequireModule.ts`'s `then` defers through `Promise.resolve(ret).then(...)` (a microtask) anyway; the synchronous resolution that `React.lazy` needs is implemented caller-side in `expo-router`'s `useScreens.tsx`, which builds its own PromiseLike and only reads `_result`/the raw value. Only the `_result` property is load-bearing on the `expo` side.

So an alternative fix that keeps #46539's behavior fully intact and restores the `import()` contract completely would be to return a **real Promise with `_result` attached**:

```js
function asyncRequire(moduleID, paths, moduleName) {
  const ret = asyncRequireImpl(moduleID, paths, moduleName);
  const promise = ret instanceof Promise ? ret : Promise.resolve(ret);
  promise._result = ret;
  return promise;
}
```

- `.then()`, `.catch()`, `.finally()`, and `p instanceof Promise` all behave per spec.
- `_result` remains synchronously readable for the router's lazy bailout.
- It survives accidental re-wrapping better than the current object: `Promise.resolve(realPromise)` returns the *same instance*, preserving `_result`, whereas `Promise.resolve(bareThenable)` returns a new Promise and loses it.

If mutating a Promise instance feels off, completing the existing thenable (adding `catch`/`finally` as in the issue description) also fixes the practical breakage — it just leaves `instanceof Promise` false, which is a smaller residual deviation.

Happy to send a PR for either variant if that helps.

**Comment by erickreutz** [comment]
Hi! Any news with this?

**Comment by kitten** [comment]
We didn't forget about this. Sorry for the lack of updates. I've got it filed as a task internally, but will also have to check whether there's a more longterm-durable approach and just scrap the previous change. It's queued up behind some other tasks, but I'll try to come back to this before the end of the week
