### ISSUE TITLE
Property 'status' does not exist on type 'NotificationPermissionsStatus'

### ISSUE THREAD

**Issue by johannb75** [expo/expo#13743]
### Summary

I've recently tried to upgrade my project to version `42` of the `Expo SDK` using command `expo upgrade`
When using version 40 (I skipped v41), I was trying expo push notifications, and it was working perfectly.
In the doc, the function [`registerForPushNotificationsAsync()`](https://docs.expo.io/versions/v42.0.0/sdk/notifications/#api), gets the property `status` from `Notifications.getPermissionsAsync()` and  `Notifications.requestPermissionsAsync()`.

Since I upgraded to v42, typescript throws this error: 
```
Property 'status' does not exist on type 'NotificationPermissionsStatus'
```

I've basically copy/pasted the code in the doc and haven't changed anything.

### Link to the related docs page

https://docs.expo.io/versions/v42.0.0/sdk/notifications/

**Comment by cruzach** [comment]
Can you provide a repro for this with your package versions? NotificationPermissionsStatus [extends PermissionResponse](https://github.com/expo/expo/blob/master/packages/expo-notifications/src/NotificationPermissions.types.ts#L23), which [has the `status` property](https://github.com/expo/expo/blob/5883a00fbb3a05d54e9a9daf0283431e400cd199/packages/expo-modules-core/src/PermissionsInterface.ts#L10)

**Comment by johannb75** [comment]
I'm sorry for the stupid error, I just restarted my computer and everything worked like a charm. 
Don't know what happened 🤷‍♂️
