### ISSUE TITLE
[expo-age-range] iOS build fails: 'AgeRangeService' has no member 'showSignificantUpdateAcknowledgment' when Xcode SDK < iOS 26.4

### ISSUE THREAD

**Issue by CavalcanteLeo** [expo/expo#46365]
### Summary

`expo-age-range@56.0.5` calls iOS 26.4-only APIs (`AgeRangeService.showSignificantUpdateAcknowledgment(in:updateDescription:)` and `AgeRangeService.requiredRegulatoryFeatures`) without a compile-time SDK guard. The runtime `#available(iOS 26.4, *)` check does not protect against the symbol being absent from the SDK at compile time. As a result, **any toolchain whose iOS SDK is below 26.4 fails to compile the `ExpoAgeRange` Swift target**.

This affects users building on **EAS Build's `image: "latest"`**, which still ships with iOS SDK 26.2 (`-sdk iPhoneOS26.2.sdk`, `-target-sdk-version 26.2`).

### Upstream cause

Introduced in PR #43519 — `[age-range] add new ios methods` (merged 2026-05-26), shipped in `expo-age-range@56.0.5`. The PR description correctly notes these methods are "iOS 26.4+ only", but the implementation only guards them at runtime.

### Failing call sites

[`expo-age-range/ios/AgeRangeModule.swift`](https://github.com/expo/expo/blob/main/packages/expo-age-range/ios/AgeRangeModule.swift):

- Line 64: `try await AgeRangeService.shared.showSignificantUpdateAcknowledgment(in: windowScene, updateDescription: updateDescription)`
- Line 75: `let features = try await AgeRangeService.shared.requiredRegulatoryFeatures`

The canary `56.0.6-canary-20260526-6cd5e37` still contains these unguarded calls (verified by inspecting the published tarball).

### Build error (from EAS Build, production iOS, Expo SDK 56)

```
/Users/expo/workingdir/build/node_modules/expo-age-range/ios/AgeRangeModule.swift:64:42: error: value of type 'AgeRangeService' has no member 'showSignificantUpdateAcknowledgment'
        try await AgeRangeService.shared.showSignificantUpdateAcknowledgment(in: windowScene, updateDescription: updateDescription)
                  ~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

EAS build ID: `ade63641-7c75-470c-8cf8-2d70c0531f30` (failed at the `ExpoAgeRange` `CompileSwift normal arm64` step).

### Steps to reproduce

1. Any Expo SDK 56 app with `expo-age-range@56.0.5` installed.
2. Build for iOS using a toolchain whose iOS SDK is below 26.4 — e.g.:
   - `eas build --platform ios --profile production` with `image: "latest"` (iOS SDK 26.2 at time of writing), or
   - locally with any Xcode < 26.4.
3. The `ExpoAgeRange` target fails to compile with the error above.

### Expected behavior

The package compiles cleanly against any iOS SDK supported by Expo SDK 56 (currently iOS 26.x baseline). The iOS 26.4-only calls should be unreachable at compile time when building against an older SDK.

### Suggested fix

Guard the affected call sites with a compile-time check, not just a runtime one. For example:

```swift
AsyncFunction("showSignificantUpdateAcknowledgmentAsync") { (updateDescription: String) in
  #if canImport(DeclaredAgeRange) && compiler(>=6.x)  // or a more targeted SDK check
  if #available(iOS 26.4, *) {
    // ... existing call
  }
  #endif
}
```

Or use a Swift availability declaration on a helper type wrapping the call. Either way, the symbol reference must be unreachable to the compiler when the SDK doesn't contain it.

### Workaround

Pin `expo-age-range` to `56.0.4` in both `dependencies` and `overrides` (since transitive resolution may upgrade it):

```jsonc
{
  "overrides": {
    "expo-age-range": "56.0.4"
  },
  "dependencies": {
    "expo-age-range": "56.0.4"
  }
}
```

This removes the unguarded calls until either:
1. The package ships a compile-time guard, or
2. EAS Build's `latest` image upgrades to a toolchain with iOS SDK 26.4.

### Environment

```
expo-env-info 2.0.14 environment info:
    System:
      OS: macOS 26.5
    Binaries:
      Node: 24.16.0
      Yarn: 4.9.0
      npm: 11.13.0
      Watchman: 2026.05.25.00
    Managers:
      CocoaPods: 1.16.2
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.5, iOS 26.5, macOS 26.5, tvOS 26.5, visionOS 26.5, watchOS 26.5
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2512.13840223
      Xcode: 26.5/17F42
    npmPackages:
      babel-preset-expo: ~56.0.13 => 56.0.13
      expo: ^56.0.5 => 56.0.5
      expo-router: ~56.2.7 => 56.2.7
      expo-updates: ~56.0.17 => 56.0.17
      react: 19.2.3 => 19.2.3
      react-native: 0.85.3 => 0.85.3
    Expo Workflow: bare
```

Note: the local machine above has Xcode 26.5 / iOS SDK 26.5, so the bug **does not reproduce locally**. It reproduces on **EAS Build's `image: "latest"`**, which is still on iOS SDK 26.2 as of build `ade63641` (2026-05-28).

### Minimal reproducible example

This bug lives entirely inside the published `expo-age-range@56.0.5` source and is triggered by the toolchain SDK version, not by any user code. Any SDK 56 app with the package installed and a pre-26.4 iOS SDK reproduces it; the offending lines are linked above. Happy to provide a stripped-down repo if maintainers prefer.

### Expo Doctor Diagnostics

Not run on a stripped repro; the bug is independent of project state (it's a fixed compile error in `node_modules/expo-age-range/ios/AgeRangeModule.swift`).

c/c @vonovak

**Comment by Kudo** [comment]
hi there!

according to the [changelog](https://expo.dev/changelog/sdk-56#upgrading-your-app), xcode 26.4 is required for sdk 56. i think you should try to use xcode 26.4 at least

> Upgrade Xcode if needed: Xcode 26.4 is required to compile a native iOS project. For EAS Build and Workflows, profiles without any specified image will default to Xcode 26.4.

**Comment by CavalcanteLeo** [comment]
On EAS, I'm using latest, is EAS CI ready for this?

```json
    "production": {
      "extends": "base",
      "autoIncrement": true,
      "env": {
        "APP_VARIANT": "production",
        "EAS_GRADLE_CACHE": "1"
      },
      "ios": {
        "image": "latest"
      },
      "android": {
        "image": "latest",
        "resourceClass": "large"
      },
      "channel": "production"
    },
````

@Kudo

**Comment by Kudo** [comment]
@CavalcanteLeo please use `sdk-56` instead. the latest is still pointed to sdk-55.
https://docs.expo.dev/build-reference/infrastructure/#macos-sequoia-156-xcode-262-latest-sdk-55

will share this to the team so they may alias latest to sdk-56

**Comment by zoontek** [comment]
`latest` now aliases `sdk-56`, I'm closing this
