### ISSUE TITLE
Facebook login not working with SDK35 after SDK36 release

### ISSUE THREAD

**Issue by SeanRenet** [expo/expo#6500]
## Description

expo-cli 3.11.1 nerfed facebook login.
A hour ago, before upgrading expo-cli this code used to  work perfectly.

			
## Expected Behavior

An hour ago before updating expo-cli this code worked perfectly

`const { type, token } = await Facebook.logInWithReadPermissionsAsync('< my actual facebook project id >', { permissions: ['public_profile', 'email'] }).catch(function(error) {
				// Handle Errors here.
				
        let errorCode = error.code;
        let errorMessage = error.message;
        // The email of the user's account used.
       let email = error.email;
       // The firebase.auth.AuthCredential type that was used.
       let credential = error.credential;
      console.log(errorCode, ' ', errorMessage, ' ', email, ' ', credential, ' ',);

});`	

I also tried Facebook.initializeAsync  but that did not work either

## Observed Behavior
Error from facebook is 
`E_FBLOGIN_APP_ID   Tried to perform Facebook login, but no Facebook app id was provided. Specify Facebook app id in Info.plist. `

error from expo is 
```
undefined is not an object (evaluating '_ref.type')
* src/actions/user.js:82:11 in _callee3$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- ... 13 more stack frames from framework internals
```

If I run Facebook.initializeAsync . I get 

`Facebook.initializeAsync is not a function`

## Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 13.2.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.11.1

 "expo-facebook": "~7.0.1",  does not work on ^8.0.0 either

Emulator is iPhone 11 Pro Max 13.3
Phone 1  is Pixel 3 Android version 10
Phone 2 is Samsung S8 Android version 9

## Reproducible Demo

I am not sure how to do this...

**Comment by Rakeda** [comment]
Try upgrading your expo from 35.0.0 to 36.0.0 by using 
`expo upgrade`

**Comment by brentvatne** [comment]
> expo-cli 3.11.1 nerfed facebook login.
> A hour ago, before upgrading expo-cli this code used to work perfectly.

expo-cli is not related to any facebook log in functionality. i suspect the problem is due to either 1) a change in your code that you didn't notice that you made or 2) updating the expo client app

> `const { type, token } = await Facebook.logInWithReadPermissionsAsync('< my actual facebook project id >', { permissions: ['public_profile', 'email'] })

are you sure that the project id that you are providing is valid? are you maybe importing it wrong?

> "expo-facebook": "~7.0.1", does not work on ^8.0.0 either

you should always use the version provided when you run `expo install expo-facebook`

> Emulator is iPhone 11 Pro Max 13.3
> Phone 1 is Pixel 3 Android version 10
> Phone 2 is Samsung S8 Android version 9

are you saying this is happening on all of these devices?

> I am not sure how to do this...

https://stackoverflow.com/help/mcve

**Comment by Rakeda** [comment]
@brentvatne I don't want to make another issue because I feel that the error is very direct, but when I try to use Facebook.initializeAsync("myappid") it immediately tells me that "Facebook Login Error: The method or property Facebook.initializeAsync is not available on android, are you sure you've linked all the native dependencies properly?"

Is Facebook.initializeAsync iOS specific?

**Comment by brentvatne** [comment]
thanks @Rakeda!

**Comment by sjchmiela** [comment]
No, `Facebook.initializeAsync` should be used on both platforms, but it is required only on SDK36. I have just run published NCL on SDK36 and confirmed that the function works as expected on Android on latest Expo client.

Are you sure you're: 
- running SDK36 experience
- using `expo-facebook@8.0.0`
- importing Facebook like `import * as Facebook from "expo-facebook";`
?

**Comment by Rakeda** [comment]
> No, `Facebook.initializeAsync` should be used on both platforms, but it is required only on SDK36. I have just run published NCL on SDK36 and confirmed that the function works as expected on Android on latest Expo client.
> 
> Are you sure you're:
> 
> * running SDK36 experience
> * using `expo-facebook@8.0.0`
> * importing Facebook like `import * as Facebook from "expo-facebook";`
>   ?

I have ensured that my expo is the most up-to-date

My package.json

`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/firestore": "^6.2.0",
    "@react-native-firebase/storage": "^6.2.0",
    "expo": "^36.0.0",
    "expo-av": "~8.0.0",
    "expo-camera": "~8.0.0",
    "expo-contacts": "~8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-image-picker": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "firebase": "^7.5.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-fbsdk": "^1.1.1",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "~1.4.0",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-svg": "9.13.3",
    "react-native-svg-charts": "^5.3.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-video": "^5.0.2",
    "react-native-web": "^0.11.7",
    "react-native-webview": "7.4.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.7.5",
    "@babel/runtime": "^7.7.6",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "babel-preset-expo": "^8.0.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.12.0"
  },
  "private": true
}
`

And I am importing it as referenced above and in the docs.

**Comment by sjchmiela** [comment]
May I just run another sanity question: what is your `sdkVersion` in `app.json`? Sorry for asking obvious questions…

**Comment by Rakeda** [comment]
> May I just run another sanity question: what is your `sdkVersion` in `app.json`? Sorry for asking obvious questions…

My sdkVersion is 36.0.0, after uninstalling and force downgrading and updating I managed to get it to work... weird error.

**Comment by SeanRenet** [comment]
> > May I just run another sanity question: what is your `sdkVersion` in `app.json`? Sorry for asking obvious questions…
> 
> My sdkVersion is 36.0.0, after uninstalling and force downgrading and updating I managed to get it to work... weird error.

@Rakeda thank you for that.  

Nerfing app authorization is a pretty big deal.  Why isn't this in neon flashing lights before "here are the candy treats" we put into the upgrade?

**Comment by brentvatne** [comment]
nothing has been "nerfed" here @SeanRenet, something didn't go right when you and @Rakeda upgraded your projects.

**Comment by brentvatne** [comment]
oh if you folks can provide information on what you did to upgrade that'd be helpful

**Comment by SeanRenet** [comment]
> nothing has been "nerfed" here @SeanRenet, something didn't go right when you and @Rakeda upgraded your projects.

@brentvatne 
Umm no.  I upgraded the expo-CLI and all of the sudden Facebook login gave a weird error.  It got NERFED with no explanation that upgrading the CLI required upgrading the SDK otherwise your auth team would spend a day trying to decode that error until someone tripped upon the upgrading the sdk as a solution.

**Comment by SeanRenet** [comment]
@brentvatne I have upgraded the expo-cli many times without having to upgrade the sdk without my project throwing undecipherable errors.

**Comment by brentvatne** [comment]
you seem a little upset. do you want to do a video call and chat about what went wrong?

**Comment by brentvatne** [comment]
oh i see what you're saying now, you didn't *want* to update the sdk, you are saying that it was broken in sdk 35 and you wanted to stay at sdk 35

**Comment by SeanRenet** [comment]
@brentvatne no.  I'm not upset, I just wanted to curtail the "user error" narrative that it sounded like you were about to run with.

No.  Every once in a while you get a green notice that says to update the expo-cli.  Whenever I see it I update the cli.  This time Facebook login stopped working and I got an error "undefined is not an object (evaluating '_ref.type')".  The documentation said to add the init code which gave an error that "Facebook.initializeAsync was not a function"

So the problem is that updating the CLI required updating the SDK and there was no warning or notice of the same.

I explained all of this in my first post.  Was part of that unclear?  I'd like to know so I can better explain next time.

**Comment by SeanRenet** [comment]
@brentvatne that is entirely the wrong heading.  The problem is that when you upgrade to Expo CLI 3.11.1 you MUST also upgrade the SDK to 36

**Comment by brentvatne** [comment]
the CLI is unrelated, there is nothing in Expo CLI related to Facebook

**Comment by brentvatne** [comment]
with respect to the `initializeAsync` issue you encountered - I believe you were reading the SDK36 docs for the Facebook module, because this method did not exist in SDK35: https://docs.expo.io/versions/v35.0.0/sdk/facebook/

**Comment by SeanRenet** [comment]
@brentvatne when the new CLI is installed on a phone or an emulator, this error is thrown.  That is a fact.  That is the only change that was made and the facebook error was thrown.  Read the forums.  Everyone basically got it the same way.  The only way to fix it is to upgrade to SDK 36

**Comment by SeanRenet** [comment]
@brentvatne if there is nothing related to facebook, maybe there is something related to the 13 more stack frames we cannot see.

undefined is not an object (evaluating '_ref.type')
* src/actions/user.js:82:11 in _callee3$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- ... 13 more stack frames from framework internals

**Comment by SeanRenet** [comment]
For my app, Facebook login was the only thing affected by upgrading the CLI.  maybe we will trip upon more...

**Comment by brentvatne** [comment]
CLI = command line interface
app that runs on phone = expo client app

so this is why i'm saying that it's not related to the CLI, it's likely related to unintentional changes to SDK35 caused by adding SDK36 to the expo client app

**Comment by SeanRenet** [comment]
@brentvatne when I upgrade the expo-cli, the next time i ran yarn start it installed a new expo client on the emulators and on the phones.  all of which produced the facebook login error that I posted above

**Comment by SeanRenet** [comment]
I had not upgraded to sdk 36 because there wasn't a notice saying that was necessary.  upgrading the expo-cli was the only change.  So I am not sure where relativity meets newton, but its there somewhere.

**Comment by brentvatne** [comment]
thanks for the info! we'll update this thread soon when we've had time to investigate. apologies for the hassle!

**Comment by SeanRenet** [comment]
@brentvatne you are welcome.  I appreciate all the work you guys put into this community

**Comment by cruzach** [comment]
@SeanRenet thanks for reporting this! @sjchmiela I repro'd this locally in the most recent expo client (2.14.1), with sdk 35, `expo-facebook ~7.0.0`
```
try {
      await Facebook.logInWithReadPermissionsAsync(
        APP_ID
      );
    } catch (e) {
      alert(e);
    }
```

**Comment by yornsocheat** [comment]
I upgraded expo:
 - sdkVersion: 36.0.0
- expo-facebook ~7.0.0

await Facebook.initializeAsync(appId);
        const { type, token, expires, permissions, declinedPermissions } = await Facebook.logInWithReadPermissionsAsync({ permissions: ['public_profile', 'email'] });
        if (type === 'success') {
            // This step is successful
            const credential = f.auth.FacebookAuthProvider.credential(token);
            console.log(credential);
            // This step got error
            auth.signInWithCredential(credential).then((user) => {
                console.log(user);
            }).catch((error) => {
                alert(error);
            });
        }
//Error Unsuccessful debug_token respone from Facebook: {"error": {"message": "(#100) You must provide an app access token or a user access token that is an owner or developer of the app", "type": "OAuthException", "code":100, "fbtrace_id":"Ab_VV...."

Do you know how to solve this error?

**Comment by sjchmiela** [comment]
Thank you for explanations, I have also misunderstood the original issue, I have just reproduced an error on SDK35 with latest Expo client
```
GraphRequest can't be used when Facebook SDK isn't fully initialized
```
On it!

**Comment by SeanRenet** [comment]
Thank you.  How can I better explain issues to help you guys track them
down?

Sean Renet

**Comment by hiberna** [comment]
I'm getting the "Facebook Login Error: Tried to perform Facebook login, but no Facebook app id was provided. Specify Facebook app id in Info.plist." message the moment I try to initiate a Facebook login on my app. The potential difference between this and other people in this thread is that I have not upgraded anything, as far as I know. This just started happening out of the blue.

Interestingly, we do not have an Info.plist file in our app. We have defined our Facebook app in an `env.json` file in the root directory, and up until very recently this was working. It works on the production version of the app -- just not on our local or staging environments.

What information can I provide that might help?

**Comment by SeanRenet** [comment]
@hiberna backup your code then type:
expo upgrade 36.0.0

that fixes it.

**Comment by ilyausorov** [comment]
hey all, a solution for people who don’t want to or aren’t ready to upgrade to SDK 36 yet. Apparently the new Expo client (v2.14.1) is set up to only work with the new SDK 36 Facebook module approach. To still be able to use Facebook Login on SDK 35 projects, you have to delete the client from your phone / simulator and then use the expo client:install:ios command from the cli. This will prompt you to install the correct version of the client for your project (i.e. v2.13.0 for SDK 35). This also requires one of the newer version of the CLI, not sure which, but `run npm install expo-cli -g` if you're unsure if you have the latest version. This allows you to use Facebook Login again on SDK 35. I assume it’s same for earlier versions of Expo as well.

**Comment by SeanRenet** [comment]
@ilyausorov Can you give a step by step description of how to do that so that I'll know how to do it in the future?  I googled like mad to figure out how to downgrade the expo client  and expo-cli and could not figure it out.

To be clear, to cause this error all I did was upgrade expo-cli when I saw the green text telling me to do so.  I was still using sdk 35.  The next time I typed "yarn start", a new client was install on my emulator and phones and I got the error.

**Comment by ilyausorov** [comment]
Delete the client from the simulator by long pressing the Expo client and waiting for the menu to come up that includes Delete App. Then from terminal run the command `expo client:install:ios`. You will receive a prompt that says something like "You're project is still running SDK 35. Do you want to install the Expo client version 2.13.0"? Press Y and enter. It will then install the right client version.

**Comment by SeanRenet** [comment]
@ilyausorov, thank you.

**Comment by ilyausorov** [comment]
@sjchmiela Not sure, we should close this yet. What about iOS? This issue is still present on iOS too when you have a project running SDK 35 and you try to run it on Expo client v2.14 or above.

**Comment by alexander0205** [comment]
Hello I found the solution to this error, the solution is very easy .
1- Delete your folder node_modules of your project

2- In your file `app.json `
 Make sure you had sdk version 36.
` "sdkVersion": "36.0.0",`

3- In your `package.json` Make sure you had this update .
`"expo": "^36.0.0",`
    `"expo-facebook": "~8.0.0",`
    ` "react": "~16.9.0",`
 `   "react-devtools": "^3.6.3",`
  `  "react-dom": "~16.9.0",`
`    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",`
`"devDependencies": {`
`    "babel-preset-expo": "~8.0.0",`
`....`
`  },`
  Remove `"expokit": "^34.0.2"` you can install afther .
4- The correct way for initialize the login.

`await Facebook.initializeAsync(ConfigApp.facebookAsynConfig.appId);`
```
const { type, token} = await Facebook.logInWithReadPermissionsAsync({
            permissions: ['public_profile', 'email']
          }
        );
```
5-` npm install  `or `yarn install `.
npm install work good for me.

Ask any question .

**Comment by lfoliveir4** [comment]
I spent hours trying to solve this problem.
For my solution I did the following:

1 - I updated my application using expo upgrade.
(Upgraded to sdk version 36, previously used 35).

2 - I ran the application again

3 - I updated in my login function the initialization of the facebook SDK. ("Facebook.initializeAsync (" APP_ID "))

4 - Login tested normally and functional.

5 - The script below represents how it is currently:

`    _loginFacebook = (navigation) =>  new Promise(async(resolve,reject) => {
        await Facebook.initializeAsync('APP_ID')
        await Facebook.logInWithReadPermissionsAsync('APP_ID', {
            permissions: ['public_profile','email'],behavior: "native"
        }).then(({type,token,}) =>  {
            if (type == "success") {
                const credential = firebase.auth.FacebookAuthProvider.credential(token);
                firebase.auth().signInWithCredential(credential)
                .then(async({user}) => {
                    const { displayName, email, phoneNumber,photoURL,providerId,uid } = user
                    resolve({ displayName,email,phoneNumber,photoURL,providerId,uid })
                    navigation.navigate("MainDono")   
                }).catch(err => reject(err))
            }else {
                reject({message:"user cancel login facebook"})
            }

        }).catch(({ message }) => reject({message}))
    })`

**Comment by appseugene** [comment]
Is there a solution for this without having to upgrade to sdk 36?
I am running on iOS on a physical device, so not sure how to get the old client app back (it's on the latest now).
After upgrading to sdk36 (which fixes the facebook login issue), I am noticing a lot of slowness and refactoring having to do. Thus, not ready for this yet.

**Comment by DavidAPears** [comment]
Hi, 

Updated to sdk 36, seemed the only way around this (it caused other issues but that's life) - however now I am getting an error message:

```
Property 'token' does not exist on type 'FacebookLoginResult'.
```

Any ideas? This whole issue has been a two-dayer :/ Thanks for the help on this thread! 

```
async function FacebookSignIn() {
  try {
    await Facebook.initializeAsync('<myfacebookAppId>', '<myfacebookAppName>');
    const {
      type,
      token,
    } = await Facebook.logInWithReadPermissionsAsync({
      permissions: [
        'public_profile',
        'read_insights',
        'instagram_basic',
        'instagram_manage_insights',
        'pages_show_list',
      ],
    });
    if (type === 'success') {
      // Get the user's name using Facebook's Graph API
      const response = await fetch(
        `https://graph.facebook.com/me?access_token=${token}`
      );
      Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
    } else {
      // type === 'cancel';
    }
  } catch ({ message }) {
    alert(`Facebook Login Error: ${message}`);
  }
}

export default FacebookSignIn;
```

**Comment by Rakeda** [comment]
> Hi,
> 
> Updated to sdk 36, seemed the only way around this (it caused other issues but that's life) - however now I am getting an error message:
> 
> ```
> Property 'token' does not exist on type 'FacebookLoginResult'.
> ```
> 
> Any ideas? This whole issue has been a two-dayer :/ Thanks for the help on this thread!
> 
> ```
> async function FacebookSignIn() {
>   try {
>     await Facebook.initializeAsync('<myfacebookAppId>', '<myfacebookAppName>');
>     const {
>       type,
>       token,
>     } = await Facebook.logInWithReadPermissionsAsync({
>       permissions: [
>         'public_profile',
>         'read_insights',
>         'instagram_basic',
>         'instagram_manage_insights',
>         'pages_show_list',
>       ],
>     });
>     if (type === 'success') {
>       // Get the user's name using Facebook's Graph API
>       const response = await fetch(
>         `https://graph.facebook.com/me?access_token=${token}`
>       );
>       Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
>     } else {
>       // type === 'cancel';
>     }
>   } catch ({ message }) {
>     alert(`Facebook Login Error: ${message}`);
>   }
> }
> 
> export default FacebookSignIn;
> ```

Make sure that you are using expo-facebook 8.0.0 or above in your package.json

**Comment by appseugene** [comment]
> Hi,
> 
> Updated to sdk 36, seemed the only way around this (it caused other issues but that's life) - however now I am getting an error message:
> 
> ```
> Property 'token' does not exist on type 'FacebookLoginResult'.
> ```
> 
> Any ideas? This whole issue has been a two-dayer :/ Thanks for the help on this thread!
> 
> ```
> async function FacebookSignIn() {
>   try {
>     await Facebook.initializeAsync('<myfacebookAppId>', '<myfacebookAppName>');
>     const {
>       type,
>       token,
>     } = await Facebook.logInWithReadPermissionsAsync({
>       permissions: [
>         'public_profile',
>         'read_insights',
>         'instagram_basic',
>         'instagram_manage_insights',
>         'pages_show_list',
>       ],
>     });
>     if (type === 'success') {
>       // Get the user's name using Facebook's Graph API
>       const response = await fetch(
>         `https://graph.facebook.com/me?access_token=${token}`
>       );
>       Alert.alert('Logged in!', `Hi ${(await response.json()).name}!`);
>     } else {
>       // type === 'cancel';
>     }
>   } catch ({ message }) {
>     alert(`Facebook Login Error: ${message}`);
>   }
> }
> 
> export default FacebookSignIn;
> ```

yes, sdk36 caused tons of issues for me too.
did you find a solution to stay on sdk 35 and have facebook working?

**Comment by DavidAPears** [comment]
I did not sadly. 

Also - Someone mentioned that my error ```Property 'token' does not exist on type 'FacebookLoginResult'.``` may be due to a (very recent)  API change at Facebook :/

**Comment by appseugene** [comment]
Hm i didnt see that token issue on my end yet. My only issue is either using the v7 of expo-facebook lib, where you don't need to call initialize, vs v8 where you have to..

**Comment by DavidAPears** [comment]
I am using   `"expo-facebook": "~8.0.0"`

**Comment by ningacoding** [comment]
Same problem here, upgrade to 36 is not an option for us.

**Comment by brentvatne** [comment]
use `expo install expo-facebook` to get the correct version of expo-facebook for your sdk version

**Comment by ningacoding** [comment]
@brentvatne Stays with the same version sdk35 -> expo-facebook 7.0.0

![image](https://user-images.githubusercontent.com/17342546/77487677-a2457780-6df8-11ea-830c-4d17f22a68ae.png)

**Comment by brentvatne** [comment]
you might want to create a new issue with more information. the comment directly above yours indicate they were using expo-facebook@8.0.0 so i assumed that you were in the same position. this issue has been known to be resolved so it's best to have a new issue that follows the issue template so we have all of the information we need to help you. thanks!

**Comment by appseugene** [comment]
this thread is about expo-facebook@8.0.0 and sdk 36
and @brentvatne , the issue is not solved by doing `expo install expo-facebook`, since it's basically just bringing in 8.0.0

**Comment by brentvatne** [comment]
@appseugene - can you create a new issue with a simple [mcve](https://stackoverflow.com/help/mcve) and explanation of what's happening? it would be very helpful!

**Comment by empregourgente-4** [comment]
Any updates on it? I can't upgrade to SDK 36 since it will cause other things to break (like push notifications on closed apps: https://github.com/expo/expo/issues/3663)

**Comment by ningacoding** [comment]
> @appseugene this thread is about expo-facebook@8.0.0 and sdk 36

Read the title: Facebook login not working with SDK35 after SDK36 release

Check the report: 
![image](https://user-images.githubusercontent.com/17342546/77764359-29197080-7002-11ea-87b4-89dfcc964b8e.png)

This is about SDK35 and expo-facebook 7+

> I can't upgrade to SDK 36 since it will cause other things to break 

upgrade to SDK 36 is not an option for us.

**Comment by DavidAPears** [comment]
Has anyone had any breakthrough with this?

**Comment by BestFromAbove** [comment]
I am having the same issue, did they update their API or something?

**Comment by brentvatne** [comment]
i'm locking this thread because it's been closed for a while and for new commenters we don't have the information that is necessary for us to help you! if you can provide a mcve (https://stackoverflow.com/help/mcve) we'd be happy to look into it, please create a new issue and fill out the issue template accordingly!
