### ISSUE TITLE
expo-modules-jsi 57.0.4 fails to build on Xcode 26.3: ambiguous use of 'abs' in JavaScriptCodable+Date.swift

### ISSUE THREAD

**Issue by skak122** [expo/expo#48983]
### Summary

`expo-modules-jsi@57.0.4` fails to compile under Xcode 26.3 (Apple Swift 6.2.4). The build stops in `JavaScriptCodable+Date.swift` with an ambiguity error on `abs`, which blocks every native iOS build on SDK 57 — `expo run:ios`, dev builds, and EAS local builds alike.

### Error

```
apple/Sources/ExpoModulesJSI/Coding/JavaScriptCodable+Date.swift:53:50: error: type of expression is ambiguous without a type annotation
  guard milliseconds.isFinite, abs(milliseconds) <= maxJavaScriptDateMilliseconds else {
                               ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
** BUILD FAILED **
```

Narrowing it to `let magnitude: Double = abs(milliseconds)` re-reports the same root cause more precisely:

```
JavaScriptCodable+Date.swift:57:27: error: ambiguous use of 'abs'
```

So the ambiguity is in resolving `abs` itself, not in the comparison. This package enables C++ interop, which brings C's `abs` overloads from `<cstdlib>` into scope alongside Swift stdlib's generic `abs<T: SignedNumeric & Comparable>`; for `Double` neither is preferred and resolution fails.

### Reproduction

1. `npx create-expo-app@latest repro` (SDK 57.0.13)
2. `npx expo run:ios` on Xcode 26.3

### Environment

| | |
|---|---|
| expo-modules-jsi | 57.0.4 (latest; also `next`) |
| expo | 57.0.13 |
| react-native | 0.86.2 |
| Xcode | 26.3 (17C529) |
| Swift | 6.2.4 (swiftlang-6.2.4.1.4) |
| macOS | 26.5.1 (25F80) |

### Suggested fix

`Double.magnitude` gives the same value with no overload resolution involved:

```diff
-  guard milliseconds.isFinite, abs(milliseconds) <= maxJavaScriptDateMilliseconds else {
+  guard milliseconds.isFinite,
+    milliseconds.magnitude <= maxJavaScriptDateMilliseconds
+  else {
     throw InvalidDateException()
   }
```

Behavior is unchanged: for a finite `Double`, `magnitude == abs()`, and non-finite values are already excluded by the `isFinite` check on the preceding line. `Float80`/`Double` NaN handling is likewise unaffected since NaN fails `isFinite` first.

I'm carrying this locally as a `pnpm patch` and would rather drop it — happy to open a PR if that's useful.
