### ISSUE TITLE
SplashModule.internalMaybeHideAsync is not a function (it is undefined)

### ISSUE THREAD

**Issue by stesvis** [expo/expo#33316]
### Minimal reproducible example

https://github.com/Krucial92/expo-go-splash-screen-bug

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in a standalone app

### Summary

Everything works in Expo Go when i run the app locally (and I know that Expo Go does not support the new splash screen, alright).

But when I make a build with `eas build` (and APK) and then install the APK on my phone, the app crashes right after the splashscreen (I don't even see the splashscreen hide tho, it crashes when it is supposed to hide).

In Sentry, I see this error, and that's all I could find out so far.

```
TypeError
SplashModule.internalMaybeHideAsync is not a function (it is undefined)

app:///index.android.bundle in _internal_maybeHideAsync
app:///index.android.bundle in asyncGeneratorStep
app:///index.android.bundle in _next
app:///index.android.bundle in Promise$argument_0
app:///index.android.bundle in tryCallTwo
app:///index.android.bundle in doResolve
app:///index.android.bundle in Promise
app:///index.android.bundle in <anonymous>
app:///index.android.bundle in <global>
app:///index.android.bundle in _internal_maybeHideAsync
app:///index.android.bundle in requestAnimationFrame$argument_0
```

![image](https://github.com/user-attachments/assets/c7a12cfd-2799-415c-b0c4-9ff9554a5743)

I just applied the same instructions found in the [documentation](https://docs.expo.dev/versions/latest/sdk/splash-screen/).

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```text
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alanjhughes** [comment]
Hi @stesvis - I've tried your example but I'm not getting the error. Is this a production or debug build of the app? Can you share the command you are using with EAS?

**Comment by alexanderoskin** [comment]
The same issue. Only with Sentry integration when you call `Sentry.init` or `Sentry.wrap`. If you remove Sentry integration (comment `Sentry.init` and `Sentry.wrap`) there is no issue.

Issue appears in all build types.

In ExpoGo:
```
(NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: SplashModule.internalPreventAutoHideAsync is not a function (it is undefined)
(NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: SplashModule.internalMaybeHideAsync is not a function (it is undefined)
```

**Comment by stesvis** [comment]
> @alanjhughes there is no issue with @sentry/react-native v6.3.0. With the expected @sentry/react-native v6.1.0 the issue taking place.

So we should use v6.3.0 even tho `expo-doctor` says it may not be compatible?
```
The following packages should be updated for best compatibility with the installed expo version:
  @sentry/react-native@6.3.0 - expected version: ~6.1.0
```

**Comment by alanjhughes** [comment]
@stesvis you can ignore the expo doctor warning here. We will update the sentry version recommendation cc @brentvatne

**Comment by stesvis** [comment]
> @stesvis you can ignore the expo doctor warning here. We will update the sentry version recommendation cc @brentvatne

Thank you.
I tried to run a new build with `v6.3.0` but it fails with this other error, which I've seen several times recently:

```
Build failed: We've lost connection to the worker.

Two common reasons:
1. Worker ran out of memory.
   Try running your build on a large worker. Learn more at https://docs.expo.dev/build/eas-json/#selecting-resource-class
2. Worker experienced a network issue.
   This is most likely an intermittent problem. Try running the build again.
```

Is it related?

**Comment by alanjhughes** [comment]
@stesvis no, that would be unrelated.

**Comment by stesvis** [comment]
> @stesvis no, that would be unrelated.

It seems to have worked with version `6.3.0`. I also added this to `eas.json`, not sure if it made a difference (i have stored `SENTRY_AUTH_TOKEN` as a secret in expo.dev):
```json
      "env": {
        "SENTRY_AUTH_TOKEN": "@SENTRY_AUTH_TOKEN"
      }
```

There is only one error that `npx expo-doctor@latest` is throwing now:

```
PluginError: Failed to resolve plugin for module "@sentry/react-native/expo" relative to <app-name>
```

**Comment by stesvis** [comment]
@alanjhughes my issue is finally resolved. 
Apparently it had nothing to do with Sentry. At least for me.

I was able to run `adb logcat` and it said

```
Exception: Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
11-29 20:33:50.511 16150 16173 E AndroidRuntime:   • Make sure your project's `package.json` depends on `@react-native-async-storage/async-storage`, even if you only depend on it indirectly through other dependencies. CLI only autolinks native modules found in your `package.json`.
```

So i installed the package, rebuilt, and now the app loads.

**Comment by alanjhughes** [comment]
@stesvis ok, great! There does seem to be an issue with the recommended sentry version so we will bump that too.

**Comment by tonynnabs** [comment]
Still have the same issue with @sentry/react-native@6.3.0 and @sentry/react-native@6.4.0

`SplashModule.internalMaybeHideAsync is not a function (it is undefined)`

**Comment by brentvatne** [comment]
@tonynnabs - can you share a minimal reproducible example? thanks! you might have multiple versions of expo-splash-screen installed, so that's something to look out for `npm why expo-splash-screen`

**Comment by VicFrolov** [comment]
experiencing same issue with bugsnag. If I hide `Bugsnag.start()` I see no error.

**Comment by brentvatne** [comment]
@VicFrolov - https://github.com/expo/expo/issues/33316#issuecomment-2540406942

**Comment by dinakar17** [comment]
What's the solution to this issue? Bumping or downgrading the versions didn't do the trick for me. The error only appears when Sentry.init({}) is used in the _layout.tsx file.

**Comment by Agustin-Perezz** [comment]
Any update ?, I have the same issue.

**Comment by dmoreno85** [comment]
I have the same problem since I started using sentry 6.3.0



 (NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: SplashModule.internalPreventAutoHideAsync is not a function (it is undefined)
 (NOBRIDGE) WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: SplashModule.internalMaybeHideAsync is not a function (it is undefined)

**Comment by vaklinzi** [comment]
Same here:

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/d1a86e82-becb-4941-9df2-c58bf82bfde1" />

**Comment by sdrrv** [comment]
Same here:
<img width="1078" alt="Image" src="https://github.com/user-attachments/assets/23098439-ca79-4854-bb1c-b4c4ff9d0ad2" />

**Comment by bb7hn** [comment]
Same Here:
<img width="570" alt="Image" src="https://github.com/user-attachments/assets/4896ed8c-e04b-4ab1-b00f-13ee49a70c93" />

**Comment by mujibsardar** [comment]
I'm experiencing the same issue where the error messages

```
SplashModule.internalPreventAutoHideAsync is not a function (it is undefined)
SplashModule.internalMaybeHideAsync is not a function (it is undefined)

```

appear in both Expo Go and production builds. I'm using expo-splash-screen v0.29.22, expo 52.0.36 and @sentry/react-native v6.3.0. Despite following the documentation and ensuring there are no duplicate versions of expo-splash-screen, the error persists even when Sentry.init is enabled.

**Comment by CarlosZiegler** [comment]
Same issue :(

**Comment by mujibsardar** [comment]
Hi everyone, I wanted to share that restarting VS Code and upgrading several packages seems to have resolved the SplashModule.internalPreventAutoHideAsync is not a function and SplashModule.internalMaybeHideAsync is not a function errors for me. Simply deleting node_modules and reinstalling dependencies without package updates did not fix the issue.

Here's a diff of my package-lock.json changes. While it's not definitively clear which package fixed it, the addition of react-native-svg: "15.8.0" is a change that stands out as potentially relevant, as it's a native dependency. It's possible there was a missing or conflicting dependency related to react-native-svg in my project.

```
diff --git a/package-lock.json b/package-lock.json
index 2242e6c..e2428f9 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -17,7 +17,7 @@
         "@react-navigation/drawer": "^7.1.1",
         "@reduxjs/toolkit": "^2.5.0",
         "@rneui/themed": "^4.0.0-rc.8",
-        "@sentry/react-native": "6.3.0",
+        "@sentry/react-native": "~6.3.0",
         "@stripe/stripe-react-native": "0.38.6",
         "axios": "1.8.2",
         "dayjs": "^1.11.13",
@@ -35,10 +35,10 @@
         "expo-image-manipulator": "~13.0.6",
         "expo-image-picker": "16.0.6",
         "expo-linking": "~7.0.5",
-        "expo-location": "~18.0.7",
+        "expo-location": "~18.0.8",
         "expo-media-library": "~17.0.5",
         "expo-notifications": "~0.29.13",
-        "expo-router": "~4.0.17",
+        "expo-router": "~4.0.19",
         "expo-sharing": "~13.0.1",
         "expo-splash-screen": "~0.29.22",
         "expo-updates": "~0.27.1",
@@ -53,6 +53,7 @@
         "react-native-reanimated": "~3.16.1",
         "react-native-safe-area-context": "4.12.0",
         "react-native-screens": "~4.4.0",
+        "react-native-svg": "15.8.0",
         "react-native-svg-transformer": "^1.5.0",
         "react-native-uuid": "^2.0.3",
         "react-native-vector-icons": "^10.2.0",
@@ -2778,15 +2779,15 @@
       "license": "MIT"
     },
     "node_modules/@expo/server": {
-      "version": "0.5.2",
-      "resolved": "https://registry.npmjs.org/@expo/server/-/server-0.5.2.tgz",
-      "integrity": "sha512-Uh10gzQM9GUC+RUX8ACdWxrbOJ47uXvs+Kiq8Ho6XMBkRG7AXhWWAgM7XSI0GddqpRLOyHafsIICJqj5YsR5sw==",
+      "version": "0.5.3",
+      "resolved": "https://registry.npmjs.org/@expo/server/-/server-0.5.3.tgz",
+      "integrity": "sha512-WXsWzeBs5v/h0PUfHyNLLz07rwwO5myQ1A5DGYewyyGLmsyl61yVCe8AgAlp1wkiMsqhj2hZqI2u3K10QnCMrQ==",
       "license": "MIT",
       "dependencies": {
         "abort-controller": "^3.0.0",
         "debug": "^4.3.4",
         "source-map-support": "~0.5.21",
-        "undici": "^6.18.2 || ^7.0.0"
+        "undici": "^6.18.2"
       }
     },
     "node_modules/@expo/spawn-async": {
@@ -6500,9 +6501,9 @@
       }
     },
     "node_modules/caniuse-lite": {
-      "version": "1.0.30001703",
-      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001703.tgz",
-      "integrity": "sha512-kRlAGTRWgPsOj7oARC9m1okJEXdL/8fekFVcxA8Hl7GH4r/sN4OJn/i6Flde373T50KS7Y37oFbMwlE8+F42kQ==",
+      "version": "1.0.30001704",
+      "resolved": "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001704.tgz",
+      "integrity": "sha512-+L2IgBbV6gXB4ETf0keSvLr7JUrRVbIaB/lrQ1+z8mRcQiisG5k+lG6O4n6Y5q6f5EuNfaYXKgymucphlEXQew==",
       "funding": [
         {
           "type": "opencollective",
@@ -6998,7 +6999,6 @@
       "resolved": "https://registry.npmjs.org/css-tree/-/css-tree-1.1.3.tgz",
       "integrity": "sha512-tRpdppF7TRazZrjJ6v3stzv93qxRcSsFmW6cX0Zm2NVKpxE1WV1HblnghVv9TreireHkqI/VDEsfolRF1p6y7Q==",
       "license": "MIT",
-      "peer": true,
       "dependencies": {
         "mdn-data": "2.0.14",
         "source-map": "^0.6.1"
@@ -7012,7 +7012,6 @@
       "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
       "integrity": "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
       "license": "BSD-3-Clause",
-      "peer": true,
       "engines": {
         "node": ">=0.10.0"
       }
@@ -7388,9 +7387,9 @@
       "license": "MIT"
     },
     "node_modules/electron-to-chromium": {
-      "version": "1.5.114",
-      "resolved": "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.114.tgz",
-      "integrity": "sha512-DFptFef3iktoKlFQK/afbo274/XNWD00Am0xa7M8FZUepHlHT8PEuiNBoRfFHbH1okqN58AlhbJ4QTkcnXorjA==",
+      "version": "1.5.118",
+      "resolved": "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.118.tgz",
+      "integrity": "sha512-yNDUus0iultYyVoEFLnQeei7LOQkL8wg8GQpkPCRrOlJXlcCwa6eGKZkxQ9ciHsqZyYbj8Jd94X1CTPzGm+uIA==",
       "license": "ISC"
     },
     "node_modules/emoji-regex": {
@@ -7788,13 +7787,13 @@
       }
     },
     "node_modules/expo-dev-client": {
-      "version": "5.0.13",
-      "resolved": "https://registry.npmjs.org/expo-dev-client/-/expo-dev-client-5.0.13.tgz",
-      "integrity": "sha512-+Io9uhlOXnL+qmNd3gC8RoCBSGH+2g/a4v/mcX3QrCfBXwMN17w8R+FoUoEnM3CTQxo1NI/5bsZnjVD4o+Lr+w==",
+      "version": "5.0.14",
+      "resolved": "https://registry.npmjs.org/expo-dev-client/-/expo-dev-client-5.0.14.tgz",
+      "integrity": "sha512-L57x2CrMb2tYsOSWc4zAvaGZ1+H7pZlGVvuDC1KzEsVCC2KjW1YUSEX9H5Zg+61Y4YUlHZ3h5rM5Eu/aCZmkZA==",
       "license": "MIT",
       "dependencies": {
         "expo-dev-launcher": "5.0.30",
-        "expo-dev-menu": "6.0.20",
+        "expo-dev-menu": "6.0.21",
         "expo-dev-menu-interface": "1.9.3",
         "expo-manifests": "~0.15.7",
         "expo-updates-interface": "~1.0.0"
@@ -7818,7 +7817,7 @@
         "expo": "*"
       }
     },
-    "node_modules/expo-dev-menu": {
+    "node_modules/expo-dev-launcher/node_modules/expo-dev-menu": {
       "version": "6.0.20",
       "resolved": "https://registry.npmjs.org/expo-dev-menu/-/expo-dev-menu-6.0.20.tgz",
       "integrity": "sha512-+ha876lpGAsRB9lqT7WRtcSvxZg2CjXKWkCSAghToyx4Wti1u3M/y3onJ4oOvddtKuFfFX4IRmnZYI3xi/TDCQ==",
@@ -7830,6 +7829,18 @@
         "expo": "*"
       }
     },
+    "node_modules/expo-dev-menu": {
+      "version": "6.0.21",
+      "resolved": "https://registry.npmjs.org/expo-dev-menu/-/expo-dev-menu-6.0.21.tgz",
+      "integrity": "sha512-HO5UpNqGXBFWqGoGQhlvarJLI0jZpXkIXBvl60QGiIwbpSRThVI5jjZ5iCFmrpSJjlSXczaid31ZfKGtggiVdA==",
+      "license": "MIT",
+      "dependencies": {
+        "expo-dev-menu-interface": "1.9.3"
+      },
+      "peerDependencies": {
+        "expo": "*"
+      }
+    },
     "node_modules/expo-dev-menu-interface": {
       "version": "1.9.3",
       "resolved": "https://registry.npmjs.org/expo-dev-menu-interface/-/expo-dev-menu-interface-1.9.3.tgz",
@@ -7965,9 +7976,9 @@
       }
     },
     "node_modules/expo-location": {
-      "version": "18.0.7",
-      "resolved": "https://registry.npmjs.org/expo-location/-/expo-location-18.0.7.tgz",
-      "integrity": "sha512-EPN5yTtDCH3EMiJpJFCWuD+vJkhVbl1j3tMYo3wkhGJN7xlvZf6naLXj8vYntdXSa5M40KjOgjaRiUUqf6+dXw==",
+      "version": "18.0.8",
+      "resolved": "https://registry.npmjs.org/expo-location/-/expo-location-18.0.8.tgz",
+      "integrity": "sha512-4PfkFtCeKCcDFa8aX2HcNeoEvc6SxZHHs3fhEDWPuIZU9MmIWYe9iPYynF4Qj0uK+sXYe+ALc2wIXbT8zrp6BQ==",
       "license": "MIT",
       "peerDependencies": {
         "expo": "*"
@@ -8045,13 +8056,13 @@
       }
     },
     "node_modules/expo-router": {
-      "version": "4.0.18",
-      "resolved": "https://registry.npmjs.org/expo-router/-/expo-router-4.0.18.tgz",
-      "integrity": "sha512-K3lI070u9M8G4MAwHbi/jy7Co+c9DQ+mW/h99YTMw+LTDIUbyzRy5tflboRDtkEbCv1W/8cDXu9Y2Puct4RRNA==",
+      "version": "4.0.19",
+      "resolved": "https://registry.npmjs.org/expo-router/-/expo-router-4.0.19.tgz",
+      "integrity": "sha512-oZ/vAx0x126Q6rccpWkMhKa/17YHYfeXQP8KwqaIadQsTR28cLgAY2gcAtFQyc8XTjgJmsRnfQNyCnyNN04DWg==",
       "license": "MIT",
       "dependencies": {
         "@expo/metro-runtime": "4.0.1",
-        "@expo/server": "^0.5.2",
+        "@expo/server": "^0.5.3",
         "@radix-ui/react-slot": "1.0.1",
         "@react-navigation/bottom-tabs": "^7.2.0",
         "@react-navigation/native": "^7.0.14",
@@ -8433,9 +8444,9 @@
       "license": "MIT"
     },
     "node_modules/flow-parser": {
-      "version": "0.263.0",
-      "resolved": "https://registry.npmjs.org/flow-parser/-/flow-parser-0.263.0.tgz",
-      "integrity": "sha512-F0Tr7SUvZ4BQYglFOkr8rCTO5FPjCwMhm/6i57h40F80Oz/hzzkqte4lGO0vGJ7THQonuXcTyYqCdKkAwt5d2w==",
+      "version": "0.265.0",
+      "resolved": "https://registry.npmjs.org/flow-parser/-/flow-parser-0.265.0.tgz",
+      "integrity": "sha512-C+bg/TZsDVlLMF14+q9P9FB2pjQSgWwYs0pkIMPE1FsZWS4A0kk1M28V6YphpxAPr3AISVRZ6VgpDepvCk6dGw==",
       "license": "MIT",
       "engines": {
         "node": ">=0.4.0"
@@ -10403,8 +10414,7 @@
       "version": "2.0.14",
       "resolved": "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.14.tgz",
       "integrity": "sha512-dn6wd0uw5GsdswPFfsgMp5NSB0/aDe6fK94YJV/AJDYXL6HVLWBsxeq7js7Ad+mU2K9LAlwpk6kN2D5mwCPVow==",
-      "license": "CC0-1.0",
-      "peer": true
+      "license": "CC0-1.0"
     },
     "node_modules/memoize-one": {
       "version": "5.2.1",
@@ -12479,11 +12489,10 @@
       }
     },
     "node_modules/react-native-svg": {
-      "version": "15.11.2",
-      "resolved": "https://registry.npmjs.org/react-native-svg/-/react-native-svg-15.11.2.tgz",
-      "integrity": "sha512-+YfF72IbWQUKzCIydlijV1fLuBsQNGMT6Da2kFlo1sh+LE3BIm/2Q7AR1zAAR6L0BFLi1WaQPLfFUC9bNZpOmw==",
+      "version": "15.8.0",
+      "resolved": "https://registry.npmjs.org/react-native-svg/-/react-native-svg-15.8.0.tgz",
+      "integrity": "sha512-KHJzKpgOjwj1qeZzsBjxNdoIgv2zNCO9fVcoq2TEhTRsVV5DGTZ9JzUZwybd7q4giT/H3RdtqC3u44dWdO0Ffw==",
       "license": "MIT",
-      "peer": true,
       "dependencies": {
         "css-select": "^5.1.0",
         "css-tree": "^1.1.3",
@@ -13701,12 +13710,12 @@
       }
     },
     "node_modules/stream-chat-expo": {
-      "version": "6.6.7",
-      "resolved": "https://registry.npmjs.org/stream-chat-expo/-/stream-chat-expo-6.6.7.tgz",
-      "integrity": "sha512-1t52SXykyJjwYN2nECsxVv+xg52RhZaP7bnix102V7Pd2+a6kkp0EFOL92VwC+BLKpNDpW7HDgfc8LWNc3WUjw==",
+      "version": "6.6.8",
+      "resolved": "https://registry.npmjs.org/stream-chat-expo/-/stream-chat-expo-6.6.8.tgz",
+      "integrity": "sha512-6panzlbm5rCgP5PqhwKtNDWB4JLSg9i8ewciVcsv2J0yIz5mtNibB6WxRtRrhv6pSKWnujLlMZ1qyi9+JxlYBg==",
       "license": "SEE LICENSE IN LICENSE",
       "dependencies": {
-        "stream-chat-react-native-core": "6.6.7"
+        "stream-chat-react-native-core": "6.6.8"
       },
       "peerDependencies": {
         "expo": ">=51.0.0",
@@ -13748,9 +13757,9 @@
       }
     },
     "node_modules/stream-chat-react-native-core": {
-      "version": "6.6.7",
-      "resolved": "https://registry.npmjs.org/stream-chat-react-native-core/-/stream-chat-react-native-core-6.6.7.tgz",
-      "integrity": "sha512-Xc/S92nUBSwfVPZqNjt/zNs/DJcRV1aRa/+yCSBCqjCwo0EuiWEP9yKy3xGxBkehNe4vaIDvkeREduA4dRUGpA==",
+      "version": "6.6.8",
+      "resolved": "https://registry.npmjs.org/stream-chat-react-native-core/-/stream-chat-react-native-core-6.6.8.tgz",
+      "integrity": "sha512-F8S70DHaiit6BEdKOkSMHq2bjMONhrouvJ+szBQuE430EJDgUlc2VErHk3yJCzqIt5lwfVZktjHuqSIOGVg5LQ==",
       "license": "SEE LICENSE IN LICENSE",
       "dependencies": {
         "@gorhom/bottom-sheet": "^5.1.1",
```

If you are still experiencing this issue, you might try:

Upgrading your Expo packages, especially expo-dev-client, expo-dev-menu, expo-location, and consider explicitly adding react-native-svg if it's not already in your dependencies.

Restarting your development environment (VS Code, Metro bundler, etc.).

Ensure you have a consistent and clean node_modules setup.

Hope this helps someone else!

**Comment by lovetingyuan** [comment]
![Image](https://github.com/user-attachments/assets/aa8d93db-402f-4ee8-ad0c-62a27a683253)

expo-router 4.0.19

expo: 52.0.40

expo-splash-screen: 0.29.22

**Comment by tarhansy** [comment]
same here with sentry..

**Comment by jerone** [comment]
Same issue:

```
TypeError: SplashModule.internalMaybeHideAsync is not a function (it is undefined)
  at _internal_maybeHideAsync (C:\Projects\<redacted>\node_modules\expo-router\build\utils\splash.js:48:46)
  at asyncGeneratorStep (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:16)
  at _next (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:26)
  at Promise$argument_0 (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:11)
  at tryCallTwo (C:\Projects\<redacted>\node_modules\promise\setimmediate\core.js:45:6)
...
(6 additional frame(s) were not displayed)
```

```
TypeError: SplashModule.internalPreventAutoHideAsync is not a function (it is undefined)
  at _internal_preventAutoHideAsync (C:\Projects\<redacted>\node_modules\expo-router\build\utils\splash.js:41:52)
  at asyncGeneratorStep (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:16)
  at _next (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:17:26)
  at Promise$argument_0 (C:\Projects\<redacted>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:11)
  at tryCallTwo (C:\Projects\<redacted>\node_modules\promise\setimmediate\core.js:45:6)
...
(6 additional frame(s) were not displayed)
```

**Comment by GenericArt** [comment]
+1 Same issue here as well with sentry

**Comment by Zenedith** [comment]
same

**Comment by jerone** [comment]
Plus, beside the repro in this issue, there is another repro here: https://github.com/expo/expo/issues/35573#issuecomment-2816694903

**Comment by thiagobrito** [comment]
Same issue here and it's blocking the deployment in Apple Store.

**Comment by mattyg986** [comment]
Also experiencing the same issue - latest versions of all packages confirmed.

**Comment by jerone** [comment]
I think closed stories are not monitored. We probably need to tag someone.
@alanjhughes You was previously involved; would you mind opening this issue.

**Comment by erdajt** [comment]
still same issue here with: `expo-splash-screen": "~0.30.8"` &  `"expo": "~53.0.9"` & `"@sentry/react-native": "~6.10.0"`

any update on a fix???

**Comment by Xe0n** [comment]
same issues "expo": "53.0.9", "@sentry/react-native": "~6.10.0",  "expo-splash-screen": "~0.30.8",

**Comment by rodolfoBee** [comment]
@alanjhughes this issue is still affecting users with recent versions.
this function is undefined: https://github.com/expo/expo/blob/main/packages/expo-router/src/utils/splash.ts#L46

**Comment by gilhrpenner** [comment]
Having the same issue with "expo": "~53.0.9" and "@sentry/react-native": "^6.14.0"

**Comment by aprilmintacpineda** [comment]
Still happening to me today `WARN  Possible Unhandled Promise Rejection (id: 1):`

```json
"expo": "~53.0.19",
"expo-font": "~13.3.2",
"expo-image": "~2.3.2",
"expo-linking": "~7.1.7",
"expo-router": "~5.1.3",
"expo-secure-store": "~14.2.3",
"expo-splash-screen": "~0.30.10",
"expo-status-bar": "~2.2.3",
```

I have:

```ts
import * as SplashScreen from 'expo-splash-screen';

SplashScreen.preventAutoHideAsync();
```

Then some other component calls `SplashScreen.hideAsync();`. However, for some reason it's only a warn for me and `hideAsync` actually works, if I remove it the splash screen never goes away which means the `preventAutoHideAsync` also worked.

**Comment by sohammondal** [comment]
Users are still experiencing this issue and the app is crashing because of that. Why is this closed?

**Comment by BenStirrup** [comment]
Hello @alanjhughes , could you at least tell the community why this issue is not re-opened ?

**Comment by alanjhughes** [comment]
@BenStirrup - I've tried the example that demonstrates the error and it does not reproduce. If the issue only presents when a third party library (sentry in this case), that we have no control over is installed, then the issue should be opened on that repository.

**Comment by alanjhughes** [comment]
@BenStirrup - I use examples with dependencies from the default template every day and have not come across this issue. I cannot fix something if the breakage is not caused by something that we ship. If you can provide an example that demonstrates this issue without third party dependencies then I would be happy to fix it but until then, I cannot fix a problem that I cannot see

**Comment by Harisene** [comment]
Having the same issue. 

```
expo: 53.0.9
@sentry/react-native: 6.18.1
```

**Comment by gr8pathik** [comment]
Anyone found an solution on this? Having the same issue.

**Comment by itsandrehere** [comment]
Having the same issue.

**Comment by Harisene** [comment]
I moved my code to a new project for some other reason, and this issue was also resolved. Not sure exactly how. I assume maybe cos now I have the latest Expo and Sentry versions. 🤷‍♂️

**Comment by aprilmintacpineda** [comment]
> I moved my code to a new project for some other reason, and this issue was also resolved. Not sure exactly how. I assume maybe cos now I have the latest Expo and Sentry versions. 🤷‍♂️

That might mean that the problem is with settings / other packages or the versions of those packages. Where you able to get to the bottom of it?
