### ISSUE TITLE
[expo-dev-launcher@55.0.26] Regression: appBridge property removed from header but referenced in implementation

### ISSUE THREAD

**Issue by uholland** [expo/expo#44676]
## Summary

`expo-dev-launcher@55.0.26` (published 2026-04-10) removed the `appBridge` property declaration from `EXDevLauncherController.h` but left a reference to `self.appBridge` in `EXDevLauncherController.m:623`. This breaks **every** iOS development build on SDK 55 with the default Xcode 26 image.

## Proof (no repro project needed — this is a source-level regression)

**55.0.25 header** declares the property:
```
@property (nonatomic, weak) RCTBridge * _Nullable appBridge;
```

**55.0.26 header** — property removed.

**55.0.26 implementation** still references it:
```objc
// EXDevLauncherController.m:623
[manager updateCurrentBridge:self.appBridge];
```

You can verify yourself:

```bash
# 55.0.25 — property exists in header (1 match), 4 references in impl
npm pack expo-dev-launcher@55.0.25 --dry-run
curl -sL $(npm view expo-dev-launcher@55.0.25 dist.tarball) | tar xzO package/ios/EXDevLauncherController.h | grep -c appBridge
# Output: 1
curl -sL $(npm view expo-dev-launcher@55.0.25 dist.tarball) | tar xzO package/ios/EXDevLauncherController.m | grep -c appBridge
# Output: 4

# 55.0.26 — property GONE from header (0 matches), but 1 reference remains in impl
curl -sL $(npm view expo-dev-launcher@55.0.26 dist.tarball) | tar xzO package/ios/EXDevLauncherController.h | grep -c appBridge
# Output: 0
curl -sL $(npm view expo-dev-launcher@55.0.26 dist.tarball) | tar xzO package/ios/EXDevLauncherController.m | grep -c appBridge
# Output: 1
```

## Build Error

```
EXDevLauncherController.m:623:37: error: property 'appBridge' not found on object of type 'EXDevLauncherController *'
  [manager updateCurrentBridge:self.appBridge];
                                    ^
```

## Impact

- Affects **all** SDK 55 iOS development builds using the default EAS image (Xcode 26.2)
- Both 55.0.26 and 55.0.27 are affected
- Published today (2026-04-10)

## Workaround

Pin `expo-dev-client` to the last working version:

```json
"expo-dev-client": "55.0.25"
```

## Environment

- Expo SDK: 55
- expo-dev-launcher: 55.0.26 / 55.0.27
- EAS Build image: macos-sequoia-15.6-xcode-26.2 (sdk-55 default)
- Platform: iOS
