### ISSUE TITLE
[EXPO 48] Android build fails

### ISSUE THREAD

**Issue by Bilitskiy** [expo/expo#21733]
### Minimal reproducible example

After updating Expo from 47 to 48 i can't make android build using eas. A number of errors appear.

### Summary

Task :app:compileReleaseJavaWithJavac FAILED
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainActivity.java:19: error: package R does not exist
[stderr] 
    setTheme(R.style.AppTheme);
[stderr] 
              ^
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainActivity.java:39: error: cannot find symbol
[stderr] 
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
[stderr] 
                                                  ^
[stderr] 
  symbol:   variable BuildConfig
[stderr] 
  location: class MainActivity
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:26: error: cannot find symbol
[stderr] 
        return BuildConfig.DEBUG;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:45: error: cannot find symbol
[stderr] 
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:50: error: cannot find symbol
[stderr] 
        return BuildConfig.IS_HERMES_ENABLED;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:63: error: cannot find symbol
[stderr] 
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr] 
        ^
[stderr] 
  symbol:   variable BuildConfig
[stderr] 
  location: class MainApplication
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:63: error: illegal parenthesized expression
[stderr] 
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr] 
       ^
[stderr] 
/home/expo/workingdir/build/android/app/src/main/java/com/mediateam/dev/walletz/MainApplication.java:67: error: cannot find symbol
[stderr] 
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
[stderr] 
    ^
[stderr] 
  symbol:   variable ReactNativeFlipper
[stderr] 
  location: class MainApplication
[stderr] 
/home/expo/workingdir/build/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:110: error: package com.mediateam.dev.walletz.R does not exist
[stderr] 
      new AppCenterReactNativeAnalyticsPackage(getApplication(), getResources().getString(com.mediateam.dev.walletz.R.string.appCenterAnalytics_whenToEnableAnalytics)),
[stderr] 
                                                                                                                     ^
[stderr] 
/home/expo/workingdir/build/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:111: error: package com.mediateam.dev.walletz.R does not exist
[stderr] 
      new AppCenterReactNativeCrashesPackage(getApplication(), getResources().getString(com.mediateam.dev.walletz.R.string.appCenterCrashes_whenToSendCrashes)),
[stderr] 
                                                                                                                   ^
[stderr] 
10 errors

### Environment

System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.15.1 - /usr/local/bin/npm
      Watchman: 2022.05.30.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
