### ISSUE TITLE
[expo-local-authentication][android][bare] Build fails, cannot find symbols FEATURE_FACE or FEATURE_IRIS

### ISSUE THREAD

**Issue by alexanderkho** [expo/expo#8964]
### Summary of Issue (just a few sentences)
I have been using expo-local-authentication version 9.0.0 with a bare react native workflow. Upgrading to 9.1.1 gave me the following error when building with Android. 

```
/my-project/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java:93: error: cannot find symbol
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_FACE)) {
                                                       ^
  symbol:   variable FEATURE_FACE
  location: class PackageManager
/my-project/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java:96: error: cannot find symbol
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_IRIS)) {
                                                       ^
  symbol:   variable FEATURE_IRIS
  location: class PackageManager
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-local-authentication:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

 Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.9

Building on Pixel 3a XL emulator with Android API 29.

### Expected behavior 
Build should not fail.

**Comment by manohar-octifi** [comment]
Same error while creating release build in version 9.0.0

```
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_FACE)) {
      results.add(AUTHENTICATION_TYPE_FACIAL_RECOGNITION);
    }
    if (mPackageManager.hasSystemFeature(PackageManager.FEATURE_IRIS)) {
      results.add(AUTHENTICATION_TYPE_IRIS);
    }
```

build succeeded when the above piece of code removed from 
`/my-project/node_modules/expo-local-authentication/android/src/main/java/expo/modules/localauthentication/LocalAuthenticationModule.java
`

**Comment by tsapeta** [comment]
Thanks for the report! What's your `compileSdkVersion` setting in `build.gradle`?

**Comment by manohar-octifi** [comment]
> Thanks for the report! What's your `compileSdkVersion` setting in `build.gradle`?

28

**Comment by tsapeta** [comment]
According to the docs (https://developer.android.com/reference/kotlin/android/content/pm/PackageManager#feature_face), these two symbols are available as of API level 29, so I believe changing this setting to 29 will solve the problem 😉 Sorry that we missed this. I'm leaving this issue open as this should be fixed anyway.

**Comment by manohar-octifi** [comment]
> https://developer.android.com/reference/kotlin/android/content/pm/PackageManager#feature_face

@tsapeta I’ll try changing the version 
Thanks a lot for the response

**Comment by alexanderkho** [comment]
@tsapeta bumping `compileSdkVersion` to 29 worked for me, thank you!

**Comment by tsapeta** [comment]
I've just published `expo-local-authentication@9.2.0` including the fix for this 🙂
