### PR TITLE
[cli] bump swc to fix js debugger launching error

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fixing an error `TypeError: osascript(...) is not a function` when pressing "j" to launch js debugger 
this is a regression from #27061 and actually a bug from swc
the transpiled **LaunchBrowserImplMacOS.js** is like
```js
function osascript() {
    const data = _interopRequireWildcard(require("@expo/osascript"));
    osascript = function() {
        return data;
    };
    return data;
}

    async isSupportedBrowser(browserType) {
        let result = false;
        try {
            // NOTE(kudo): the double ()() after osascript encountered the problem
            await osascript()().execAsync(`id of application "${this.MAP[browserType]}"`);
            result = true;
        } catch {
            result = false;
        }
        return result;
    }
```

# How

upgrade swc fixed the problem, maybe a relevant fix is https://github.com/swc-project/swc/commit/0a7ca2f4bbfaa2573b4da6b25127064cbcfd755f?

it's near release stage and i don't want to upgrade swc 1.4. let's stick on 1.2.

# Test Plan

pressing "j" to open js debugger on macos

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).

### CODE REVIEW

File: yarn.lock [hunk 1]
```diff
@@ -20812,6 +20850,15 @@ wrap-ansi@^6.2.0:
     string-width "^4.1.0"
     strip-ansi "^6.0.0"
 
+wrap-ansi@^7.0.0:
```
Comment (Kudo) [inline yarn.lock:20853]: 🙈

Comment (byCedric) [reply yarn.lock:20853]: oh man, Yarn v1 really is running on its last breath in this repo 🙈

**Review by byCedric — APPROVED** [review]
Works! Thanks 🙏
