### ISSUE TITLE
babel-plugin-module-resolver issues when upgrading to v50 and expo-router v4

### ISSUE THREAD

**Issue by dmathisen** [expo/expo#26512]
### Minimal reproducible example

Not available be SDK 50

### Summary

I apologize for not having a reproducible example, but I have a decent amount of detail and a fix that worked.

I'm upgrading my app from **expo** 49.0.21 to 50.0.2 and **expo-router** 2.0.14 to 3.4.3

I followed both guides [here](https://expo.dev/changelog/2024/01-18-sdk-50) and [here](https://blog.expo.dev/expo-router-v3-beta-is-now-available-eab52baf1e3e#aed2), removed `expo-router/babel` from my babel.config plugins.

After doing a dev build and install, I got an error `Cannot find module 'babel-plugin-module-resolver'` (full stack below).

I've tried several things with babel.config and different versions of expo/expo-router without any luck.

**The fix** was to `npm install babel-plugin-module-resolver` but **NOT** as a dev dependency. This feels wrong, as it probably should be a dev dependency, if anything, but it's what got my app building again. I don't know if this helps and as of now, it's resolved on my end. I wanted to point it out, in case it helps debug or clarify any other reported issues.

Good luck, and thanks for this incredible release. Great work!

```
Android Bundling failed 48ms (C:\Projects\my-app\node_modules\expo-router\entry.js)
error: node_modules\expo-router\entry.js: Cannot find module 'babel-plugin-module-resolver'
Require stack:
- C:\Projects\my-app\node_modules\@babel\core\lib\config\files\plugins.js
- C:\Projects\my-app\node_modules\@babel\core\lib\config\files\index.js
- C:\Projects\my-app\node_modules\@babel\core\lib\index.js
- C:\Projects\my-app\node_modules\metro-transform-worker\src\index.js
- C:\Projects\my-app\node_modules\@expo\metro-config\build\transform-worker\metro-transform-worker.js
- C:\Projects\my-app\node_modules\@expo\metro-config\build\transform-worker\transform-worker.js
- C:\Projects\my-app\node_modules\metro\src\DeltaBundler\Worker.flow.js
- C:\Projects\my-app\node_modules\metro\src\DeltaBundler\Worker.js
- C:\Projects\my-app\node_modules\jest-worker\build\workers\processChild.js
- If you want to resolve "module-resolver", use "module:module-resolver"

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
```

Here's a full list of my project dependencies, if it helps...

```
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-community/datetimepicker": "7.6.1",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "babel-plugin-module-resolver": "^5.0.0",
    "date-fns": "^3.2.0",
    "expo": "^50.0.2",
    "expo-av": "~13.10.3",
    "expo-constants": "~15.4.5",
    "expo-dev-client": "~3.3.6",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.3",
    "expo-status-bar": "~1.11.1",
    "firebase": "^10.7.1",
    "module-resolver": "^1.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.2",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-reanimated": "~3.6.0",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.10"
  },
  "devDependencies": {
    "@babel/core": "^7.23.7",
    "@types/react": "~18.2.48",
    "@typescript-eslint/eslint-plugin": "^6.19.0",
    "@typescript-eslint/parser": "^6.19.0",
    "concurrently": "^8.2.2",
    "eslint": "^8.56.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-native": "^4.1.0",
    "typescript": "^5.3.3"
  }
```

### Environment

    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    npmPackages:
      expo: ^50.0.2 => 50.0.2
      expo-router: ~3.4.3 => 3.4.3
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.10 => 0.19.10
    Expo Workflow: managed
