### PR TITLE
fix(babel-preset-expo): Fix three Hermes v1 (250829098) IR/compiler syntax bugs with fix-up transforms

### LINKED ISSUE #45592: 🐛 [SDK 56 preview.7] await of an async function's Promise resolves to undefined while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS
# 🐛 [SDK 56 preview.7] `await` of an async function's Promise resolves to `undefined` while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS

## Summary

On `expo@56.0.0-preview.7` (`react-native@0.85.3`, Hermes default, iOS simulator), `await aPromise` resolves with `undefined` *before* the underlying `async function` reaches its `return` statement. The function continues executing in the background, its `return` does eventually fire with the correct value, but the awaiting caller has already moved on with `undefined`.

The same userland code works correctly on `expo@55.0.23` / `react-native@0.83.6`.

The most visible symptom: **every RTK Query `queryFn`-based endpoint fails** because the dispatcher's internal `await executeRequest(arg)` resolves to `undefined`, then `finalQueryReturnValue.data` access throws `TypeError: Cannot read property 'data' of undefined`. Identical `@reduxjs/toolkit@2.11.2` works on SDK 55 with the same userland code.

## Minimal reproducible example

**Repro:** https://github.com/azaars/expo-56-rtk-await-bug

```bash
git clone https://github.com/azaars/expo-56-rtk-await-bug.git
cd expo-56-rtk-await-bug
npm install
npx expo prebuild --clean --platform ios
npx expo run:ios
```

The repro is `npx create-expo-app@latest --template blank-typescript` scaffolded, then bumped to `expo@next`, with `@reduxjs/toolkit` + `react-redux` added and a single `queryFn` endpoint that returns `{ data: { message: 'hello from queryFn' } }`. Three small files: `src/api.ts` (createApi), `src/store.ts` (configureStore), `App.tsx` (Provider + a child that subscribes via `useGetThingQuery()`).

## Steps to reproduce

1. Clone and install per above.
2. `npx expo prebuild --clean --platform ios && npx expo run:ios`.
3. App boots in iOS simulator. The single screen renders.

## Expected behavior

```
isLoading: false
isError:   false
data:      {"message":"hello from queryFn"}
error:     (none)
```

## Actual behavior

```
isLoading: false
isError:   true
data:      undefined
error:     {"status":"CUSTOM_ERROR","error":"Cannot read property 'data' of undefined"}
```

Metro logs:

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning: {"data":{"message":"hello from queryFn"}}
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       In the case of an unhandled error, no tags will be "provided" or "invalidated".
       [TypeError: Cannot read property 'data' of undefined]
```

## Diagnostic evidence

In a parallel investigation I patched `node_modules/@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` at the dispatcher's await call site:

```js
// Patched at line 1091 of executeEndpoint:
const __exr_promise = executeRequest(arg.originalArgs);
console.log('[RTK PATCH] BEFORE-AWAIT typeof:', typeof __exr_promise,
            'isPromise:', __exr_promise instanceof Promise,
            'isUndefined:', __exr_promise === undefined);
finalQueryReturnValue = await __exr_promise;
console.log('[RTK PATCH] AFTER-AWAIT finalQueryReturnValue =',
            JSON.stringify(finalQueryReturnValue),
            'type:', typeof finalQueryReturnValue);

// And patched executeRequest's return statement (~line 1041):
const __ret = __spreadProps(__spreadValues({}, result), { data: transformedResponse });
console.log('[RTK PATCH] executeRequest about to return:',
            JSON.stringify(__ret), 'type:', typeof __ret);
return __ret;
```

Time-ordered output from the iOS simulator (with the queryFn reduced to a synchronous return of a hoisted constant `{ data: [] }` to eliminate userland variables):

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning hoisted: {"data":[]}
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       [TypeError: Cannot read property 'data' of undefined]
LOG    [RTK PATCH] executeRequest about to return: {"data":[]} type: object
```

Note the **time ordering**:

1. `BEFORE-AWAIT` confirms `executeRequest()` returns a real `Promise` synchronously (`isPromise: true`, `isUndefined: false`).
2. `AFTER-AWAIT` resumes immediately with `undefined`.
3. The dispatcher's catch block logs the unhandled error.
4. **Only afterwards** does `executeRequest`'s body reach its return statement and log the correct value.

A nested-`await` test inside the queryFn itself behaves consistently — the inner await resolves with the right value, but only after RTK's outer await has already moved on:

```
LOG    [REPRO] outer enter
LOG    [REPRO] inner enter
LOG    [REPRO] before await, p instanceof Promise: true typeof p: object
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  [TypeError: Cannot read property 'data' of undefined]
LOG    [REPRO] after await, r: {"data":[]} typeof: object
```

## Same pattern in non-RTK code

In a private brownfield app on the same SDK 56 preview.7 stack, the same pattern surfaces in code that has nothing to do with RTK Query:

```ts
const localPlants = await soloTaskService.getLocalPlants('solo-user', 'active');
// → throws TypeError: Cannot read property 'map' of undefined on the next line
const mappedPlants = localPlants.map((lp) => ({...}));
```

`SoloTaskService.getLocalPlants` is a class `async` method that ends with `return rows.map(...)`. The await receives `undefined`. Same root cause, completely separate call path. Not included in the public minimal repro because reproducing it cleanly requires recreating that class context, but happy to share if useful.

## What was ruled out

- **`@reduxjs/toolkit` version**: identical `2.11.2` works on SDK 55 / RN 0.83.6 with the same userland code.
- **`react-redux` version**: `9.2.0`, unchanged across SDKs.
- **`react-native-reanimated`/`worklets` babel plugin**: bug reproduces with `react-native-reanimated/plugin` removed from `babel.config.js` and Metro restarted with `--clear`.
- **Userland code**: queryFn reduced to a hoisted-constant synchronous return. Bug persists.
- **`baseQuery: fakeBaseQuery()` vs `baseQuery: async () => ({ data: null })`**: bug fires with both.
- **`providesTags`** as static array vs callback: no difference.
- **Node test suite**: `npm test` (Node + ts-jest + better-sqlite3, no Hermes) passes 3028/3030 in the brownfield app on SDK 56. Bug is iOS-Hermes-runtime-only.

## Suspected scope

The dispatcher in `@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` declares `executeRequest` as a hoisted nested `async function` inside another `async function`:

```js
async function executeEndpoint(arg, ...) {
  // ...
  async function executeRequest(finalQueryArg) {
    // ...
    return __spreadProps(...);
  }
  // ...
  finalQueryReturnValue = await executeRequest(arg.originalArgs);
  // → undefined here despite executeRequest returning a Promise that
  //   eventually resolves to the correct value
}
```

The same nested-async-function-declaration pattern is what surfaces the bug in the non-RTK case as well. This points to Hermes RN 0.85.3's async-function / Promise resolution machinery rather than RTK or app code.

## Environment

```
expo-env-info 2.0.12 environment info:
  System:
    OS: macOS 26.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 25.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 11.12.1 - /opt/homebrew/bin/npm
    Watchman: 2025.11.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
  IDEs:
    Android Studio: 2025.1 AI-251.26094.121.2513.14007798
    Xcode: 26.4.1/17E202 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^56.0.0-preview.7 => 56.0.0-preview.7
    react: 19.2.3 => 19.2.3
    react-dom: 19.2.3 => 19.2.3
    react-native: 0.85.3 => 0.85.3
  npmGlobalPackages:
    eas-cli: 16.19.3
  Expo Workflow: bare (custom dev client via expo-dev-client)
```

Additional minimal-repro deps:

- `@reduxjs/toolkit@2.11.2`
- `react-redux@9.2.0`
- `babel-preset-expo@56.0.5`

## Asks

1. Is this a known issue in the SDK 56 preview Hermes / RN 0.85.3?
2. Workaround guidance for the next 1–2 weeks until SDK 56 GA?
3. Happy to attach the patched `rtk-query.legacy-esm.js`, run further traces, or drop into Discord for live debugging if useful.

### PR DESCRIPTION
**Pull request by kitten**
# Why

Resolves #45592

There's three fixes that have landed in Hermes v1 since the `250829098.x.x` branch cut that can reasonably be triggered by user code. In descending order of likelihood:
- https://github.com/facebook/hermes/commit/68bfb3a48b31a19ac904ce6d3174ab2698ffc5e9
- https://github.com/facebook/hermes/commit/18a963465
- https://github.com/facebook/hermes/commit/1e94fbe0e

The first issue is very easy to trigger, since it involves any complex parameters for any async arrow function.

These commits have been identified in a full diff between `250829098.0.10` and the `static_h` branch on Hermes, and cross-checked against the `250829098.0.0-stable`. There's more fixes that this branch doesn't contain but they either:
- aren't relevant for most codebases or are Hermes toolchain fixes
- are runtime fixes (unfortunate, but not relevant for Babel)
- cannot be fixed or are hard to hit
- **apply only to async generators which are already transpiled by our preset**

# How

We apply three targeted fix-ups in Babel transforms that are targeted to these fixes. They swap out the problematic patterns with working ones.

- Add test cases to `test-suite` for failing patterns
- Add `fix-hermes-v1-async-arrow-non-simple-params` plugin for Hermes v1 preset
- Add `fix-hermes-v1-class-in-finally` plugin for Hermes v1 preset
- Add `fix-hermes-v1-super-in-object-accessor` plugin for Hermes v1 preset

# Test Plan

- Checked fixes against the `test-suite` and confirmed they avoid all three bugs
- Added unit tests per Babel plugin with snapshots
- Confirmed that transform performance isn't impacted significantly using `node scripts/profile-plugins.js --config hermes-v1`

# Checklist

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

### CODE REVIEW

File: packages/babel-preset-expo/src/configs/hermes-v1.ts [hunk 1]
```diff
@@ -22,6 +26,11 @@ export interface HermesV1ConfigOptions {
 /** The JS syntax preset used with Hermes v1 (SDK 56+) */
 module.exports = function (_api: ConfigAPI, _options: HermesV1ConfigOptions) {
   const plugins: PluginItem[] = [
+    // NOTE(@kitten): See individual plugins for which Hermes v1 fixes they correspond to
+    [fixHermesV1AsyncArrowNonSimpleParams],
+    [fixHermesV1SuperInObjectAccessor],
+    [fixHermesV1ClassInFinally],
```
Comment (ide) [inline packages/babel-preset-expo/src/configs/hermes-v1.ts:32]: This may be a micro-optimization but I remember the RN Babel preset would do cheap string checks for whether to include a plugin. For instance, if a file doesn't contain `super` at all (common, I'd say) we could omit `fixHermesV1SuperInObjectAccessor`. If it doesn't include `class` and `finally`, we can omit `fixHermesV1ClassInFinally`. The async function parameters are complex enough to detect that the cost of always running the plugin might make sense.

Comment (kitten) [reply packages/babel-preset-expo/src/configs/hermes-v1.ts:32]: the `src` check sin `@react-native/babel-preset` look very convincing, but it's actually now passed as `src: null` and Babel's config evaluation cache has replaced this mostly. Likely because evaluating the config itself exceeds the cost of some source checks.

The only alternative for very expensive plugins is to abort their visitors, as far as I'm aware, e.g. https://github.com/expo/expo/blob/main/packages/babel-preset-expo/src/plugins/lazy-decorators-plugin.ts
(or doing caller checks, which explicitly invalidates the config cache)

In this case, the plugin bails out early enough that I think this isn't needed. At least the `scripts/profiler-plugins.js` run puts it at a very low cost relatively to other plugins, so I didn't want to add any speculative checks, because the numbers indicate this doesn't impact transform times significantly (at least in the quick checks I did)

**Review by byCedric — APPROVED** [review]
I'm disappointed the latest Hermes release in React Native is from 2025-08-29. But, nothing we can do now to fix that for SDK 56...

The tests are a good addition as well!
