### ISSUE TITLE
Error building in SDK version 42 using use_frameworks! in bare workflow

### ISSUE THREAD

**Issue by fcaride** [expo/expo#13634]
### Summary

Im getting this error after i upgrade from v40 to v42 in my bare workflow project.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UMExportedModule", referenced from:
      _OBJC_CLASS_$_EXApplication in EXApplication.o
  "_OBJC_METACLASS_$_UMExportedModule", referenced from:
      _OBJC_METACLASS_$_EXApplication in EXApplication.o
  "_UMRegisterModule", referenced from:
      +[EXApplication load] in EXApplication.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.7.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.1/bin/yarn
      npm: 7.19.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        Android NDK: 22.0.6917172-beta1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

run -> expo init sample
modify the podfile and add "use_frameworks!"
cd ios
pod install
npm run ios

**Comment by fcaride** [comment]
any info on this?
