### ISSUE TITLE
Upgrading `targetSdkVersion` > 31 results in Android build time error when using `expo-device`

### ISSUE THREAD

**Issue by jsindos** [expo/expo#19752]
### Summary

I am getting the following Android compilation error after upgrading `targetSdkVersion` to 33. I narrowed the problem down to `expo-device`.

```
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.SecurityException:
Settings key: <bluetooth_name> is only readable to apps with targetSdkVersion lower than or equal to: 31
```

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.02.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.2 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Minimal reproducible example

"expo-device": "~4.3.0"

**Comment by gabrieldonadel** [comment]
Hi @jsindos, this issue seems like a duplicate of https://github.com/expo/expo/issues/18738, if that's the case this problem has been fixed by https://github.com/expo/expo/pull/19666.

**Comment by jsindos** [comment]
Great, thank you!

**Comment by rishabraghav** [comment]
hi @jsindos how did you resolve it ? I'm having the same issue when setting target sdk to 33. It's working fine when sdk is set to 31

**Comment by jsindos** [comment]
@rishabraghav Using the latest version of `expo-device` should fix the issue.
