### ISSUE TITLE
unimodules-react-native-adapter:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by dig22** [expo/expo#13168]
### Summary

![image](https://user-images.githubusercontent.com/9392098/120882667-e0424c00-c5f6-11eb-9d7b-e9f7dd643e04.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 4.5.2 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      expo: ^41.0.0 => 41.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

I was working on ubuntu before, I changed switched to windows and ran : 
` npm i `
`npm run android`

**Comment by achmadk** [comment]
I have the same error as this, after upgrading `react-native-unimodules` from v0.13.3 into v0.14.1.

**Comment by CodeSMG** [comment]
+1

**Comment by professorkolik** [comment]
+1

**Comment by antoniogoulao** [comment]
+1
After updating to Expo SDK 42

**Comment by GuillaumeRZ** [comment]
Same error ! :) Trying `cd android && ./gradlew clean` doesn't do anything.

**Comment by majugurci** [comment]
Same error with react-native-unimodules@0.14.3

**Comment by achmadk** [comment]
Yes, still have the same error with react-native-unimodules@0.14.3.

```sh
require(expo-modules-autolinking)(process.argv.slice(1))
[0]         ^
[0]
[0] ReferenceError: expo is not defined
[0]     at [eval]:1:9
[0]     at Script.runInThisContext (vm.js:134:12)
[0]     at Object.runInThisContext (vm.js:311:38)
[0]     at internal/process/execution.js:77:19
[0]     at [eval]-wrapper:6:22
[0]     at evalScript (internal/process/execution.js:76:60)
[0]     at internal/main/eval_string.js:23:3
```
Maybe this is the culprit why we get the `compileDebugJavaWithJavac FAILED` error ([source](https://github.com/expo/expo/blob/master/packages/%40unimodules/react-native-adapter/scripts/autolinking.gradle#L97)). In windows, the module name inside `require` has no quotation.

**Comment by brentvatne** [comment]
hi there! can someone share a reproducible example? you can run `expo init` and choose the "minimal" template and notice that the project runs as expected using react-native-unimodules 0.14.3, so i'm not sure how to reproduce the problem that you are seeing

**Comment by achmadk** [comment]
1. Create a react-native project with `react-native init`.
2. Add `react-native-unimodules`, then add additional codes into android project files, according to [this doc](https://docs.expo.io/bare/installing-unimodules/).
3. Run `react-native run-android`.

**Comment by brentvatne** [comment]
@achmadk - please do that and share the project with me on github if you believe that will reproduce it

**Comment by achmadk** [comment]
[Here it is](https://github.com/achmadk/compileDebugJavaWithJavac-rn-project), @brentvatne .

**Comment by brentvatne** [comment]
hi @achmadk. i followed the instructions myself and it worked just fine: https://github.com/brentvatne/achmadk. try cloning that and running it on your machine.

if that doesn't work for you, let me know. if it does work, compare the relevant files with those in your project to see what you did differently. if you still can't figure it out, then init a project and commit everything, then in a separate commit make the changes from the set up guide and send me a link to that specific commit with only those changes.

**Comment by youennPennarun** [comment]
Hi @breentvatne 
I cloned your branch but got the same error message 
```  
error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class ModuleRegistryAdapter
   ```  
   
  Before that I was also able to reproduce the same issue by creating a project with: 
 - `npx crna -t with-dev-client` => `npm run eject` 
 -  `react-native init` => followed the docs to setup unimodules
 - `npx crna` => select the expo navigation template (I haven’t tried any other template than the “with-dev-client” one) => Bump every expo packages to latest => [and during a second attempt I tried running `npm dedupe` to prevent two different version of expo-constants in the node modules tree]  
 
 I should note that `npx crna -t with-dev-client` works just fine but doesn’t fully satisfy my needs as I need to tweak native code)
 
 The same issue has been reported in #13475, with the difference that it also happens on macOS Catalina and node v14.15.0, not only on Windows and Node 12  
 
 Sorry I can’t report much more on this issue :/

**Comment by valascus** [comment]
Could you check if this works for you?

[[Expo 42] Bare app build failing #13475](https://github.com/expo/expo/issues/13475#issuecomment-873380737)

**Comment by achmadk** [comment]
I still have the same error after cloning your repo, @brentvatne.

**Comment by brentvatne** [comment]
can you try running 'npx react-native doctor' and share the output here?

**Comment by wbroek** [comment]
Got the same error today but not on my development machine (Macbook) but on the CI. We use Appcenter as our build server and we are getting the error there. Tried to look if there were difference in the unimodule settings needed for android; determined in the installation guide but we could not find any differences. Did not try to build the test project yet but if needed I will.
Also attached de full build logs from Appcenter maybe there is something in there.
```
2021-07-05T14:52:18.2112480Z > Task :unimodules-react-native-adapter:compileReleaseJavaWithJavac FAILED
2021-07-05T14:52:18.2114160Z /Users/runner/work/1/s/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
2021-07-05T14:52:18.2115250Z     mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
2021-07-05T14:52:18.2116300Z                                                                   ^
2021-07-05T14:52:18.2117100Z   symbol:   class ExpoModulesPackageList
2021-07-05T14:52:18.2118030Z   location: class ModuleRegistryAdapter
2021-07-05T14:52:18.2118760Z 1 error
2021-07-05T14:52:18.4040680Z 
2021-07-05T14:52:18.4046320Z FAILURE: Build failed with an exception.
```

[1_Build.txt](https://github.com/expo/expo/files/6765220/1_Build.txt)

**Comment by brkastner** [comment]
I'm also seeing this issue in v42 and after a lot of digging, it seems to be caused by [pull request #11593](https://github.com/expo/expo/pull/11593).

**Comment by brkastner** [comment]
> Could you check if this works for you?
> 
> [[Expo 42] Bare app build failing #13475](https://github.com/expo/expo/issues/13475#issuecomment-873380737)

Upgrading node from v12 to v14 and applying that patch worked for me!

**Comment by professorkolik** [comment]
> Got the same error today but not on my development machine (Macbook) but on the CI. We use Appcenter as our build server and we are getting the error there. Tried to look if there were difference in the unimodule settings needed for android; determined in the installation guide but we could not find any differences. Did not try to build the test project yet but if needed I will.
> Also attached de full build logs from Appcenter maybe there is something in there.
> 
> ```
> 2021-07-05T14:52:18.2112480Z > Task :unimodules-react-native-adapter:compileReleaseJavaWithJavac FAILED
> 2021-07-05T14:52:18.2114160Z /Users/runner/work/1/s/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
> 2021-07-05T14:52:18.2115250Z     mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
> 2021-07-05T14:52:18.2116300Z                                                                   ^
> 2021-07-05T14:52:18.2117100Z   symbol:   class ExpoModulesPackageList
> 2021-07-05T14:52:18.2118030Z   location: class ModuleRegistryAdapter
> 2021-07-05T14:52:18.2118760Z 1 error
> 2021-07-05T14:52:18.4040680Z 
> 2021-07-05T14:52:18.4046320Z FAILURE: Build failed with an exception.
> ```
> 
> [1_Build.txt](https://github.com/expo/expo/files/6765220/1_Build.txt)

Same for us, works locally but fails on Bitrise

**Comment by brentvatne** [comment]
> can you try running 'npx react-native doctor' and share the output here?

to anyone replying here, please refer to this comment

**Comment by grifotv** [comment]
I did have this issue with Node v10.14.1, after upgrading to v14.17.2 it worked fine for me.

**Comment by professorkolik** [comment]
Upgraded react-native-unimodules to latest (as for now 0.14.3) and installing Node v14.7.3 **resolved** the issue on Bitrise

**Comment by rajeshde** [comment]
Created this [project](https://github.com/rajeshde/expo-test) with `npx create-react-native-app` 

Run `npm run android` and it worked fine.

Installed `expo-camera` and followed [this extra steps](https://github.com/expo/expo/tree/master/packages/expo-camera#installation-in-bare-react-native-projects)

Run `npm run android` and it worked fine again. Successfully used camera on the app, on physical device.


Now when im trying to **clean and rebuild** this same project from Android Studio, i am getting this error
```
expo-test/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/ModuleRegistryAdapter.java:26: error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);
                                                                  ^
  symbol:   class ExpoModulesPackageList
  location: class ModuleRegistryAdapter
```

On Line 26, it says `Cannot resolve symbol 'ExpoModulesPackageList'`

#
But again, its still working fine while running just `npm run android`

Here is `npx react-native doctor` ouput

```
Common
 ✓ Node.js
 ✓ npm
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.06.07.00
   - Version supported: 4.x

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 27.0.3, 28.0.3, 29.0.2, 30.0.3, 31.0.0
   - Version supported: 29.0.3
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   3
Warnings: 1
```

Some other info

Node 14.17.1
npm  6.14.13

**Comment by brentvatne** [comment]
@raajnadar - try updating to node v14.7.3 and reinstalling node_modules as per the above comments

**Comment by rajeshde** [comment]
Updated node to v14.17.3, but did not work.

**Comment by daominhsangvn** [comment]
Try to change Gradle to 6.9. It did work for me

**Comment by yunusaydinonline** [comment]
> Updated node to v14.17.3, but did not work.
> 
> **Edit: Added this screenshot from Android Studio**
> 
> <img alt="Screenshot 2021-07-08 at 9 45 07 AM" width="1398" src="https://user-images.githubusercontent.com/22252320/124861526-66c0c380-dfd1-11eb-873b-d60311596db7.png">

I'm gettin exactly the same error with my bare workflow project. I've been searching a fine solution since last 3 days but so far no good.

I'm using react native **v0.63.4** and it seems like it happens all versions greater than **v0.60**.

I also tried to init a new expo managed project and eject. Then tried to run it on Android device without any change. But no luck.

By the way there is no problem projects created by `npx react-native init` with versions greater than **v0.60**. They work just fine as expected.

I'm thinking to clear all **expo** libraries and go with only react native.

**Comment by wbroek** [comment]
Did some more investigation in why this does not work on Appcenter for us, but locally it did.

First tried to manual run the Gradle task for creating the `ExpoModulesPackageList` which after some searching I think is `/gradlew :unimodules-react-native-adapter:generateExpoModulesPackageList` but this also did not generate the file `node_modules/@unimodules/react-native-adapter/android/build/generated/expo/src/main/java/org/unimodules/adapters/react/ExpoModulesPackageList.java` on Appcenter system.

The gradle task runs the newly written commands (in typescript) with the following command:
```
node --eval  "require('expo-modules-autolinking')(process.argv.slice(1))" -- generate-package-list --platform android --namespace org.unimodules.adapters.react --target node_modules/@unimodules/react-native-adapter/android/build/generated/expo/src/main/java/org/unimodules/adapters/react/ExpoModulesPackageList.java --empty
```
When we ran this on Appcenter the file was created but the build still failed with the same error `error: cannot find symbol
    mModuleRegistryProvider = new ReactModuleRegistryProvider(new ExpoModulesPackageList().getPackageList(), null);`

Looked like the file was removed again so when we looked at the build command we saw the one below
```
/Users/runner/work/1/s/android/gradlew -DAPPCENTER_BUILD_VERSION=289 -DMOBILECENTER_BUILD_VERSION=289 -p android clean :app:assembleRelease
```
Besides the DAPPCENTER_BUILD_VERSION which Appcenter adds to the line we see it uses a global gradle, runs from the project root (not the android folder) and does a clean before building.

When I run this command on my local machine it indeed failed with the same error message. Then I downloaded the example from @brentvatne on https://github.com/brentvatne/achmadk and made a build with the same command it also failed. Then I removed all parameters except the `clean` and `assembleRelease` it still fails. If I remove the clean command and only do `assembleRelease` it works?


So to reproduce: 
- git clone https://github.com/brentvatne/achmadk.git 
- cd achmadk
- yarn install
- run command line `android/gradlew -p android clean assembleRelease`

`npx react-native doctor` output:
```
Common
 ✓ Node.js
 ✓ yarn
 ✓ npm
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: 1.8.0_292
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   1
Warnings: 0
```

**Comment by rajeshde** [comment]
Cloned https://github.com/brentvatne/achmadk.git and still getting the same error.

Sharing my system info from `npx react-native info`

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 239.40 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: Not Found
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by yunusaydinonline** [comment]
Updating **Node.js** version from **v12.x.x** to **v14.17.3** has fixed my problem.

I've also made some cleaning stuff. Then it worked just fine.
```
watchman watch-del-all
rm -rf yarn.lock package-lock.json node_modules
rm -rf android/app/build
rm -rf android/.gradle
rm ios/Podfile.lock 
rm -rf ~/Library/Developer/Xcode/DerivedData
npm install && cd ios && pod update && cd ..
npm start -- --reset-cache
```
I hope it helps.

**Comment by brentvatne** [comment]
@wbroek - something changes about the semantics when you run `./gradlew clean assembleRelease` vs invoking the commands in two separate calls:

```
./gradlew clean
./gradlew assembleRelease
```

this works as expected. do you happen to have any idea what the difference is between these approaches? we run the module list generation prior to gradle preBuild: https://github.com/expo/expo/blob/a3f3a9a724bfef6c351dc378258649b3769aaee7/packages/%40unimodules/react-native-adapter/android/build.gradle#L59

**Comment by wbroek** [comment]
@brentvatne good question which I had myself as well, if I look a the task list from Gradle (see attached log) I see that the generateExpoModulesPackageList is run at the beginning of the build (made a debug statement) but every module is cleaned first and rebuild again but I do not see the debug statement run so it looks like the `preBuild` only runs 1 time at the beginning but not responding to the second preBuild step?
```
> Configure project :app
...
generateExpoModulesPackageList DEBUG
...
...
> Task :unimodules-react-native-adapter:clean
> Task :unimodules-react-native-adapter:preBuild UP-TO-DATE
> Task :unimodules-react-native-adapter:preReleaseBuild UP-TO-DATE
> Task :unimodules-react-native-adapter:compileReleaseAidl NO-SOURCE
> Task :unimodules-react-native-adapter:packageReleaseRenderscript NO-SOURCE
> Task :unimodules-react-native-adapter:writeReleaseAarMetadata FROM-CACHE
> Task :unimodules-react-native-adapter:mergeReleaseShaders FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseShaders NO-SOURCE
> Task :unimodules-react-native-adapter:generateReleaseAssets UP-TO-DATE
> Task :unimodules-react-native-adapter:packageReleaseAssets FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-react-native-adapter:generateReleaseResValues FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseResources UP-TO-DATE
> Task :unimodules-react-native-adapter:packageReleaseResources FROM-CACHE
> Task :unimodules-react-native-adapter:extractDeepLinksRelease FROM-CACHE
> Task :unimodules-react-native-adapter:processReleaseManifest FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseLibraryResources FROM-CACHE
> Task :unimodules-react-native-adapter:parseReleaseLocalResources FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseRFile FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseBuildConfig FROM-CACHE
```
[withclean.log](https://github.com/expo/expo/files/6789608/withclean.log)
[withoutclean.log](https://github.com/expo/expo/files/6789609/withoutclean.log)

**Comment by aprilmintacpineda** [comment]
> @wbroek - something changes about the semantics when you run `./gradlew clean assembleRelease` vs invoking the commands in two separate calls:
> 
> ```
> ./gradlew clean
> ./gradlew assembleRelease
> ```
> 
> this works as expected. do you happen to have any idea what the difference is between these approaches? we run the module list generation prior to gradle preBuild:
> 
> https://github.com/expo/expo/blob/a3f3a9a724bfef6c351dc378258649b3769aaee7/packages/%40unimodules/react-native-adapter/android/build.gradle#L59

You're right, running `clean` and `bundle` separately works... Weird.

**Comment by wbroek** [comment]
@brentvatne after some more investigation and some other eyes think I found the problem.
As I mentioned in my previous comment I found it odd that the task `generateExpoModulesPackageList` was not mentioned in the task list at all and that it did not run (my debug statement was not printed) only at the beginning of the total build.
This was because (what I could find) the value of `preBuild.dependsOn` (generateExpoModulesPackageList) is a direct reference to the task and is immediately executed when the build starts. Also why my debug statement was at the top of the build tasks. 
When you want to make it a value that the gradle can lookup to execute as a task we need to put into quotes (as they do in the [Gradle documentation](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:adding_dependencies_to_tasks).

So changed `preBuild.dependsOn generateExpoModulesPackageList` to `preBuild.dependsOn "generateExpoModulesPackageList"`

Then not only did the build run correctly with `./gradlew clean assembleRelease` but it also was put down as a task in the build task list:
```
> Task :unimodules-react-native-adapter:clean
> Task :unimodules-react-native-adapter:generateExpoModulesPackageList    <--** task name
generateExpoModulesPackageList DEBUG                                      <--** debug statement

> Task :unimodules-react-native-adapter:preBuild
> Task :unimodules-react-native-adapter:preReleaseBuild
> Task :unimodules-react-native-adapter:compileReleaseAidl NO-SOURCE
> Task :unimodules-react-native-adapter:packageReleaseRenderscript NO-SOURCE
> Task :unimodules-react-native-adapter:writeReleaseAarMetadata FROM-CACHE
> Task :unimodules-react-native-adapter:mergeReleaseShaders FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseShaders NO-SOURCE
> Task :unimodules-react-native-adapter:generateReleaseAssets UP-TO-DATE
> Task :unimodules-react-native-adapter:packageReleaseAssets FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseRenderscript NO-SOURCE
> Task :unimodules-react-native-adapter:generateReleaseResValues FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseResources UP-TO-DATE
> Task :unimodules-react-native-adapter:packageReleaseResources FROM-CACHE
> Task :unimodules-react-native-adapter:extractDeepLinksRelease FROM-CACHE
> Task :unimodules-react-native-adapter:processReleaseManifest FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseLibraryResources FROM-CACHE
> Task :unimodules-react-native-adapter:parseReleaseLocalResources FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseRFile FROM-CACHE
> Task :unimodules-react-native-adapter:generateReleaseBuildConfig FROM-CACHE
> Task :unimodules-react-native-adapter:compileReleaseKotlin FROM-CACHE
> Task :unimodules-react-native-adapter:javaPreCompileRelease FROM-CACHE
```

Make a PR of it now and testing it with `bare-expo`, which failed with the `./gradlew clean assembleRelease` as well
