### PR TITLE
[expo-image-picker] Add option on iOS to change dimensions and compression algorithm for video 

### LINKED ISSUE #6035: Expo imagePicker on iOS lowers video dimensions
### Environment

Expo CLI 3.4.0 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^4.0.10 => 4.0.10 

The targeted OS's are iOS and Android
### Steps to Reproduce

1- call ImagePicker.launchImageLibraryAsync({
    mediaTypes: "All"}) on iOS
2-Select any video
3-Video is being compressed by iOS
4-The returned result of the promise is:
 Object {
       "cancelled": false,
       "duration": 10044,
       "height": 1280,
       "type": "video",
       "uri": "file:///.../ImagePicker/63C082FA-C431-4964-B12B-01BCB89D1FD8.mov",
       "width": 720,
     }
5-The original video's resolution/dimensions are 1080 by 1920
6-Tried selecting a video of resolution/dimension  1024 by 576 and it returned  
Object {
       "cancelled": false,
       "duration": 30234,
       "height": 320,
       "type": "video",
       "uri": "file:///.../ImagePicker/91CFD1D3-B4DE-4D7F-9A5C-73BB0812636D.mov",
       "width": 568,
     }

### Expected Behavior

I want the videos that are being selected from expo's ImagePicker on iOS to not be compressed or with lower resolution/dimensions.
On Android the videos are being selected with the correct resolution\dimensions with no problems 
Images are also fine
### Actual Behavior

Videos selected from expo's imagePicker on iOS have lower resolution/dimensions than the original videos. 
### Reproducible Demo

https://snack.expo.io/@samyoptimize/playful-raspberrie

### PR DESCRIPTION
**Pull request by lukmccall**
# Why

Resolve #6035.

# How

Adding new options - `exportPreset`, which indicated dimensions of the output.
 
Also:
- added fallback value to `UIImagePickerControllerMediaURL` field.
- updated `ImagePicker` documentation. 

# Test Plan

- https://snack.expo.io/@lukaszkosmaty/github---imagepicker-changing-dimensions-of-video - not longer changing the dimension of the selected video (I've also tested it by changing `exportPreset` field).

### CODE REVIEW

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 1]
```diff
@@ -539,6 +553,25 @@ - (BOOL)hasCameraRollPermission
   return [self.permissionsModule hasGrantedPermission:@"cameraRoll"];
 }
 
+
+- (NSString *)mapPreset:(NSString *)preset API_AVAILABLE(ios(11));
+{
+  if ([preset isEqualToString:@"Passthrough"]) return AVAssetExportPresetPassthrough;
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I think having these mappings in a dictionary would be better and clearer than thousands of `if`s 😜

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 2]
```diff
@@ -1,8 +1,22 @@
...
+export const ExportPresets = {
+  LowQuality: 'LowQuality',
+  MediumQuality: 'MediumQuality',
+  HighestQuality: 'HighestQuality',
+  Passthrough: 'Passthrough',
+  H_264_640x480: 'H_264_640x480',
+  H_264_960x540: 'H_264_960x540',
+  H_264_1280x720: 'H_264_1280x720',
+  H_264_1920x1080: 'H_264_1920x1080',
+  H_264_3840x2160: 'H_264_3840x2160',
```
Comment (tsapeta) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]: Wouldn't `H264_*` be better than `H_264_*`? 😉

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 3]
```diff
@@ -28,16 +28,21 @@ Display the system UI for choosing an image or a video from the phone's library.
 
   A map of options for both:
 
-  - **mediaTypes (_String_)** -- Choose what type of media to pick. Usage: `ImagePicker.MediaTypeOptions.<Type>`, where `<Type>` is one of: `Images`, `Videos`, `All`.
+  - **mediaTypes ([ImagePicker.MediaTypeOptions](#imagepickermediatypeoptions)])** -- Choose what type of media to pick. Defaults to `ImagePicker.MediaTypeOptions.Images`.
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
  - **mediaTypes (_[ImagePicker.MediaTypeOptions](#imagepickermediatypeoptions)]_)** -- Choose what type of media to pick. Defaults to `ImagePicker.MediaTypeOptions.Images`.
```

**Review by bbarthec — APPROVED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 4]
```diff
@@ -556,20 +556,29 @@ - (BOOL)hasCameraRollPermission
...
-  if ([preset isEqualToString:@"H_264_1280x720"]) return AVAssetExportPreset1280x720;
-  if ([preset isEqualToString:@"H_264_1920x1080"]) return AVAssetExportPreset1920x1080;
-  if ([preset isEqualToString:@"H_264_3840x2160"]) return AVAssetExportPreset3840x2160;
-  if ([preset isEqualToString:@"H_264_960x540"]) return AVAssetExportPreset960x540;
-  if ([preset isEqualToString:@"H_264_960x540"]) return AVAssetExportPreset960x540;
-  if ([preset isEqualToString:@"HEVC_1920x1080"]) return AVAssetExportPresetHEVC1920x1080;
-  if ([preset isEqualToString:@"HEVC_3840x2160"]) return AVAssetExportPresetHEVC3840x2160;
-  return AVAssetExportPresetPassthrough;
+  static NSDictionary* presetsMap = nil;
+  if (!presetsMap) {
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I think we don't need to check whether `presetsMap` is set. Static variables are initialized only once, so it should be safe to just define them as a dictionary from the beginning.

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 5]
```diff
@@ -336,9 +341,16 @@ - (BOOL)tryCopyImage:(NSDictionary * _Nonnull)info path:(NSString *)toPath {
...
-- (void)handleVideoWithInfo:(NSDictionary * _Nonnull)info saveAt:(NSString *)directory updateResponse:(NSMutableDictionary *)response
+- (void)handleVideoWithInfo:(NSDictionary * _Nonnull)info
+                     saveAt:(NSString *)directory
+             updateResponse:(NSMutableDictionary *)response
+          completionHandler:(void (^)(void))completionHandler
 {
-  NSURL *videoURL = info[UIImagePickerControllerMediaURL];
+  NSURL *videoURL = info[UIImagePickerControllerMediaURL] ? info[UIImagePickerControllerMediaURL] : info[UIImagePickerControllerReferenceURL];
+  if (videoURL == nil) {
+    self.reject(@"E_COULDNT_OPEN_FILE", @"Couldn't open video", nil);
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I don't really like when we're defining resolve/reject callbacks as an instance member of the module. It is considered as a bad practice since it can easily break when someone call the method twice without awaiting. Don't change that now, I just wanted you to keep that in mind in the future 😉

**Review by tsapeta — CHANGES_REQUESTED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 4 above)
Comment (lukmccall) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I've done this to avoid compilation error (**"Initializer element is not a compile-time constant"**).
you can read more about this [here](https://stackoverflow.com/questions/22534251/static-nsdictionary-const-lettervalues-in-a-method-does-not-compil).

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 6]
```diff
@@ -389,9 +394,16 @@ - (BOOL)tryCopyImage:(NSDictionary * _Nonnull)info path:(NSString *)toPath {
...
+    return;
```
[the remark this answers is not in the document]
Comment (sjchmiela) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: Ok, I see that the answer is **no**, but couldn't we change the logic around this piece of code so that we always call `completionHandler` before returning from this function? We could pass an updated `response` back to the handler in case of success and `nil` in case of failure.

1. We wouldn't need to remember `self.reject` as an instance variable.
2. We would always call `completionHandler` which is something someone would expect from a completion handler
3. resolving/rejecting the promise is in one place

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 7]
```diff
@@ -389,9 +394,16 @@ - (BOOL)tryCopyImage:(NSDictionary * _Nonnull)info path:(NSString *)toPath {
...
 }
 
-- (void)handleVideoWithInfo:(NSDictionary * _Nonnull)info saveAt:(NSString *)directory updateResponse:(NSMutableDictionary *)response
+- (void)handleVideoWithInfo:(NSDictionary * _Nonnull)info
+                     saveAt:(NSString *)directory
+             updateResponse:(NSMutableDictionary *)response
+          completionHandler:(void (^)(void))completionHandler
 {
-  NSURL *videoURL = info[UIImagePickerControllerMediaURL];
+  NSURL *videoURL = info[UIImagePickerControllerMediaURL] ? info[UIImagePickerControllerMediaURL] : info[UIImagePickerControllerReferenceURL];
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
  NSURL *videoURL = info[UIImagePickerControllerMediaURL] ?: info[UIImagePickerControllerReferenceURL];
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 8]
```diff
@@ -40,8 +40,9 @@ - (instancetype)init
 {
   if (self = [super init]) {
     self.defaultOptions = @{
-                            @"allowsEditing" : @NO,
+                            @"allowsEditing": @NO,
                             @"base64": @NO,
+                            @"exportPreset": @"Passthrough",
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: There are two places now where we define _default_ value. Here and in `mapPreset:` function. Maybe we could drop one of the places? (I would say `mapPreset:` `if` guards for more invalid situations.)

File: CHANGELOG.md [hunk 9]
```diff
@@ -33,6 +33,7 @@ This is the log of notable changes to the Expo client that are developer-facing.
 - Added @react-native-community/viewpager ([#6198](https://github.com/expo/expo/pull/6198)).
 - Added `canAskAgain` and `granted` fields to `PermissionsResponse`. ([#5061](https://github.com/expo/expo/pull/5061) by [@lukmccall](https://github.com/lukmccall))
 - Added support for `react-native-appearance` on Android and Web. ([#6162](https://github.com/expo/expo/pull/6162) by [@bbarthec](https://github.com/bbarthec))
+- Added a `exportPreset` field to `ImagePickerOptions`, which indicates dimensions and compression algorithm of exported video on iOS. ([#6046](https://github.com/expo/expo/pull/6046) by [@lukmccall](https://github.com/lukmccall))
```
Comment (sjchmiela) [inline CHANGELOG.md]:
```suggestion
- Added an `exportPreset` field to `ImagePickerOptions`, which sets dimensions and compression algorithm for exported video on iOS. ([#6046](https://github.com/expo/expo/pull/6046) by [@lukmccall](https://github.com/lukmccall))
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 10]
```diff
@@ -592,6 +606,34 @@ - (BOOL)hasCameraRollPermission
...
+        @"HEVC_1920x1080": AVAssetExportPresetHEVC1920x1080,
+        @"HEVC_3840x2160": AVAssetExportPresetHEVC3840x2160
+    };
+  }
+  
+  NSString *presetSystemString = [presetsMap objectForKey:preset];
+  if (presetSystemString == nil) {
+    return AVAssetExportPresetPassthrough;
+  }
+  return presetSystemString;
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: We could use Elvis operator for default value here too

**Review by sjchmiela — COMMENTED** [review]
Great work! Could you please look at those couple of comments before we merge this? 🚀

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 6 above)
[the remark this answers is not in the document]
Comment (lukmccall) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I think it's a good idea. However, I'll do it in different PR. It's not connected with export presets and this change will affect others part of this module.

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 11]
```diff
@@ -592,6 +605,29 @@ - (BOOL)hasCameraRollPermission
   return [_permissionsManager hasGrantedPermissionUsingRequesterClass:[EXImagePickerCameraRollPermissionRequester class]];
 }
 
+
+- (NSString *)mapJSPresetToNativePreset:(NSNumber *)preset API_AVAILABLE(ios(11));
```
Comment (tsapeta) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I'd use `import`/`export` naming convention for such methods. In that case it would be:
```suggestion
- (NSString *)importExportPreset:(NSNumber *)preset API_AVAILABLE(ios(11));
```
But `importExport` sounds weird, though 😅

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 12]
```diff
@@ -1,9 +1,23 @@
...
-  All = 'All',
-  Videos = 'Videos',
-  Images = 'Images',
+export const MediaTypeOptions = {
+  All: 'All',
+  Videos: 'Videos',
+  Images: 'Images',
+} as const;
+
+export enum ExportPresets {
```
Comment (tsapeta) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]: I think enum names used to be singular when they are not bit fields 🤔

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 13]
```diff
@@ -117,3 +129,30 @@ When you run this example and pick an image, you will see the image that you pic
...
+| ------------------------- | ------------------ | --------- |
+| `MediaTypeOptions.All`    | Images and videos  | iOS       |
+| `MediaTypeOptions.Images` | Only images        | both      |
+| `MediaTypeOptions.Videos` | Only videos        | both      |
+
+### `ImagePicker.ExportPresets`
+
+| Preset                         | Resolution            | Video compression algorithm | Audio compression algorithm |
+| ------------------------------ | --------------------- | --------------------------- | --------------------------- |
+| `ExportPresets.Passthrough`    | Unchanged             | None                        | None                        |
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]: It might be a good idea to also document what are the number values of each of those enum values.

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 14]
```diff
@@ -117,3 +129,30 @@ When you run this example and pick an image, you will see the image that you pic
...
+
+### `ImagePicker.MediaTypeOptions`
+
+| Media type                | Accept asset types | Platforms |
+| ------------------------- | ------------------ | --------- |
+| `MediaTypeOptions.All`    | Images and videos  | iOS       |
+| `MediaTypeOptions.Images` | Only images        | both      |
+| `MediaTypeOptions.Videos` | Only videos        | both      |
+
+### `ImagePicker.ExportPresets`
```
Comment (tsapeta) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
## Enums

### `ImagePicker.ExportPresets`
```

**Review by tsapeta — CHANGES_REQUESTED** [review]
Generally looks good, but left a few nitpicking comments 😄 
Could you also add some tests in test-suite that use `mediaTypes` and `exportPreset` options?

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 15]
```diff
@@ -1,10 +1,24 @@
 import { PermissionResponse, PermissionStatus } from 'unimodules-permissions-interface';
 
-export enum MediaTypeOptions {
-  All = 'All',
-  Videos = 'Videos',
-  Images = 'Images',
-}
+export const MediaTypeOptions = {
```
[the remark this answers is not in the document]
Comment (sjchmiela) [reply packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]: `MediaTypeOptions` remained `export const`

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 16]
```diff
@@ -22,13 +36,14 @@ export type ImagePickerOptions = {
   aspect?: [number, number];
   quality?: number;
   allowsMultipleSelection?: boolean;
-  mediaTypes?: MediaTypeOptions;
+  mediaTypes?: typeof MediaTypeOptions[keyof typeof MediaTypeOptions];
```
Comment (sjchmiela) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]:
```suggestion
  mediaTypes?: MediaTypeOptions;
```

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 17]
```diff
@@ -22,13 +36,14 @@ export type ImagePickerOptions = {
...
   exif?: boolean;
   base64?: boolean;
+  exportPreset?: ExportPreset;
 };
 
 export type OpenFileBrowserOptions = {
-  mediaTypes: MediaTypeOptions;
+  mediaTypes: typeof MediaTypeOptions[keyof typeof MediaTypeOptions];
```
Comment (sjchmiela) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]:
```suggestion
  mediaTypes: MediaTypeOptions;
```

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 18]
```diff
@@ -389,9 +393,16 @@ - (BOOL)tryCopyImage:(NSDictionary * _Nonnull)info path:(NSString *)toPath {
...
+- (void)handleVideoWithInfo:(NSDictionary * _Nonnull)info
+                     saveAt:(NSString *)directory
+             updateResponse:(NSMutableDictionary *)response
+          completionHandler:(void (^)(void))completionHandler
 {
-  NSURL *videoURL = info[UIImagePickerControllerMediaURL];
+  NSURL *videoURL = info[UIImagePickerControllerMediaURL] ?: info[UIImagePickerControllerReferenceURL];
+  if (videoURL == nil) {
+    self.reject(@"E_COULDNT_OPEN_FILE", @"Couldn't open video", nil);
+    return;
```
Comment (sjchmiela) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]:
```suggestion
    // not calling completionHandler here, as it's only purpose is to resolve the promise and we rejected it right here
    return;
```

Comment (sjchmiela) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: ~Shouldn't we also clear `self.resolve` and `self.reject` here?~

Ah, I see the previous instances are lost if we call two methods consecutively without awaiting… 😢

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 19]
```diff
@@ -74,7 +74,7 @@ Display the system UI for choosing an image or a video from the phone's library.
 
   Option for videos:
 
-  - **exportPreset (_[ImagePicker.ExportPresets](#imagepickerexportpresets)_)** -- **Available on iOS 11+ only.** Specify preset, which will be used to compress selected video. Defaults to `ImagePicker.ExportPresets.Passthrough`.
+  - **exportPreset (_[ImagePicker.ExportPreset](#imagepickerexportpreset)_)** -- **Available on iOS 11+ only.** Specify preset, which will be used to compress selected video. Defaults to `ImagePicker.ExportPreset.Passthrough`.
```
Comment (bbarthec) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]: I don't like this new option name at all 😞 
First thing: I don't like that this sounds like method name, because it contains some verb (`Export`). (ImagePicker.ExportedPreset sounds betters, but I would rather go with `SupportedPreset` at this point 🤔, but see second thing)
Second thing: the name mismatch with the actual behaviour: `exportPreset` vs `use selected preset to compress picked video`. Method is `launchImageLibraryAsync` and you change video picking process so I would stick with the some word that somehow describes what's happening. (names coming to my mind: `videoCompressionPreset`, `pickedVideoCompressionPreset` ❓ cc @sjchmiela, @tsapeta)

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 20]
```diff
@@ -89,13 +94,20 @@ Display the system UI for taking a photo with the camera. Requires `Permissions.
...
+  A map of options for images:
+
   - **aspect (_array_)** -- An array with two entries `[x, y]` specifying the aspect ratio to maintain if the user is allowed to edit the image (by passing `allowsEditing: true`). This is only applicable on Android, since on iOS the crop rectangle is always a square.
   - **quality (_number_)** -- Specify the quality of compression, from 0 to 1. 0 means compress for small size, 1 means compress for maximum quality.
   - **base64 (_boolean_)** -- Whether to also include the image data in Base64 format.
   - **exif (_boolean_)** -- Whether to also include the EXIF data for the image. On iOS the EXIF data does not include GPS tags in the camera case.
 
+  Option for videos:
+
+  - **exportPreset (_[ImagePicker.ExportPresets](#imagepickerexportpresets)_)** -- **Available on iOS 11+ only.** Specify preset, which will be used to compress selected video. Defaults to `ImagePicker.ExportPresets.Passthrough`.
```
Comment (sjchmiela) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
  - **exportPreset (_[ImagePicker.ExportPresets](#imagepickerexportpresets)_)** -- **Available on iOS 11+ only.** Specify preset which will be used to compress selected video. Defaults to `ImagePicker.ExportPresets.Passthrough`.
```

File: docs/pages/versions/unversioned/sdk/imagepicker.md [hunk 21]
```diff
@@ -60,17 +60,22 @@ Display the system UI for choosing an image or a video from the phone's library.
...
 
   - **aspect (_array_)** -- An array with two entries `[x, y]` specifying the aspect ratio to maintain if the user is allowed to edit the image (by passing `allowsEditing: true`). This is only applicable on Android, since on iOS the crop rectangle is always a square.
   - **quality (_number_)** -- Specify the quality of compression, from 0 to 1. 0 means compress for small size, 1 means compress for maximum quality.
+    > **Note:** If the selected image has been compressed before, the size of the output file may be bigger than the size of the original image.
   - **base64 (_boolean_)** -- Whether to also include the image data in Base64 format.
   - **exif (_boolean_)** -- Whether to also include the EXIF data for the image.
 
+  Option for videos:
+
+  - **exportPreset (_[ImagePicker.ExportPreset](#imagepickerexportpreset)_)** -- **Available on iOS 11+ only.** Specify preset, which will be used to compress selected video. Defaults to `ImagePicker.ExportPreset.Passthrough`.
```
Comment (sjchmiela) [inline docs/pages/versions/unversioned/sdk/imagepicker.md]:
```suggestion
  - **exportPreset (_[ImagePicker.ExportPreset](#imagepickerexportpreset)_)** -- **Available on iOS 11+ only.** Specify preset which will be used to compress selected video. Defaults to `ImagePicker.ExportPreset.Passthrough`.
```

**Review by sjchmiela — APPROVED** [review]
A couple more small comments. Apart from that I think it should be ready to go! 💯

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m [hunk 22]
```diff
@@ -606,15 +606,15 @@ - (BOOL)hasCameraRollPermission
 }
 
 
-- (NSString *)mapJSPresetToNativePreset:(NSNumber *)preset API_AVAILABLE(ios(11));
+- (NSString *)importExportPreset:(NSNumber *)preset API_AVAILABLE(ios(11));
 {
   static NSDictionary* presetsMap = nil;
   if (!presetsMap) {
     presetsMap = @{
```
Comment (bbarthec) [inline packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: `presetsMap` - what presets?
`videoCompressionPresets`. I dunno about `Map` suffix in name 😛

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 23]
```diff
@@ -6,11 +6,11 @@ export const MediaTypeOptions = {
   Images: 'Images',
 } as const;
 
-export enum ExportPresets {
-  LowQuality = 0,
-  MediumQuality = 1,
-  HighestQuality = 2,
-  Passthrough = 3,
+export enum ExportPreset {
```
Comment (bbarthec) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]: See comment regarding docs.

File: packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts [hunk 24]
```diff
@@ -39,7 +39,7 @@ export type ImagePickerOptions = {
   mediaTypes?: typeof MediaTypeOptions[keyof typeof MediaTypeOptions];
   exif?: boolean;
   base64?: boolean;
-  exportPreset?: typeof ExportPresets[keyof typeof ExportPresets];
+  exportPreset?: ExportPreset;
```
Comment (bbarthec) [inline packages/expo-image-picker/src/ImagePicker/ImagePicker.types.ts]: Comment regarding docs.

**Review by bbarthec — CHANGES_REQUESTED** [review]

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 22 above)
Comment (sjchmiela) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I am for the `Map` suffix, it's only purpose is to **map** preset number to a preset, so the name explains its purpose

File: docs/pages/versions/unversioned/sdk/imagepicker.md (hunk 19 above)
Comment (sjchmiela) [reply docs/pages/versions/unversioned/sdk/imagepicker.md]: I would say that **export** is also a noun ([source](https://dictionary.cambridge.org/dictionary/english/export))

> **the activity or business of sending goods to another country in order to sell them there:**
> - **the export of sth** _The ruling banned the export of live cattle._
> - _Most of their crops are grown **for export**._
> - _**an export company/business**_

Moreover, this is the name that Apple documentation uses — https://developer.apple.com/documentation/avfoundation/avassetexportsession/export_preset_names_for_apple_devices?language=objc

Comment (bbarthec) [reply docs/pages/versions/unversioned/sdk/imagepicker.md]: Oh! @sjchmiela, that's correct 😉 You see I didn't check what's Apple approach for this thing 😅. So at this point I' m not sure which one should we choose 😓

Comment (bbarthec) [reply docs/pages/versions/unversioned/sdk/imagepicker.md]: After a small discussion with @tsapeta we consider `videoCompressionPreset` to be most suitable name for this parameter 😉
From one side: we need to explicitly state that this parameter affect only video, so `videoXX` and from the other side: we can go with `xxExportPreset`, but this name does not play well with method name IMO and of course it has much sense, but not in this case 😉

Comment (bbarthec) [reply docs/pages/versions/unversioned/sdk/imagepicker.md]: Other thing is that we can omit `video` prefix but only if use `Union Type` feature of TypeScript language for this method parameters to ensure consistency of arguments and execution.

Comment (bbarthec) [reply docs/pages/versions/unversioned/sdk/imagepicker.md]: @lukmccall `videoExportPreset` ⬅️ go with this one 😉 this is my final word here

File: packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m (hunk 22 above)
Comment (bbarthec) [reply packages/expo-image-picker/ios/EXImagePicker/EXImagePicker.m]: I withdraw from my comment here 😉 I see that this variable is static and available from this method context only so I'm 💯% okay with the way how it's now 😉

File: CHANGELOG.md [hunk 25]
```diff
@@ -35,6 +35,7 @@ This is the log of notable changes to the Expo client that are developer-facing.
 - Added support for `react-native-appearance` on Android and Web. ([#6162](https://github.com/expo/expo/pull/6162) by [@bbarthec](https://github.com/bbarthec))
 - Added `Location.getLastKnownPositionAsync` to get the last known position of the device. ([#6246](https://github.com/expo/expo/pull/6246) by [@lukmccall](https://github.com/lukmccall))
 - Added `exif` and `base64` properties into the TypeScript definitions for `ImagePickerResult` in `expo-image-picker`. ([#6311](https://github.com/expo/expo/pull/6311) by [@kyletsang](https://github.com/kyletsang))
+- Added an `videoExportPreset` field to `ImagePickerOptions`, which sets dimensions and compression algorithm for exported video on iOS. ([#6046](https://github.com/expo/expo/pull/6046) by [@lukmccall](https://github.com/lukmccall))
```
Comment (sjchmiela) [inline CHANGELOG.md]:
```suggestion
- Added a `videoExportPreset` field to `ImagePickerOptions`, which sets dimensions and compression algorithm for exported video on iOS. ([#6046](https://github.com/expo/expo/pull/6046) by [@lukmccall](https://github.com/lukmccall))
```

**Review by sjchmiela — APPROVED** [review]

**Review by tsapeta — APPROVED** [review]
