### ISSUE TITLE
🐛 [SDK 56 preview.7] await of an async function's Promise resolves to undefined while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS

### ISSUE THREAD

**Issue by azaars** [expo/expo#45592]
# 🐛 [SDK 56 preview.7] `await` of an async function's Promise resolves to `undefined` while the underlying function runs to completion later — breaks RTK Query queryFn dispatch on iOS

## Summary

On `expo@56.0.0-preview.7` (`react-native@0.85.3`, Hermes default, iOS simulator), `await aPromise` resolves with `undefined` *before* the underlying `async function` reaches its `return` statement. The function continues executing in the background, its `return` does eventually fire with the correct value, but the awaiting caller has already moved on with `undefined`.

The same userland code works correctly on `expo@55.0.23` / `react-native@0.83.6`.

The most visible symptom: **every RTK Query `queryFn`-based endpoint fails** because the dispatcher's internal `await executeRequest(arg)` resolves to `undefined`, then `finalQueryReturnValue.data` access throws `TypeError: Cannot read property 'data' of undefined`. Identical `@reduxjs/toolkit@2.11.2` works on SDK 55 with the same userland code.

## Minimal reproducible example

**Repro:** https://github.com/azaars/expo-56-rtk-await-bug

```bash
git clone https://github.com/azaars/expo-56-rtk-await-bug.git
cd expo-56-rtk-await-bug
npm install
npx expo prebuild --clean --platform ios
npx expo run:ios
```

The repro is `npx create-expo-app@latest --template blank-typescript` scaffolded, then bumped to `expo@next`, with `@reduxjs/toolkit` + `react-redux` added and a single `queryFn` endpoint that returns `{ data: { message: 'hello from queryFn' } }`. Three small files: `src/api.ts` (createApi), `src/store.ts` (configureStore), `App.tsx` (Provider + a child that subscribes via `useGetThingQuery()`).

## Steps to reproduce

1. Clone and install per above.
2. `npx expo prebuild --clean --platform ios && npx expo run:ios`.
3. App boots in iOS simulator. The single screen renders.

## Expected behavior

```
isLoading: false
isError:   false
data:      {"message":"hello from queryFn"}
error:     (none)
```

## Actual behavior

```
isLoading: false
isError:   true
data:      undefined
error:     {"status":"CUSTOM_ERROR","error":"Cannot read property 'data' of undefined"}
```

Metro logs:

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning: {"data":{"message":"hello from queryFn"}}
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       In the case of an unhandled error, no tags will be "provided" or "invalidated".
       [TypeError: Cannot read property 'data' of undefined]
```

## Diagnostic evidence

In a parallel investigation I patched `node_modules/@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` at the dispatcher's await call site:

```js
// Patched at line 1091 of executeEndpoint:
const __exr_promise = executeRequest(arg.originalArgs);
console.log('[RTK PATCH] BEFORE-AWAIT typeof:', typeof __exr_promise,
            'isPromise:', __exr_promise instanceof Promise,
            'isUndefined:', __exr_promise === undefined);
finalQueryReturnValue = await __exr_promise;
console.log('[RTK PATCH] AFTER-AWAIT finalQueryReturnValue =',
            JSON.stringify(finalQueryReturnValue),
            'type:', typeof finalQueryReturnValue);

// And patched executeRequest's return statement (~line 1041):
const __ret = __spreadProps(__spreadValues({}, result), { data: transformedResponse });
console.log('[RTK PATCH] executeRequest about to return:',
            JSON.stringify(__ret), 'type:', typeof __ret);
return __ret;
```

Time-ordered output from the iOS simulator (with the queryFn reduced to a synchronous return of a hoisted constant `{ data: [] }` to eliminate userland variables):

```
LOG    [REPRO][queryFn] entered
LOG    [REPRO][queryFn] returning hoisted: {"data":[]}
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  An unhandled error occurred processing a request for the endpoint "getThing".
       [TypeError: Cannot read property 'data' of undefined]
LOG    [RTK PATCH] executeRequest about to return: {"data":[]} type: object
```

Note the **time ordering**:

1. `BEFORE-AWAIT` confirms `executeRequest()` returns a real `Promise` synchronously (`isPromise: true`, `isUndefined: false`).
2. `AFTER-AWAIT` resumes immediately with `undefined`.
3. The dispatcher's catch block logs the unhandled error.
4. **Only afterwards** does `executeRequest`'s body reach its return statement and log the correct value.

A nested-`await` test inside the queryFn itself behaves consistently — the inner await resolves with the right value, but only after RTK's outer await has already moved on:

```
LOG    [REPRO] outer enter
LOG    [REPRO] inner enter
LOG    [REPRO] before await, p instanceof Promise: true typeof p: object
LOG    [RTK PATCH] BEFORE-AWAIT typeof: object isPromise: true isUndefined: false
LOG    [RTK PATCH] AFTER-AWAIT finalQueryReturnValue = undefined type: undefined
ERROR  [TypeError: Cannot read property 'data' of undefined]
LOG    [REPRO] after await, r: {"data":[]} typeof: object
```

## Same pattern in non-RTK code

In a private brownfield app on the same SDK 56 preview.7 stack, the same pattern surfaces in code that has nothing to do with RTK Query:

```ts
const localPlants = await soloTaskService.getLocalPlants('solo-user', 'active');
// → throws TypeError: Cannot read property 'map' of undefined on the next line
const mappedPlants = localPlants.map((lp) => ({...}));
```

`SoloTaskService.getLocalPlants` is a class `async` method that ends with `return rows.map(...)`. The await receives `undefined`. Same root cause, completely separate call path. Not included in the public minimal repro because reproducing it cleanly requires recreating that class context, but happy to share if useful.

## What was ruled out

- **`@reduxjs/toolkit` version**: identical `2.11.2` works on SDK 55 / RN 0.83.6 with the same userland code.
- **`react-redux` version**: `9.2.0`, unchanged across SDKs.
- **`react-native-reanimated`/`worklets` babel plugin**: bug reproduces with `react-native-reanimated/plugin` removed from `babel.config.js` and Metro restarted with `--clear`.
- **Userland code**: queryFn reduced to a hoisted-constant synchronous return. Bug persists.
- **`baseQuery: fakeBaseQuery()` vs `baseQuery: async () => ({ data: null })`**: bug fires with both.
- **`providesTags`** as static array vs callback: no difference.
- **Node test suite**: `npm test` (Node + ts-jest + better-sqlite3, no Hermes) passes 3028/3030 in the brownfield app on SDK 56. Bug is iOS-Hermes-runtime-only.

## Suspected scope

The dispatcher in `@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js` declares `executeRequest` as a hoisted nested `async function` inside another `async function`:

```js
async function executeEndpoint(arg, ...) {
  // ...
  async function executeRequest(finalQueryArg) {
    // ...
    return __spreadProps(...);
  }
  // ...
  finalQueryReturnValue = await executeRequest(arg.originalArgs);
  // → undefined here despite executeRequest returning a Promise that
  //   eventually resolves to the correct value
}
```

The same nested-async-function-declaration pattern is what surfaces the bug in the non-RTK case as well. This points to Hermes RN 0.85.3's async-function / Promise resolution machinery rather than RTK or app code.

## Environment

```
expo-env-info 2.0.12 environment info:
  System:
    OS: macOS 26.4.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 25.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 11.12.1 - /opt/homebrew/bin/npm
    Watchman: 2025.11.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
  IDEs:
    Android Studio: 2025.1 AI-251.26094.121.2513.14007798
    Xcode: 26.4.1/17E202 - /usr/bin/xcodebuild
  npmPackages:
    expo: ^56.0.0-preview.7 => 56.0.0-preview.7
    react: 19.2.3 => 19.2.3
    react-dom: 19.2.3 => 19.2.3
    react-native: 0.85.3 => 0.85.3
  npmGlobalPackages:
    eas-cli: 16.19.3
  Expo Workflow: bare (custom dev client via expo-dev-client)
```

Additional minimal-repro deps:

- `@reduxjs/toolkit@2.11.2`
- `react-redux@9.2.0`
- `babel-preset-expo@56.0.5`

## Asks

1. Is this a known issue in the SDK 56 preview Hermes / RN 0.85.3?
2. Workaround guidance for the next 1–2 weeks until SDK 56 GA?
3. Happy to attach the patched `rtk-query.legacy-esm.js`, run further traces, or drop into Discord for live debugging if useful.

**Comment by gronxb** [comment]
workaround 

```
npx expo customize babel.config.js
```

```js
module.exports = function (api) {
  api.cache(true);

  return {
    presets: ["babel-preset-expo"],
    plugins: ["@babel/plugin-transform-async-to-generator"],
  };
};
```

-----


I ran into what looks like the same problem while debugging on Expo SDK 56 / RN 0.85.

At first it looked like `fetch` was broken:

```ts
const response = await fetch(url, options);
console.log(response); // undefined
```

But the same request worked if I used promise chaining:

```ts
fetch(url, options).then((response) => {
  console.log(response); // valid Response
});
```

So I don't think the network request or `fetch` itself is the real problem. It looks more like the Promise resolves correctly, but the native `await` path resumes with `undefined`.

One thing I noticed is that Expo SDK 56's Babel preset selects the Hermes V1 profile when the caller engine is Hermes. That profile preserves native `async`/`await`, while the older Hermes V0/default profile includes `@babel/plugin-transform-async-to-generator`.

As a quick test, I added this to the app:

```js
module.exports = function (api) {
  api.cache(true);

  return {
    presets: ["babel-preset-expo"],
    plugins: ["@babel/plugin-transform-async-to-generator"],
  };
};
```

After forcing async functions through `async-to-generator`, the broken `await fetch(...)` path started working again.

So my current guess is:

- `fetch` resolves with a valid `Response`
- `.then(...)` sees that value correctly
- native `await` on this Expo SDK 56 / RN 0.85 / Hermes V1 stack sometimes gets `undefined`
- forcing `async-to-generator` avoids that Hermes native await path

That seems to line up with this issue pretty closely.

**Comment by baveku** [comment]
It appears the root cause has finally surfaced. My associates (Claude, Gemini, Codex) and I spent over a day investigating why every API response was returning as undefined. We were at a complete dead end until I came across this issue.

**Comment by byCedric** [comment]
We might actually be hitting this issue https://github.com/facebook/hermes/issues/1761.

Edit, yes we are. Ran Hermes from source, on the parent commit of the fix commit, with the following reproducible snippet (courtesy of @kitten). The latest `static_h` version of Hermes handles this correctly.

```js
async function test() {
  const f = async ({ b }) => 42;
  return await f({ b: 1 });
}

test().then(result => console.log('Result:', result));

// > Result: undefined
```

**Comment by WadhahEssam** [comment]
this issue is fixed in dev buidls, but still happens to me in production builds, not quite sure if its the same issue or not. but it behaves the same way

**Comment by WadhahEssam** [comment]
Update: it doesn't seem like its the same issue, because when I switched to axios it worked fine

**Comment by boris-szl** [comment]
What is the status on this? Fixed? Is the fix which was deployed working for you all?

**Comment by mzaien** [comment]
> What is the status on this? Fixed? Is the fix which was deployed working for you all?

It is fixed, Update babel-preset-expo to latest  @boris-szl
