### ISSUE TITLE
Android: SDK upgrade from 44 to 46 width android sdk 31 failed,  Error: Exception in HostObject::get(propName:NativeUnimoduleProxy)

### ISSUE THREAD

**Issue by nathanwkwong** [expo/expo#19316]
### Summary

**Description**

After upgrading expo SDK from 44 to 46 and react-native from 0.66.1 to 0.69.5, then import a package from expo, e.g. expo-camera, expo-constants, expo-file-system to App.js will so the following error:

```
from expo-constatns and expo-secure-store:
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.NoClassDefFoundError: expo.modules.kotlin.jni.JSIInteropModuleRegistry

from expo-media-library:
Error: Exception in HostObject::get(propName:NativeUnimoduleProxy): java.lang.UnsatisfiedLinkError: dlopen failed: library "libexpo-modules-core.so" not found

```

### What platform(s) does this occur on?

Android

### Environment

Node v16.15.1
React Native version: 0.69.5
Workflow: React Native without Expo

**Platforms**: Android
**compileSdkVersion** 31
**targetSdkVersion** 31
**Gradle version** 7.3.3
**enableHermes** false
**Architecture** Paper( Old Architecture)
**Device** Android emulator (Pixel 4 Android 11, Google Play | arm64)

### Minimal reproducible example

1. Upgrade react native from 0.66.1 to 0.69.5 and follow the react native upgrade helper, https://react-native-community.github.io/upgrade-helper/, and change the codebase
2. Upgrade from 2.9.1 to 2.10.0
3. Without importing any expo package, open the app and confirmed there is simple text rendering on screen
4. Import a package from expo, e.g. expo-camera, expo-constants, the failure message appear and stuck at splash screen

**Comment by nickrugge** [comment]
I'm experiencing the same issue.

### Description

Ejected a new expo v46 managed project to bare workflow.

On iOS everything is ok.

On android it correctly builds and installs the app on the emulator.
Immediately after the bundling is complete the app crashes with error `java.lang.UnsatisfiedLinkError: dlopen failed: library "libexpo-modules-core.so" not found`.


### Environment:

Node v16.15.1
React Native version: 0.69.6
Workflow: Ejected Expo project (bare)

Platforms: Android
compileSdkVersion 31
targetSdkVersion 31
Gradle version 7.3.3
enableHermes false
Mac M1
Device Android emulator (Pixel 5 Android SDK 33, Google Play | arm64)

**Comment by chuanfan2** [comment]
同问，解决了吗
