### ISSUE TITLE
React Native 0.67.3 expo-dev-launcher Android Task :expo-dev-launcher:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by leejunhui** [expo/expo#16465]
### Summary

Recently I try to upgrade my react native project version to 0.67.3. And after upgrade the expo-dev-client to 0.8.4, the android side still produces the error as below:

```bash
> Task :expo-dev-launcher:compileDebugKotlin FAILED
e: /../node_modules/expo-dev-launcher/android/src/react-native-66/expo/modules/devlauncher/rncompatibility/DevLauncherDevSupportManager.kt: (58, 1): No value passed for parameter 'surfaceDelegateFactory'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expo-dev-launcher:compileDebugKotlin'.
> Compilation error. See log for more detai
```

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

 Expo CLI 5.1.1 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.18.0 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 23, 28, 29, 30, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 32.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.67.3 => 0.67.3 
    npmGlobalPackages:
      expo-cli: 5.1.1
    Expo Workflow: bare

### Reproducible demo

N/A

**Comment by lukmccall** [comment]
This bug was fixed in the https://github.com/expo/expo/pull/16038. Those changes weren't published yet and will be part of the next `expo-dev-client` version.

For now, I'll close this issue.

**Comment by mrbrentkelly** [comment]
Any idea on when the version of `expo-dev-client` (and `expo-dev-launcher`) that supports RN 0.67 will be released? Currently released version is 0.8.4 which only supports up to RN66.
