### ISSUE TITLE
expo-linking typescript errors 

### ISSUE THREAD

**Issue by zakharchenkoAndrii** [expo/expo#17866]
### Summary

Hi! After upgrading SDK version from 44 to 45 our TS linter started to complain about expo-linking library.
Here is the error summary after running `tsc --noEmit`:
```
node_modules/expo-linking/src/Linking.types.ts:1:26 - error TS7016: Could not find a declaration file for module 'qs'. '/Users/user/Work/app/node_modules/expo-linking/node_modules/qs/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/qs` if it exists or add a new declaration (.d.ts) file containing `declare module 'qs';`

1 import { ParsedQs } from 'qs';
                           ~~~~

node_modules/expo-linking/src/Linking.types.ts:39:17 - error TS2304: Cannot find name 'MessageEvent'.

39   nativeEvent?: MessageEvent;
                   ~~~~~~~~~~~~

node_modules/expo-linking/src/Linking.types.ts:46:47 - error TS2304: Cannot find name 'MessageEvent'.

46 export type NativeURLListener = (nativeEvent: MessageEvent) => void;
                                                 ~~~~~~~~~~~~
```
my tsconfig includes  ` "skipLibCheck": true,` option

 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/Work/app/node_modules/.bin/yarn
      npm: 6.14.17 - ~/Work/app/node_modules/.bin/npm
      Watchman: 2022.01.31.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/user/.gem/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 16.13.1 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: ^0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.8
    Expo Workflow: bare
```

### Reproducible demo
"typescript": "4.7.3"
run `tsc --noEmit`
